### ISSUE TITLE
Nested associations not being validated when more than one exist

### ISSUE THREAD

**Issue by olliefreeman** [grails/grails-data-mapping#1006]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create domain class AlphaChild and BetaChild with a couple of simple properties and constraints, say `String label` which is `nullable: false` for both
2. Create domain class Parent with ```hasMany = [
    alphaChildren: AlphaChild,
    betaChildren:BetaChild
]``` and set `belongsTo = [parent:Parent]` in the Child classes
3. Create domain class SuperParent with ```hasMany = [
    parents: Parent
]``` and set `belongsTo = [superParent:SuperParent]` in the Parent classes
4. Create a domain unit test for the SuperParent which sets up invalid an invalid child class
```
Parent parent = new Parent()
        parent.addToAlphaChildren(label: 'valid child')
        parent.addToBetaChildren(new BetaChild())
        domain.addToParents(parent)
```
5. Call `domain.validate()`

### Expected Behaviour

There should be an error in the domain as the child is invalid

### Actual Behaviour

The domain is valid.

### Environment Information

- **Operating System**: Mac OS X Sierra
- **GORM Version:** 6.1.7
- **Grails Version (if using Grails):** 3.3.0
- **JDK Version:** 1.8.0_131

### Example Application

- https://github.com/olliefreeman/grails-issues 
Run the rest.api.app.SupremeParentSpec tests.

### Reason

In `grails.gorm.validation.PersistentEntityValidator` in the `validate` method the `cascadeToAssociativeProperty` is passed with a new HashSet for the `validatedObjects` property. However once nesting into objects (as expected) this set is passed into each subsequent call.
Line 107 adds the parent to the set, however whilst this is fine for the first association, all subsequent associations are returned at line 105 due to the boolean check `validatedObjects.contains(parent)`, which it does as it was added for the previous association.

The solution is probably to have `validatedObjects.remove(parent)` at line 133 as the final line in the `cascadeToAssociativeProperty` method.

**Comment by olliefreeman** [comment]
I am working on building a git repo with this as an example...i cannot share the codebase which I have this failing in.

**Comment by jameskleeh** [comment]
Thanks!
