### ISSUE TITLE
Where query fails if using "embedded" on field association

### ISSUE THREAD

**Issue by AdrienGuichard** [grails/grails-data-mapping#1035]
The following action that contains a where query fails if "Address" class is embedded into Contact. 
It is Ok otherwise.

```
class WhereController {

    def index() {
        DetachedCriteria<Partner> partners = Partner.where {
            contact.address.city =~ "Paris"
        }

        render "OK" + partners.list()
    }
}

```
```
package contact

class Contact {
    Address address

    static embedded = ['address']
    static constraints = {
    }
}
```

### Steps to Reproduce

1. Unpack the provided test case [whereQueries.tar.gz](https://github.com/grails/grails-data-mapping/files/1568920/whereQueries.tar.gz)
2. in the resulting folder, executes 

> $ ./gradlew bootrun

3. after startup, go to [http://localhost:8080/where]( http://localhost:8080/where)

### Expected Behaviour

No errors should happen. No errors happen if we remove the line 
`    static embedded = ['address']
`
from Contact.groovy. This line seems to be responsible for the exception raised.

### Actual Behaviour

The server has an internal error, caused by a hibernate exception (**org.hibernate.QueryException** could not resolve property: address of: contact.Partner)

### Environment Information

- **Operating System**: x86_64 GNU/Linux
- **GORM Version:** 6.1.8.RELEASE
- **Grails Version (if using Grails):** 3.3.2
- **JDK Version:** openjdk version "1.8.0_131"

Thanks for your support!

**Comment by puneetbehl** [comment]
Fixed with commit d945152282b4540399dc9e65a669a91c400084ea
