### ISSUE TITLE
PagedResultList.getTotalCount raises NullPointerException if query result return no rows.

### ISSUE THREAD

**Issue by gtors** [grails/grails-data-mapping#1050]
If the query created via `createCriteria`  with criterias that will lead to return empty result, then the call of `getTotalCount` on `PagedResultList` will always raise a `NullPointerException`.

Example:
```groovy
def result = SomeDomain.createCriteria().list(max: 1) {
      lt 'id' , 0
})

result.getTotalCount() // will cause NullPointerException
```

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Make query like this: `def result = AnyDomain.createCriteria().list(max: 123) { }` with the filter condition that guaranteed to not return records 
2. Try to obtain total rows count via `result.getTotalsCount()`

### Expected Behaviour

`0` will be returned

### Actual Behaviour

NullPointerException

### Environment Information

- **Operating System**:  Arch Linux
- **GORM Version:** 6.1.8
- **Grails Version (if using Grails):** 3.2.11
- **JDK Version:** 1.8

**Comment by puneetbehl** [comment]
@gtors Can you please upload the example replicating the issue. I am not able to replicate the issue by following above steps.

**Comment by gtors** [comment]
@puneetbehl I have update the example. Now it should be reproducible.

**Comment by gtors** [comment]
Also, you may look at test in my pull-request: https://github.com/gtors/grails-data-mapping/commit/ce742edbf2b458c9aa9beebe6a95b05c155ac4ed#diff-f05d6706e5ab0b0519907d1fe64b0d58

**Comment by puneetbehl** [comment]
Yes, that's where I am confused because I tried to run the without your code changes in `PagedResultList` and they work fine.

**Comment by gtors** [comment]
Ok, I will recheck it

**Comment by gtors** [comment]
I can reproduce it only in my grails service...  
As I understand, root of the evil in this line: https://github.com/grails/gorm-hibernate5/blob/master/grails-datastore-gorm-hibernate5/src/main/groovy/grails/orm/PagedResultList.java#L44

**Comment by gtors** [comment]
```
java.lang.NullPointerException: null
    at grails.gorm.PagedResultList.initialize(PagedResultList.java:103)
    at grails.gorm.PagedResultList.getTotalCount(PagedResultList.java:50)
    at sun.reflect.GeneratedMethodAccessor1153.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
    at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:64)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
    at myapp.ManagersService.$tt__getManagers(ManagersService.groovy:315)
... 
```

**Comment by erichelgeson** [comment]
We get this in our app as well - https://github.com/erichelgeson/grails1050/commit/85a42233a00e05bfb65c74b2f8e9c478fd330ce5 is an example of the NPE.

totalCount works when it finds items, but throws NPE when it doesnt, though i'd expect it to just return 0.
