### ISSUE TITLE
Lazy associations with inheritance do not unwrap Hibernate proxy anymore

### ISSUE THREAD

**Issue by adrianotr** [grails/grails-data-mapping#1072]
I am migrating a Grails 2.4 application to Grails 3.3 and I noticed that the behaviour of Lazy initialized associations using inheritance has changed since this commit:
https://github.com/grails/gorm-hibernate5/commit/0679a0a2e465a486ffd316d729c12c649f53d78d

It seems that because the line`GrailsDomainBinder.java:3263` was commented, the method `HibernateUtils.handleLazyProxy` is never called. It seems that that line of code was committed by mistake.

### Steps to Reproduce

Given the domain classes:
```
class Pet {
}

class Dog extends Pet {
}

class Owner {
    Pet pet
}
```

Now, supposing that `Owner` has a `pet` of type `Dog`. 
This used to work but fails since gorm 6.1.3
```
def owner = Owner.get(id)
assert owner.pet instanceof Dog
```

### Expected Behaviour

GORM should unwrap the hibernate proxy  when the getter is called and return an instance of the proper subclass.
In fact, that used to be the actual behaviour before this commit:
https://github.com/grails/gorm-hibernate5/commit/0679a0a2e465a486ffd316d729c12c649f53d78d

### Actual Behaviour

The assertion above fails because `owner.pet` is returning a hibernate proxy that is a subclass of `Pet`, not `Dog`. It used to unwrap the proxy into the correct subclass (`Dog`).

This has lead to some silent errors because some of our logic checks the subtype using `instanceof`. eg:
```
if (owner.pet instanceof Dog) {
   // then do something
} else {
  // do something else
}
```

### Environment Information

- **Operating System**: MAC
- **GORM Version:** 6.1.8
- **Grails Version (if using Grails):** 3.3.2
- **JDK Version:** 1.8.0_151

**Comment by jameskleeh** [comment]
Thanks for the report and the digging to find the cause. Made fixing the issue much faster.
