### ISSUE TITLE
Data services. JPA-QL in @Query annotation can't recognize property id

### ISSUE THREAD

**Issue by kefirfromperm** [grails/grails-data-mapping#1078]
When I try to use property **id** in the `@Query` annotation it fails on compilation.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a simple domain object
```groovy
class Book {
    String title

    static constraints = {
    }
}
```
2. Create a data service
```groovy
@Service(Book)
interface BookService {
    @Query("update ${Book book} set ${book.title} = $title where ${book.id} = $id")
    void update(long id, String title)
}
```
3. build
```
gradlew build
```

### Expected Behaviour

It is compiled

### Actual Behaviour

Is is not compiled and show error

```
/home/kefir/projects/gorm-bug-sample/grails-app/services/gorm/bug/sample/BookService.groovy: 8: No property [id] existing for domain class [gorm.bug.sample.Book]
 @ line 8, column 67.
   ${book.title} = $title where ${book.id} 
```

### Environment Information

- **Operating System**: OpenSUSE Leap 42.3
- **GORM Version:** 6.1.9.RELEASE
- **Grails Version (if using Grails):** 3.3.3
- **JDK Version:** OracleJDK 1.8.0_161

### Example Application

https://github.com/kefirfromperm/gorm-bug-sample

**Comment by zyro23** [comment]
looks like the problem could be that `ServiceTransformation` (`CompilePhase.SEMANTIC_ANALYSIS`) runs before `EntityASTTransformation`/`GormEntityTransformation` (`CompilePhase.CANONICALIZATION`) which inject the id property?

sample compiles for me if i define the `id` property in `Book` explicitly (i.e. `Long id`)

**Comment by kefirfromperm** [comment]
Yes if you define **id** it compiles, but this is not i want. :)
