### ISSUE TITLE
Validation and persistence of "basic collection type" is broken

### ISSUE THREAD

**Issue by donalmurtagh** [grails/grails-data-mapping#1084]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce
Run the integration tests in [this example Grails 3.3.5 app](https://github.com/donalmurtagh/gorm-bug)

### Expected Behaviour
All tests should pass

### Actual Behaviour
One tests fails.

This app contains a single domain class that maps a collection of images to an `Evidence` instance. The constraint requires each `Evidence` to have at least one image
```groovy
class Evidence {

    String customer
    static hasMany = [images: String]

    static constraints = {
        images minSize: 1
    }
}
```

This test fails because the images are not saved

```groovy
    void "save evidence"() {

        when:
        def evidence = new Evidence(customer: 'foo')

        evidence.addToImages('first')
        evidence.addToImages('second')
        Evidence savedEvidence = evidence.save(failOnError: true)

        then:
        Evidence.count == old(Evidence.count) + 1
        savedEvidence.refresh().images.size() == 2 // FAIL because 0 != 2
    }
```
### Environment Information

- Mac OS X
- 6.1.9.RELEASE
- 3.3.5
- 1.8.0_66

### Example Application
https://github.com/donalmurtagh/gorm-bug

**Comment by puneetbehl** [comment]
Please call `evidence.save(flush: true)`

**Comment by donalmurtagh** [comment]
@puneetbehl have you tested whether this actually resolves this issue? I suspect I would have tried this, and presumably it didn't work

**Comment by puneetbehl** [comment]
Yes, it works with `flush: true`. And, I tested with the sample application shared by you.
