### ISSUE TITLE
ConstrainedProperty.getPropertyType returns Object for to-one associations (6.1.10)

### ISSUE THREAD

**Issue by longwa** [grails/grails-data-mapping#1104]
A recent change in 6.1.10.BUILD-SNAPSHOT in the `gorm-hibernate5` project uncommented this line in `GrailsDomainBinder`:

```
protected void handleLazyProxy(PersistentEntity domainClass, PersistentProperty grailsProperty) {
    HibernateUtils.handleLazyProxy(domainClass, grailsProperty);
}
```

This was to fix issue #1072. Presumably this line was commented out by mistake some time ago.

However, this has an unintended side-effect. As part of the proxy handling for entities, the `setter` and `getter` methods are wrapped to provide better proxy support.

When the `ConstrainedPropertyBuilder` initializes the constrained properties, it uses:

`Class<?> propertyType = classPropertyFetcher.getPropertyType(property);`

The ClassPropertyFetcher uses the `metaProperty.getType` which returns 'Object' instead of the actual type of the property.

### Steps to Reproduce

1. Create a class such as Author with a to-one assocation to Publisher
2. Get the constraints for the Author persistent entity

### Expected Behaviour

The ConstrainedProperty for a to-one association such as the `publisher` in the example provided should have a propertyType of Publisher.

### Actual Behaviour

The ConstrainedProperty.propertyType is Object since the proxy causes the getter/setter to be wrapped with a generic Closure.

GORM 6.1.10.BUILD-SNAPSHOT

### Example Application

https://github.com/longwa/grails-issue-constrainedPropertyType

**Comment by longwa** [comment]
This is the commit that ultimately caused the behavior change:
https://github.com/grails/gorm-hibernate5/commit/5c4e6ede3752d0eb84c89b82c8dd729410c4aaeb

Since 5/5/2017, we haven't been doing the auto-unwrap for proxies when the getters are called and, IMHO, I don't think we should be doing it anyway. It sort of defeats the purpose of having proxies anyway and rarely causes issues since Grails tends to handle setup of sessions automatically anyway.

For example, prior to this change (in 6.1.9) calling:
`author.publisher.id` doesn't actually hit the database since `author.publisher` doesn't do the auto-unwrap logic.

However, with this change in 6.1.10, just calling `author.publisher` without even accessing the publisher attributes will unwrap. I guess that's by-design to avoid "proxy hell".

A better solution might be to have a mapping attribute like `autoUnwrapProxy false` that can disable this behavior on a per-entity basis.

**Comment by graemerocher** [comment]
you can get the id without unwrapping the proxy by doing `author.publisherId`

**Comment by longwa** [comment]
Yeah, but that doesn’t work in normal unit tests which is frustrating. We are still trying to make use of HibernateSpec so that’s probably the best workaround. Jeff is looking to refactor that to fit into the new trait style so we will see how that works out. 

I was mostly just pointing out that it wasn’t unwrapping for almost a year and no one noticed too much, lol. 

Thanks for the feedback.

**Comment by longwa** [comment]
I found a scenario where this fix still doesn't work. In some cases, if the field is in an abstract base class and you are building constraints for the subclass, the `field` reference on the `MetaBeanProperty` is still null so we are still getting `Object` for the type.

I think the best approach is to use the `mappingContext` initially to get the type from the `PersistentEntity` and then fallback to the `ClassPropertyFetcher` if that can't resolve the type. That would make it more immune to any metaClass wizardry done by GORM on the entities.

I'll submit another PR with this change, it doesn't break any tests and fixes some additional issues in our project.

**Comment by longwa** [comment]
So basically, I just added a helper method to resolve the type:
```
    protected Class<?> determinePropertyType(String propertyName) {
        Class<?> propertyType = null;

        // First try to use the persistent entity mappings
        PersistentEntity persistentEntity = mappingContext.getPersistentEntity(targetClass.getName());
        if (persistentEntity != null) {
            PersistentProperty persistentProperty = persistentEntity.getPropertyByName(propertyName);
            if (persistentProperty != null) {
                propertyType = persistentProperty.getType();
            }
        }
        // Fall back to just using the meta properties
        if (propertyType == null) {
            propertyType = classPropertyFetcher.getPropertyType(propertyName);
        }

        return propertyType;
    }
```

**Comment by jameskleeh** [comment]
@longwa That is what I was suggesting you to do in slack

**Comment by longwa** [comment]
@jameskleeh Fair enough, maybe I misunderstood you. At any rate this seems to handle both cases so now I'm not sure if the ClassPropertyFetcher changes should be reverted or if they are safe to leave.

**Comment by puneetbehl** [comment]
It seems like this change in `ClassPropertyFetcher` is causing a failing build in gorm-hibernate5 with `NullPointerException`. I will check if that can be resolved otherwise I am thinking to revert the changes in `ClassPropertyFetcher` as using `mappingContext` to get the `type` sounds best solution to me.

**Comment by longwa** [comment]
@puneetbehl Agreed. The changes in CPF are no longer needed as the mappingContext should resolve the issue in all cases. I think we should still leave the fallback to using the original CPF code just in case the PersistentEntity or property cannot be found.
