### ISSUE TITLE
Embedded types are being wrapped in proxy handling closures (6.1.10)

### ISSUE THREAD

**Issue by longwa** [grails/grails-data-mapping#1112]
Related to #1104, the changes in 6.1.10 to start wrapping to-one associations in proxy handling logic (related to commit grails/gorm-hibernate5@5c4e6ed) are also causing Embedded types to be wrapped in proxy handling. This is because the Embedded type extends ToOne and the proxy logic just checks if `instanceof ToOne`.

This causes the data binding to fail when using a `StructuredBindingEditor` since the object's type in from `metaProperty.type` is `Object` instead of the actual type (same root cause as #1104).

In this case, this fix is probably to change the check in `GrailsDomainBinder` to exclude `Embedded` types from the isToOne check. I don't believe the embedded types are proxied by Hibernate by default anyway so there's really nothing for the getter/setter wrappers to do in that case.

### Steps to Reproduce

1. Register a structured binding editor for an embedded type
2. Try to bind to a domain object that uses that type

### Expected Behaviour

Structured properties bind correctly using the registered binding editor

### Actual Behaviour

The binding editor is not used since the metaProperty for the embedded type is `Object`

### Environment Information

- **GORM Version: 6.1.10.BUILD-SNAPSHOT

**Comment by ilopmar** [comment]
@longwa Can you please share a project that reproduces the issue?

**Comment by longwa** [comment]
Probably but it’s easy to see why it’s happening. I’ll submit a PR with some test cases in grails-data-mapping project to fix it shortly.

**Comment by ilopmar** [comment]
I just started to taking a look at this, so I wanted a sample project to reproduce it. If you are going to submit a PR it's awesome! :)

**Comment by longwa** [comment]
The changes for this are actually in two places. In this project the `AbstractGrailsDomainBinder` needs to be changed. However, it looks like for `gorm-hibernate5`, most of the code is copied into the `GrailsDomainBinder` (the hibernate5 version doesn't extend `AbstractGrailsDomainBinder`, only the hibernate4 version, I assume this is by-design).

A fix also needs to be made in the gorm-hibernate5 project (basically the exact same change).

**Comment by longwa** [comment]
Sample project to verify the problem. In 6.1.9, these tests will pass since the proxy wrapping logic was globally disabled (due to a bug). In 6.1.10, the tests will fail and the embedded property will be wrapped in a closure causing the MetaBeanProperty getters and setters to be ClosureMetaMethods

https://github.com/longwa/grails-issue-embeddedProxy
