### ISSUE TITLE
Interface projection with ID or version fails to compile

### ISSUE THREAD

**Issue by vmj** [grails/grails-data-mapping#1119]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Try to compile the following code:

```groovy
import grails.gorm.services.Service
import grails.gorm.annotation.Entity
import org.grails.datastore.gorm.GormEntity

@Entity
class Bottle implements GormEntity<Bottle> {
    String color
}

interface BottleRef {
    Long getId()
    Long getVersion()
}

@Service(Bottle)
interface BottleService {
    List<BottleRef> findByColor(String color)
}
```

### Expected Behaviour

I would expect that the code compiles.

### Actual Behaviour

The following compilation error occurs:

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script1529969280324530580667.groovy: -1: Can't have an abstract method in a non-abstract class. The class '$BottleServiceImplementation$BottleRef' must be declared abstract or the method 'java.lang.Long getVersion()' must be implemented.
 @ line -1, column -1.
script1529969280324530580667.groovy: -1: Can't have an abstract method in a non-abstract class. The class '$BottleServiceImplementation$BottleRef' must be declared abstract or the method 'java.lang.Long getId()' must be implemented.
 @ line -1, column -1.
2 errors
```

### Environment Information

- **Operating System**: Any, but mine is macOS 10.13.5
- **GORM Version:** 6.1.x (git checkout)
- **Grails Version (if using Grails):** not grails related
- **JDK Version:**
```
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (Zulu 8.30.0.1-macosx) (build 1.8.0_172-b01)
OpenJDK 64-Bit Server VM (Zulu 8.30.0.1-macosx) (build 25.172-b01, mixed mode)
```

### Example Application

git clone of 6.1.x branch with failing tests added: https://github.com/grails/grails-data-mapping/compare/6.1.x...vmj:interface-projection-with-id-and-version?expand=1

If this is indeed a bug, I can try to come up with a patch.

**Comment by puneetbehl** [comment]
Yes, I would expect it to throw compile error because `GormEntityTransformation` which defines `Id` and `Version` has phase `CompilePhase.CANONICALIZATION` and `ServiceTransformation` has  phase `CompilePhase.SEMANTIC_ANALYSIS`.

As a workaround, you can define property `id` and `version` in the domain class.
