### ISSUE TITLE
One to many association with belongsTo doesn't delete the child records

### ISSUE THREAD

**Issue by mamun217** [grails/grails-data-mapping#1121]
### Steps to Reproduce

**Domain classes**
```groovy
package test

class Book {
    String name

    static hasMany = [authors: Author]
}
```

```groovy
package test

class Author {
    String name
    String email

    static belongsTo = [book: Book]
}
```

**Test**
```groovy
package test

import spock.lang.Specification
import grails.testing.gorm.DomainUnitTest

class BelongsToSpec extends Specification implements DomainUnitTest<Book> {

    def "deletion of an one to many association works correctly"() {
        when:
        Book book = new Book(name: "abc")
                .addToAuthors(new Author(name: "Author A", email: "author.a@email.com"))
                .addToAuthors(new Author(name: "Author B", email: "author.b@email.com"))
        book.save(flush: true)

        then:
        Book.count == 1
        Author.count == 2

        when:
        currentSession.clear()
        book = Book.findByName("abc")
        book.delete()

        then:
        Book.count == 0
        Author.count == 0 // This line fails since Author.count returns 2
    }
}

```

### Expected Behaviour

Trying to create an one to many association with `hasMany` and `belongsTo`. 
When saving a book with two authors, both Book and Author count are as expected. After deletion of the book, I was expecting both Book and Author count to be 0.
Source is as given above.

### Actual Behaviour

After deletion of the Book, `Author.count` still returns 2.

### Environment Information

- **Operating System**: Windows7
- **GORM Version:** 6.1.10
- **Grails Version (if using Grails):** 3.3.6
- **JDK Version:** 1.8
- **Hibernate Version:** 5.2.10.Final

**Comment by zyro23** [comment]
looks like it works as expected using a `HibernateSpec` and `.delete(flush: true)`. so i guess this is related to the `SimpleMapDatastore`?

**Comment by mamun217** [comment]
It's working with `HibernateSpec `and `.delete(flush: true)` as you have suggested. 
So does it mean association is not expected to work when implemented `DataTest` or `DomainUnitTest`? I have to specifically create `SimpleMapDatastore`?
Could you please elaborate?

**Comment by zyro23** [comment]
`HibernateSpec` uses a `HibernateDatastore` (with a real database, usually h2 in-mem) with gorm using hibernate as persistence provider impl.
hibernate takes care of cascades.

`DataTest` and/or `DomainUnitTest` are using `SimpleMapDatastore` which is "just" a `Map`-backed in-memory data store. gorm uses that instead of hibernate.
looks like that does not support cascades (at least for this example).

so the question is if the `SimpleMapDatastore` is expected to support any cascading behavior at all. maybe someone from the dev team can answer that.

**Comment by graemerocher** [comment]
It is designed to mock the database layer and not as a integration test. The behaviour of map based implementation will not be exactly the same as what hibernate or a real implementation will do and can never be the same.

If you are testing logic that is heavily reliant on the behaviour of your persistence operations then you should use `HibernateSpec` or `MongoSpec` etc.
