### ISSUE TITLE
DirtyChecking fails for fields defined in belongsTo

### ISSUE THREAD

**Issue by snimavat** [grails/grails-data-mapping#1126]
I noticed that many of our domain classes doesnt update the record in database and no update query is being fired by hibernate. 

Looking in the decompiled code revealed that some of the fields are not marked with DirtyCheckedProperty and the dirty checking code is not weaved into setter.

I noticed that most of the time, the issue is with those associations which are in beoingsTo

So i created following test in grails-data-mapping project  ```DirtyCheckTransformationSpec``` which fails.

```
@Entity
class Parent {
    String name
}

@Entity
class Child {
    String name
    static belongsTo = [parent:Parent]
}


 void "Test dirty check with belongsTo"() {
        when:
        Child child = new Child()
        child.trackChanges()

        then:
        !child.hasChanged()
        !child.hasChanged("parent")

        when:
        child.name = "test"

        then:
        child.hasChanged()
        child.hasChanged("name")

        when:
        child.parent = new Parent()

        then:
        child.hasChanged()
        child.hasChanged("name")
        child.hasChanged("parent")
    }

```

the assertion fails on line   ```child.hasChanged("parent")```

Gorm version 6.1.x, Grails 3.3.2

**Comment by snimavat** [comment]
Looks like the issue is, the setters/field for associations defined in belongsTo doesnt exist when DirtyCheckingTransformer runs.

[final propertyNodes = classNode.getProperties() ](https://github.com/grails/grails-data-mapping/blob/d11d32ee84f5d777c59cceb322b84d82efb97a18/grails-datastore-gorm/src/main/groovy/org/grails/compiler/gorm/DirtyCheckingTransformer.groovy#L108)

does not return property nodes for those associations defined in belongsTo

**Comment by graemerocher** [comment]
Most probably because the other class was already compiled

**Comment by snimavat** [comment]
@graemerocher both classses are in same project. What is the solution here.

**Comment by snimavat** [comment]
@graemerocher Do you think this is a valid issue, can there be any fix.. or any temporary workaround.

**Comment by graemerocher** [comment]
Seems like a valid issue, but I'm not sure what can me done about it. This would normally occur only if one class is compiled after the other instead of both classes being compiled together

**Comment by snimavat** [comment]
Ok, i see... In our project, both of the domains are in same project, nothing special about the domains, almost a regular grails project. And still, when i see at decompiled code, i see, a considerable amount of domains has this exact issue.

**Comment by graemerocher** [comment]
Provide an example that reproduces the issue can we can take a look

**Comment by snimavat** [comment]
@graemerocher the test above is not good enough ?

**Comment by snimavat** [comment]
@graemerocher Verified and seem to be working good in 6.1.11.BUILD-SNAPSHOT thanks
