### ISSUE TITLE
Search by discriminator column stop working in grails 3.3, gorm 6.1

### ISSUE THREAD

**Issue by demon101** [grails/grails-data-mapping#1129]
We have hierarchy of two classes in the project. For searching only for parents instances we have used discriminator column in hql. Now it fails.

```
class ApplicationProperty {
    ....

    static mapping = {
        discriminator column: 'class_type'
    }

static findProperty(PropertyType type, boolean require=false) {
        def prop = find('from ApplicationProperty ap where ap.name = :type and ap.class_type = :cl',[type: type, cl: ApplicationProperty.class.name]) // this line
       ...
    }
}

class ChildProperty extends ApplicationProperty {
....
}
```

It works in grails 3.2.11 and in grails 3.3 it stops working and throwing an error with the message: 

> could not resolve property: class_type of: com.xxx.system.ApplicationProperty [from com.xxx.system.ApplicationProperty ap where ap.name = :type and ap.class_type = :cl]; nested exception is org.hibernate.QueryException: could not resolve property: class_type of: com.xxx.system.ApplicationProperty [from com.xxx.system.ApplicationProperty ap where ap.name = :type and ap.class_type = :cl]
> Caused by
> could not resolve property: class_type of: com.xxx.system.ApplicationProperty

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Actual Behaviour

Tell us what happens instead

### Environment Information

- **Operating System**: TODO
- **GORM Version:** 6.1.10.RELEASE
- **Grails Version (if using Grails):** 3.3.6
- **JDK Version:** 8

In gorm documentation I didn't find any words about deprecation of the feature.

**Comment by demon101** [comment]
discriminator column in unique constraint also not working now
`name unique: 'class_type'`

**Comment by demon101** [comment]
[testD.zip](https://github.com/grails/grails-data-mapping/files/2253599/testD.zip)
On new app, domain with constraint on discriminator column fails during startup with NPE. I have commented line. 
could not resolve property exception reproduced.

**Comment by longwa** [comment]
This is most likely because the discriminator column is no longer a `PersistentProperty` on the entity. We had some places that broke b/c of this change.

**Comment by demon101** [comment]
Now a bug. Hql `type()` function should be used
