### ISSUE TITLE
Validateable object with beforeValidate() callback is not serializable

### ISSUE THREAD

**Issue by longwa** [grails/grails-data-mapping#1132]
Grails 3.3.6
GORM 6.1.11.BUILD-SNAPSHOT

The `BeforeValidateHelper` implements Serializable but the `eventTriggerCallerCache` has a value of `BeforeValidateEventTriggerCaller` which is NOT Serializable.

Since it's just a cache and populates on demand, perhaps the cache could be `transient` anyway.

Attempting to serialize a command object that is `Validateable` with a `beforeValidate()` callback results in:

```
Caused by: java.io.NotSerializableException: org.grails.datastore.gorm.support.BeforeValidateHelper$BeforeValidateEventTriggerCaller
        - custom writeObject data (class "java.util.concurrent.ConcurrentHashMap")
        - object (class "java.util.concurrent.ConcurrentHashMap", {class com.triu.operational.ptl.DeclareByCommand=org.grails.datastore.gorm.support.BeforeValidateHelper$BeforeValidateEventTriggerCaller@2f9034bb})
        - field (class "org.grails.datastore.gorm.support.BeforeValidateHelper", name: "eventTriggerCallerCache", type: "interface java.util.Map")
        - object (class "org.grails.datastore.gorm.support.BeforeValidateHelper", org.grails.datastore.gorm.support.BeforeValidateHelper@48a70153)
        - field (class "com.triu.operational.ptl.DeclareByCommand", name: "grails_validation_Validateable__beforeValidateHelper", type: "class org.grails.datastore.gorm.support.BeforeValidateHelper")
```

**Comment by longwa** [comment]
Just to clarify a bit more, it would only be an issue after the `BeforeValidateHelper` had been used once and had an item in the cache. So an object that hadn't been validated would serialize fine until after the `validate` method was called at least once. Then it would fail since the cache has items. That tripped me up for a sec while writing the test cases so thought I'd note it here.

**Comment by jeffbrown** [comment]
Related to https://github.com/grails/grails-core/issues/10642 and https://github.com/grails/grails-core/issues/9986.
