### ISSUE TITLE
Domain class instance properties unexpectedly marked as dirty

### ISSUE THREAD

**Issue by ilPittiz** [grails/grails-data-mapping#1135]
Given the following domain classes
```
class User implements Serializable {
	String email
	String name
	String password
	Set<Team> teams = []

	static embedded = [ 'teams' ]

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if(isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = "_$password_"	// naive encoding
	}
}
```
```
class Team {
	String id
}
```
In my web-app basically you can assign/unassign users to/from a team.

I found out an unexpected behavior when upgrading my web-app from Grails 3.2.6 to version 3.3.x: when unassigning users from one or more teams, I got their `password` updated (basically re-encoded) as marked as dirty.
```
user.teams.removeAll { it.id == teamId }
user.save()
println user.isDirty()              // -> true
println user.isDirty('password')    // -> true
```
In particular, all other `User` instance's properties are marked as dirty as well.

Converting the snippet above to
```
user.removeFromTeams(user.find { it.id == teamId })
println user.isDirty()              // -> true
println user.isDirty('password')    // -> false
user.save()
```
everything works as expected.

Though this is I guess a valid workaround, there's another case highlighting the issue: a dull instance save without changing any of its properties. In this case as well the `password` is marked as dirty and hence re-encoded.
```
user.save()
println user.isDirty()              // -> true
println user.isDirty('password')    // -> true
```

**Notes:**
- the issue occurs regardless `User` and `Teams` instances are versioned or not
- it's not specifically related to Grails 3.3, but it seems it was introduced with Grails 3.2.8

### Example Application

https://github.com/ilPittiz/GormDirtyInstance

You must have a running MongoDB instance (default port).
The app will run on http://localhost:8080/, and you can get users info (including their password) and perform all user-related actions from there:
1. reset users to default
2. add user to team
3. remove user from team (both variants)
4. dull user save

For 3 and 4, you'll also see a meaningful output displayed.

### Environment Information

- **GORM Version:** 6.1.10, breaking change between 6.0.7 and 6.0.9
- **Grails Version:** 3.3.6, breaking change between 3.2.6 and 3.2.8
- **JDK Version:** 1.8.0_171

**Comment by ChiranjibKarn** [comment]
I am also having same problem after upgrading my REST application from Grails 3.2.11 to Grails 3.3.8 and Gradle 4.9.
The password is getting marked as dirty even when there is no change/update on that field.

**Comment by graemerocher** [comment]
I believe this is because explicitly calling `save()` marks the object as dirty. This behaviour is related to https://github.com/grails/gorm-neo4j/issues/93

**Comment by ilPittiz** [comment]
Thanks! Applying the configuration `grails.gorm.markDirty: false` did the trick.
I also tested it with Grails 4.0.1 and GORM 7.0, and it works like a charm.
Closing this issue.
