### ISSUE TITLE
Autowired helpers are not injected in spite of the autowire mapping

### ISSUE THREAD

**Issue by joemccall86** [grails/grails-data-mapping#1149]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Grails 3.2.x project with default configuration
2. Create a domain class with `static mapping = { autowired true }` and an injected helper class
3. Run tests to determine if the helper instance was injected

### Expected Behaviour

An instance is injected into the domain class.

### Actual Behaviour

The instance is null and both unit and integration tests fail.

### Environment Information

- **Operating System**: Fedora 28 Workstation
- **GORM Version:** 6.1.10.RELEASE
- **Grails Version (if using Grails):** 3.2.13
- **JDK Version:** `openjdk version "1.8.0_181"`

### Example Application

- https://github.com/joemccall86/gorm-autowired-example

**Comment by graemerocher** [comment]
autowiring is globally disabled by default to in the default mapping. You need to enable it configuration

**Comment by joemccall86** [comment]
Perhaps I misunderstand. If I enable that globally then there's no use for `static mapping = { autowire true }` on the domain class. I'm attempting to follow the syntax outlined in the docs [here](http://gorm.grails.org/6.1.x/hibernate/manual/#_domain_autowiring_disabled_by_default).

If it's enabled globally, why is there a need for the mapping?

**Comment by graemerocher** [comment]
Actually you are right, however, the issue here appears to be more in `@TestFor`. Please report to https://github.com/grails/grails-testing-support/

**Comment by joemccall86** [comment]
This should not be closed, since the test also fails in the integration test, and when replicated in BootStrap.groovy.

**Comment by graemerocher** [comment]
Possibly related to https://github.com/grails/grails-core/issues/11005

**Comment by graemerocher** [comment]
The setting `grails.gorm.autowire` is set to false in `application.yml` in your config. Setting it to `true` resolves the issue

**Comment by joemccall86** [comment]
I'm still not sure I understand. Setting it to `true` would enable autowiring in all gorm objects, eliminating the need for `static mapping = { autowire true }`. Am I missing something?

**Comment by graemerocher** [comment]
With the current implementation that is a requirement it seems. Probably it should not be that way, but since auto wiring entities is deprecated and scheduled to be completely removed in the next major version of GORM I don't see us fixing the behaviour. My suggestion would be to move your logic to event listeners.
