### ISSUE TITLE
Empty list as parameter for dynamic finder with inList fails to SQLGrammarException with MySQL

### ISSUE THREAD

**Issue by smakela** [grails/grails-data-mapping#1160]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create dynamic finder query for any Domain object and use empty list as parameter for example
Foo.findAllByCodeInList([])

### Expected Behaviour

Should return empty list like GORM implementation in Grails 2.x
In my opinion this should not even go to hibernate because this could be handled in GORM

### Actual Behaviour

You get org.hibernate.exception.SQLGrammarException

### Environment Information

- **Operating System**: OSX 10.13.5
- **GORM Version:** 6.1.10.RELEASE
- **Grails Version (if using Grails):** 3.3.8
- **JDK Version:** 1.8.0_72-b15
- **MySQL Version:** 5.6.27
- **MySQL Driver Version:** 5.1.47

### Example Application

- https://github.com/smakela/emptyinlist/

**Comment by jameskleeh** [comment]
I don't think GORM should make that decision to not send the query to hibernate. This is valid in other databases like H2.

**Comment by smakela** [comment]
@jameskleeh You don't think? Please give me some explanation why GORM should send the query to Hibernate when you KNOW that result should be empty list? I don't understand why you delegate stuff to other system what you could do it earlier.

**Comment by jeffbrown** [comment]
> Please give me some explanation why GORM should send the query to Hibernate when you KNOW that result should be empty list?

One argument against doing it is that in order to do so GORM has to interrogate the value of the list any time `InList` is used, which would be an unwanted penalty for most use cases.

**Comment by jeffbrown** [comment]
An option that makes sense for a lot of apps is don't involve GORM at all when your `List` is empty.

```groovy
def someList = // ...

if(someList) {
    // query
} else {
    // don't query
}
```

**Comment by jeffbrown** [comment]
Another consideration is if GORM were going to short circuit when the `List` is empty we need to be careful about how that works when `InList` is used along with other criteria by way of `Or` or `And`.

**Comment by jameskleeh** [comment]
@smakela Because there are too many variables and use cases to consider implementing this sort of behavior

**Comment by smakela** [comment]
Ok. Fair enough.

It would be still nice to have these breaking changes documented, because in Grails 2 GORM returns empty list.

>

> > Please give me some explanation why GORM should send the query to Hibernate when you KNOW that result should be empty list?
> 
> One argument against doing it is that in order to do so GORM has to interrogate the value of the list any time `InList` is used, which would be an unwanted penalty for most use cases.

Same time goes if you check the value or I check the value (cause otherwise I get exception), right?

**Comment by jameskleeh** [comment]
@smakela I'm not aware of anything on the GORM side that caused this to change. This is likely a change in Hibernate causing the difference.

**Comment by smakela** [comment]
> @smakela I'm not aware of anything on the GORM side that caused this to change. This is likely a change in Hibernate causing the difference.

Ok. But it must be the hibernate then. Thanks again from your answers! Sorry I don't accept always the first answer :)
