### ISSUE TITLE
Unique constraint is not checked across 2 child classes when constraints are defined in an abstract parent class

### ISSUE THREAD

**Issue by joemccall86** [grails/grails-data-mapping#1162]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an abstract GORM class with a unique constraint on a field (e.g., "name")
2. Create 2 child GORM classes
3. Instantiate one instance of each child GORM class with the same name

### Expected Behaviour

The unique constraint invalidates one of the instances

### Actual Behaviour

The unique constraint is not checked (potentially leading to it being caught as a runtime error when inserted into the database).

### Environment Information

- **Operating System**: Fedora 28 Workstation
- **GORM Version:** 6.1.10.RELEASE
- **Grails Version (if using Grails):** 3.3.8
- **JDK Version:** OpenJDK Runtime Environment (build 1.8.0_181-b15)

### Example Application

https://github.com/joemccall86/grails-unique-constraint

It is an integration test since unique constraints weren't checked properly in Grails 3.2.x using a simple datastore. The initial import (first commit) is Grails 3.2.x, and the second commit upgrades the app to Grails 3.3.x.

### Notes

This behavior worked in Grails 3.2.x. In Grails 3.2.13 (both with GORM 6.0.x and 6.1.x) the unique constraint was checked in `org.grails.orm.hibernate.validation.UniqueConstraint`. In Grails 3.3.8 it's now checked in `org.grails.datastore.gorm.validation.constraints.builtin.UniqueConstraint`. The regression likely lies in there.

**Comment by joemccall86** [comment]
It looks like https://github.com/grails/grails-data-mapping/blob/c4c4073bcad3198ed974e52646e3ae091d920d29/grails-datastore-gorm-support/src/main/groovy/org/grails/orm/hibernate/validation/UniqueConstraint.java#L160 is the functionality that needs to be ported over to the new constraint.

**Comment by graemerocher** [comment]
Thanks for the PR
