### ISSUE TITLE
Groovy 2.5.5 issue with Ordered trait

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-data-mapping#1211]
We used to have a trait named `Ordered`: 

```groovy
package org.grails.datastore.mapping.core

import groovy.transform.CompileStatic

@CompileStatic
trait Ordered {
    int order = 0
}
```

This trait is implemented by many classes. Upgrading to 2.5.5 causes issues.

### Steps to Reproduce

1. Clone branch https://github.com/grails/grails-data-mapping/tree/groovy-2.5.5-issue
2. `./gradlew grails-datastore-gorm:compileGroovy --stacktrace`
3. TODO

### Expected Behaviour

Compilation should work.

### Actual Behaviour

It tells to implement getter and setter in `TransactionalTransform` and `TenantTransform`.

```
/Users/sdelamo/Developer/grails/grails-data-mapping/grails-datastore-gorm/build/tmp/compileGroovy/groovy-java-stubs/org/grails/datastore/gorm/transactions/transform/TransactionalTransform.java:15: error: TransactionalTransform is not abstract and does not override abstract method setOrder(int) in Ordered
@groovy.transform.CompileStatic() @org.codehaus.groovy.transform.GroovyASTTransformation(phase=org.codehaus.groovy.control.CompilePhase.CANONICALIZATION) public class TransactionalTransform
                                                                                                                                                                 ^
/Users/sdelamo/Developer/grails/grails-data-mapping/grails-datastore-gorm/build/tmp/compileGroovy/groovy-java-stubs/org/grails/datastore/gorm/multitenancy/transform/TenantTransform.java:18: error: TenantTransform is not abstract and does not override abstract method setOrder(int) in Ordered
@groovy.transform.CompileStatic() @org.codehaus.groovy.transform.GroovyASTTransformation(phase=org.codehaus.groovy.control.CompilePhase.CANONICALIZATION) public class TenantTransform
```
### Environment Information

- **Operating System**: macOS Mojave
- **GORM Version:** 7.0.0.BUILD-SNAPSHOT
- **Grails Version (if using Grails):** 4.0.0.BUILD-SNAPSHOT
- **JDK Version:** 1.8.0_191

**Comment by aaloise** [comment]
Maybe it's something beyond that. This simple code works:

import groovy.transform.CompileStatic

```
@CompileStatic
trait Ordered {
    int order = 0
}

@CompileStatic
class GroovyXImpl implements Ordered { }

println new GroovyXImpl().getOrder()
```

No compilation error and prints 0 normally.

**Comment by puneetbehl** [comment]
Closed with https://github.com/grails/grails-data-mapping/commit/b8c88de72599872a807a7f6621854b778d4c7791
