### ISSUE TITLE
Properties are not dirty-checked properly when Comparable is implemented

### ISSUE THREAD

**Issue by joemccall86** [grails/grails-data-mapping#1231]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Define a GORM class `Person` and `BlogPost`, where `Person` has a field `BlogPost lastViewedPost`
2. Implement a natural order on `BlogPost` by implementing `Comparable<BlogPost>`. In this case I used `@Sortable(includes = ['title'])` to indicate I want all the posts to be sorted by title.
3. Create two blog posts with the same title
4. Set the `lastViewedPost` on a `Person` instance to one, then the other blog post using the API generated by the `@Resource` annotation.

### Expected Behaviour

The `lastViewedPost` value is updated to the new value.

### Actual Behaviour

The `lastViewedPost` value remains at the old value.

### Environment Information

- **Operating System**: Fedora 29 Workstation
- **GORM Version:** 6.1.11.RELEASE (does not appear in GORM 6.0.12.RELEASE)
- **Grails Version (if using Grails):** 3.3.9
- **JDK Version:** openjdk version "1.8.0_201"

### Example Application

- https://github.com/joemccall86/data-binding-custom

See specifically https://github.com/joemccall86/data-binding-custom/blob/master/src/integration-test/groovy/BlogPostApiSpec.groovy

### Further discussion

This is because `DirtyCheckable` uses Groovy `==` operator to determine equality to decide if an entity is dirty or not. Groovy `==` will always call `a.compareTo(b) == 0` if it implements Comparable, even if a custom `equals` method is defined.

Regardless, I think it's worth at the very least discussing if the `==` operator should be used in `DirtyCheckable` since I would imagine defining a natural sort order via implementing Comparable is a common pattern. Perhaps it would be useful to use `.equals()` in `DirtyCheckable` instead. I'm putting together a PR to demonstrate this.

**Comment by demon101** [comment]
@jameskleeh   I believe the issue can be closed
