### ISSUE TITLE
default sort on Integers on GORM 7.0.0 break list call

### ISSUE THREAD

**Issue by Taack** [grails/grails-data-mapping#1240]
Using postgres, on domain classes declaring default sort on an Integer field, list call fails.

The error message is:

> 2019-04-22 10:34:39.796 ERROR --- [nio-9442-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: function upper(integer) does not exist
>   Indice : No function matches the given name and argument types. You might need to add explicit type casts.
>   Position : 455
>  

The generated SQL query is wrong, it contains  

> order by upper(menuentry0_.position) asc

### Expected Behaviour

Sort objects as in Grails 3.3.9.

### Actual Behaviour

An exception is thrown.

### Environment Information

- **Operating System**: Linux Mageia 7-beta3
- **GORM Version:** 7.0.0.RC1
- **Grails Version (if using Grails):** 4.0.0.RC1
- **JDK Version:** openjdk full version "1.8.0_212-b03"

### Example Application

- I can join a sample app if needed.

**Comment by Taack** [comment]
[t400RC1.tar.gz](https://github.com/grails/grails-data-mapping/files/3102869/t400RC1.tar.gz)

It is specific to postgres, I might made a mistake configuring Postgres dialect...

Here is a test-case:
`$ createdb -U postgres test-sort`
`$ ./gradlew bootrun`
Click on http://localhost:8080/testSort/index

**Comment by Taack** [comment]
Almost the same problem than in this bug report:
https://github.com/grails/gorm-hibernate5/issues/134

**Comment by jameskleeh** [comment]
Duplicate
