### ISSUE TITLE
resolveTenantIdentifier is being called twice for every request 

### ISSUE THREAD

**Issue by sreedharrao225** [grails/grails-data-mapping#1259]
I see resolveTenantIdentifier is being called twice immedielty one after the other which made to look into the src and figured out that it might be unnecessary which might impact the performance .

In below code i see resolveTenantIdentifier is being called once before logger and later again in Tenants.groovy file 

TenantResolver tenantResolver = multiTenantCapableDatastore.getTenantResolver()
            Serializable tenantIdentifier = tenantResolver.resolveTenantIdentifier()
            log.debug "Resolved tenant id [$tenantIdentifier] from resolver [${tenantResolver.getClass().simpleName}]"
            return multiTenantCapableDatastore.getTenantResolver().resolveTenantIdentifier()

I have made pulled request (https://github.com/grails/grails-data-mapping/pull/1258) to fix this if it make sense .Please comment and let me know.

**Comment by abhaygoel** [comment]
It gets called 8 times for me. Please advice.

**Comment by jeffbrown** [comment]
> It gets called 8 times for me. Please advice.

@abhaygoel Are you saying that the code shown in the original report causes `resolveTenantIdentifier` to be invoked 8 times?

**Comment by jeffbrown** [comment]
Apologies.  I just re-read.  Sorry for the noise.
