### ISSUE TITLE
Unique constraint no longer properly checks parent field

### ISSUE THREAD

**Issue by joemccall86** [grails/grails-data-mapping#1263]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Define a parent class `Organization`
2. Define child class `Channel` with a `String name` that `belongsTo = [organization: Organization]`
3. Add `hasMany = [channels: Channel]` to `Organization`
4. Add `static constraints = { name unique: 'organization' }` to `Channel`
5. Attempt to test said constraint inside an isolated transaction.

### Expected Behaviour

Validation fails with a unique constraint violation.

### Actual Behaviour

Validation passes.

### Environment Information

- **Operating System**: Fedora 30 Workstation
- **GORM Version:** 7.0.2
- **Grails Version (if using Grails):** 4.0.0
- **JDK Version:** 
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

### Example Application

https://github.com/joemccall86/uniqui-group-constraint-test

### Notes
There are two integration tests, one that has a finder that only looks for the requested `Channel` based on the name, the other that uses both the name and the organization. When the organization is present in the finder the unique constraint works fine. When it is missing the unique constraint fails.

This behavior worked properly in GORM 6.1.12.

**Comment by joemccall86** [comment]
Is there any additional information I can provide to help address this issue?

**Comment by graemerocher** [comment]
No there is enough info thanks, we will look at prioritizing it for the next 7.0.x release
