### ISSUE TITLE
minSize does not work when String is blank

### ISSUE THREAD

**Issue by chris13524** [grails/grails-data-mapping#1275]
When using the constraint `minSize` on a String property, it passes validation if the String is blank.

I believe this is also an issue with the `size` constraint.

### Steps to Reproduce

1. Disable converting empty Strings to null by adding this to `grails-app/conf/application.yml`:
    ```
   grails:
     databinding:
       convertEmptyStringsToNull: false
    ```
2. Create a controller and command object that makes use of the `minSize` constraint:
    ```
    class TestController {
      def index(TestCommand cmd) {
        if (cmd.validate()) {
          render("ok")
        } else {
          cmd.errors.allErrors.each { render(it) }
        }
      }
    }
    
    class TestCommand implements grails.validation.Validateable {
      String thing
    
      static constraints = {
        thing minSize: 5
      }
    }
    ```
3. This produces no validation errors: `curl http://localhost:8080/test -H "Content-Type: application/json" --data '{"thing":""}'`
    This does: `curl http://localhost:8080/test -H "Content-Type: application/json" --data '{"thing":"x"}'`

### Expected Behaviour

`minSize` should function on blank Strings.

### Actual Behaviour

`minSize` ignores blank Strings.

### Environment Information

- **Operating System**: Ubuntu 18.04
- **GORM Version:** 7.0.2.RELEASE
- **Grails Version (if using Grails):** 4.0.1
- **JDK Version:** 1.8.0_232

### Example Application

[minsize-test.zip](https://github.com/grails/grails-data-mapping/files/4026907/minsize-test.zip)

### Proposed fix

I believe this is the result of [this](https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-validation/src/main/groovy/org/grails/datastore/gorm/validation/constraints/AbstractConstraint.java#L98). If we override this method [like the `blank` constraint does](https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-validation/src/main/groovy/org/grails/datastore/gorm/validation/constraints/BlankConstraint.java#L57), that should fix the issue.

Either we implement a fix for this or mention it in the [documentation for `minSize`](https://docs.grails.org/latest/ref/Constraints/minSize.html).

**Comment by chris13524** [comment]
Looking closer, `blank` doesn't actually check if the length if the string length is greater than 0, it checks if it ["hasText"](https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-validation/src/main/groovy/org/grails/datastore/gorm/validation/constraints/BlankConstraint.java#L62).

So this means that there is actually no way to check that the string length is greater than 0 without using a custom validator.

**Comment by graemerocher** [comment]
This is not a bug. The `minSize` constraint has never checked for blankness. You can combine constraint definitions for this purpose and if you need custom requirements (as it appears you do) then define a custom validator.
