### ISSUE TITLE
update data service docs on multiple datasource

### ISSUE THREAD

**Issue by musketyr** [grails/grails-data-mapping#1286]
The [guide about multi-data source](https://guides.grails.org/grails-multi-datasource/guide/index.html) is properly explaining how to use custom data source with data services. None of this information is mentioned in [the official documentation](https://gorm.grails.org/latest/hibernate/manual/index.html#multipleDataSources).

**Comment by niravassar** [comment]
This is ready for a review with a PR

**Comment by musketyr** [comment]
thanks, @niravassar. the PR looks good to me!

**Comment by niravassar** [comment]
i closed and deleted PR https://github.com/grails/gorm-hibernate5/pull/212

The PR to use is https://github.com/grails/gorm-hibernate5/pull/213

**Comment by erichelgeson** [comment]
Merged, thanks!
