### ISSUE TITLE
DetachedCriteria.deleteAll() ignores criteria created via lazyWhere

### ISSUE THREAD

**Issue by douglyuckling** [grails/grails-data-mapping#1306]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a simple domain class that has at least one property, and create some data for it
2. Create an instance of `DetachedCriteria` for the domain class via `whereLazy()` and specify some reasonable criteria
3. Invoke `deleteAll()` on the criteria.

### Expected Behaviour

Only the data matching the specified criteria is deleted.

### Actual Behaviour

The specified criteria are ignored and _all_ data for the domain class is deleted.

### Environment Information

- **Operating System**: MacOS 10.14.6 (18G4032)
- **GORM Version:** 6.1.12.RELEASE and 7.0.4.RELEASE
- **Grails Version (if using Grails):** 3.3.11 and 4.0.3
- **JDK Version:** openjdk version "1.8.0_242"

### Example Application

https://github.com/douglyuckling/gorm-lazy-criteria-bug

**Comment by puneetbehl** [comment]
@douglyuckling I believe it should work when you use `Product.where { color == givenColor }.deleteAll()` instead of calling `where { }.deleteAll()`

**Comment by puneetbehl** [comment]
Nvm, I just noticed that you already mentioned it on the repo README.

**Comment by douglyuckling** [comment]
Thanks, @puneetbehl! Any chance we could get this fixed on the 6.1.x branch, too? We're not quite ready to upgrade to 7.0.x yet, and in the meantime it would be easy for someone to forget to add the workaround mentioned above.  😬

**Comment by puneetbehl** [comment]
@douglyuckling It is done.
