### ISSUE TITLE
Gorm 7.0.5 with grails 3..3.11 fails on multiple dependency issues

### ISSUE THREAD

**Issue by snimavat** [grails/grails-data-mapping#1527]
- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

**Steps to Reproduce** :
- Add grails 7.0.5 dependency to grails 3.3.11 project (gormVersion=7.0.5 in gradle.properties)
- Upgrade grails hibernate plugin in build.gradle -  `classpath "org.grails.plugins:hibernate5:7.0.5"`

Would expect the application to work with new gorm version, as per this gorm [documentation](https://gorm.grails.org/latest/hibernate/manual/index.html#gettingStarted)

Instead it fails with following errors

```
Could not resolve all dependencies for configuration ':runtime'.
   > Could not find org.grails:grails-datastore-core:7.0.5.
     Searched in the following locations:


    Required by:
         project : > org.grails:grails-core:3.3.11
         project : > org.grails:grails-plugin-rest:3.3.11 > org.grails:grails-plugin-datasource:3.3.11
         project : > org.grails:grails-plugin-rest:3.3.11 > org.grails:grails-web:3.3.11 > org.grails:grails-web-url-mappings:3.3.11
```

```
Could not find org.grails:grails-datastore-web:7.0.5.
     Searched in the following locations:

     Required by:
         project : > org.grails.plugins:hibernate5:7.0.5

   > Could not find org.grails:grails-datastore-gorm-support:7.0.5.
     Required by:
         project : > org.grails.plugins:hibernate5:7.0.5
```

- **Operating System**: OSX
- **GORM Version:** 7.0.5
- **Grails Version (if using Grails):** 3.3.11
- **JDK Version:** JDK8

**Comment by puneetbehl** [comment]
Grails 3 does not work with GORM 7, please update to Grails 4.
