### ISSUE TITLE
Ugrade Groovy version to 4+

### ISSUE THREAD

**Issue by injecteer** [grails/grails-data-mapping#1753]
Groovy 4 has been released 2 years ago and is already in use by many libraries and frameworks out there.

GORM because of it's Groovy 3.0.11 can not be used in actual version of e.g. Micronaut 4.0 as a data-layer.

**Comment by ibmsoft** [comment]
+1

**Comment by puneetbehl** [comment]
Thank you for reporting it. We are already working towards Grails 7 which will support Apache Groovy 4.

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-data-mapping/pull/1810

**Comment by jamesfredley** [comment]
The 9.0.0-SNAPSHOT is based on Groovy 4.0.22 and the Grails 7.0.0 release will be fully based on Groovy 4.0.22.
