### ISSUE TITLE
GPMONGODB-366: Cannot persist embedded object id

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-data-mapping#347]
Original Reporter: sagrawal14
Environment: Grails 2.3.5, JDK 1.7.0_21, Ubuntu 13.10, No hibernate
Version: 3.0.1
Migrated From: http://jira.grails.org/browse/GPMONGODB-366

I'm having some problem using mongo db plugins. I'm listing out key problems below & described further:

1. Problem persisting id named attribute in a embedded class,
2. No rendering set of embedded object using default marshaller,
3. Data rollback problem with integration test.

I had a domain class named *User*, which have a list of embedded class named *EmbeddedUser* stored as members.

{code:title=User.groovy|borderStyle=solid}
package com.test

class User {

    static constraints = {
    }

    static embedded = ["members"]

    //static hasMany = [members: EmbeddedUser]

    String email
    String fullName

    Set<EmbeddedUser> members = []

    EmbeddedUser getEmbeddedInstance() {
        return new EmbeddedUser([id: id, fullName: fullName])
    }
}
{code}

{code:title=EmbeddedUser.groovy|borderStyle=solid}
package com.test

class EmbeddedUser {

    Long id

    String fullName

    @Override
    int hashCode() {
        // Implemented in attachment
    }

    @Override
    boolean equals(Object obj) {
        // Implemented in attachment
    }
}
{code}

When I add any embedded user instance to any user instance, it only persists the *fullName*, *id* is not persisted in mongodb. This states my first problem. I don't know if this is by implementation or bug.

Steps to reproduce:

1. Install mongodb( if not installed),
2. Create database: *use mongoEmbed*,
3. Add user to it: *db.addUser("sa", "sa")*
4. Download attachment & un-tar it,
5. Just do *grails run-app*,
6. Check user document in mongodb: *db.user.find()*

You can see, only *fullName* is persisted to database for second user. However if I rename *id* field to something else, it works fine.

Second problem is that, when I render any user instance, using respond method, its members are not being rendered.

Steps to Reproduce:

1. Do *grails run-app*
2. Go to http://localhost:8080/mongo-embed/user

You'll see that no members object is rendered. However if I mark *members* as **hasMany** relationship, it works fine.

I'm not sure about third problem but according to integration test doc, all data is automatically rollback after finishing test case. Is it not true with mongo database.

Steps to reproduce:

1. Delete all existing records: **db.user.remove()**,
2. Run: **grails test-app UserService**

**Comment by jakecoffman** [comment]
+1

**Comment by jakecoffman** [comment]
Why did you go through and close all these mongo plugin bugs? I am experiencing this issue and #414 in my app and I was hoping for an eventual resolution.

**Comment by graemerocher** [comment]
@jakecoffman The MongoDB plugin has been rewritten from the ground up ontop of the CodecRegistry concept in the MongoDB 3.x driver. So the majority of these bugs no longer apply to the new version of the plugin that will be released soon.

**Comment by SAgrawal14** [comment]
:+1:
