### ISSUE TITLE
mongodb - BigDecimal gets persisted as String

### ISSUE THREAD

**Issue by zyro23** [grails/grails-data-mapping#534]
conversion takes place here: https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-mongodb/src/main/groovy/org/grails/datastore/mapping/mongo/engine/MongoEntityPersister.java#L537

is this behavior intentional? would converting it to `Double` (being a mongo native type) make more sense? if so, i guess the same applies to `Float`..

fwiw, `NumberToNumberConverterFactory` is already registered by default with `DefaultConversionService`.

thanks, zyro

**Comment by graemerocher** [comment]
By design. See https://groups.google.com/forum/#!topic/mongodb-user/Mi8RN4wh_BU
