### ISSUE TITLE
Configuration documentation deviates from implementation

### ISSUE THREAD

**Issue by miffels** [grails/grails-data-mapping#535]
Hi all,

Would you like to fix the [MongoDB docs](http://grails.github.io/grails-data-mapping/mongodb/manual/guide/2.%20Getting%20Started.html), please, where it says that the MongoDB settings would reside under the ``grails.mongo`` key? [The source code reveals](https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-mongodb/src/main/groovy/grails/mongodb/bootstrap/MongoDbDataStoreSpringInitializer.groovy#L39-48) that it should much rather be ``grails.mongodb``, and it took me hours to figure out why the heck GORM would ignore my settings ;)

Cheers,
Michael

**Comment by graemerocher** [comment]
pull requests welcome
