### ISSUE TITLE
GRAILS-11801 RestBuilder destroys custom response renderers

### ISSUE THREAD

**Issue by tcrossland** [grails/grails-data-mapping#536]
See https://jira.grails.org/browse/GRAILS-11801, https://github.com/grails-plugins/grails-rest-client-builder/issues/34

**Comment by jeffbrown** [comment]
Is this related to grails-data-mapping?

**Comment by tcrossland** [comment]
The class causing the issue (grails.plugins.rest.client.RestBuilder) is in this repository.

**Comment by tcrossland** [comment]
The problem is caused by using the RestBuilder constructor, custom configuration will then be overridden:

https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-rest-client/src/main/groovy/grails/plugins/rest/client/RestBuilder.groovy#L99
