### ISSUE TITLE
3.0.2 grails.databinding.dateFormats does not affect binding at all

### ISSUE THREAD

**Issue by kpaxton** [grails/grails-data-mapping#540]
When trying to create new Domain objects from JSON or a Map date formats get rejected if in the JSON standard format 'yyyy-MM-dd'T'HH:mm:ss'Z'. I've put a config setting grails.databinding.dateFormats to declare the format properly but it changes nothing. The only way that I can get it to work is using the @BindingFormat attribute, however that then makes the field required. 

Is the config setting different for this plugin or is this a bug?

**Comment by jeffbrown** [comment]
> 3.0.2 grails.databinding.dateFormats does not affect binding at all

I can't reproduce that.  My testing suggests that the property is being respected.

If I have something like this in `application.yml`

    ---
    grails:
        databinding:
            dateFormats:
                -  "yyyy-MM-dd'T'HH:mm:ssZ"

Then a date string like `2013-09-29T18:46:19-0700` does bind correctly.

Can you create a simple sample app which demonstrates the problem, push that to a public repo here at GitHub and provide a link to that project?

Thanks for the feedback.

**Comment by jeffbrown** [comment]
In the original report you have ` 'yyyy-MM-dd'T'HH:mm:ss'Z'` which has mismatched single quotes in it.  Maybe that is related to the problem.  Did you intend to have a single quote at the front and did you really intend for `'Z'` to be surrounded by quotes or are both of those mistakes?

**Comment by kpaxton** [comment]
Hi Jeff,
The mismatching of quotes is a typo in the ticket.
"yyyy-MM-dd'T'HH:mm:ss'Z'" is the format. It's the standard JSON format
that comes from the browser. Maybe I'm doing something wrong then? In
Config.groovy I have: grails.databinding.dateFormats =
["yyyy-MM-dd'T'HH:mm:ss'Z'", "yyyy-MM-dd'T'HH:mm:ss.S'Z'"]. Then Domain
object that has a Date createDate property. When I create a new Domain
object  like DomObj([createDate:"2014-04-25T13:55:02Z"]) I get rejected
properties in the errors property of the created Object.

Is Config.groovy not the right place for this setting? I also seem to have
issues with the grails.gorm.default.constraints setting not being
recognized.

**Comment by jeffbrown** [comment]
@kpaxton The config I showed above is defined in `application.yml`.  Does that work in your app?

**Comment by jeffbrown** [comment]
> "yyyy-MM-dd'T'HH:mm:ss'Z'" is the format.

Is there a reason that you want the literal `Z` in the format and not the replaceable token `Z`?  I think surrounding the `Z` with single quotes like that makes it a literal.

**Comment by jeffbrown** [comment]
If the browser is sending the date string with the literal `Z` in it, then of course you do want it surrounded by quotes in your pattern.

**Comment by kpaxton** [comment]
JSON dates are in the standard format  like this: "2012-04-23T18:25:43.511Z"

Config.groovy is currently the only way that I can set those properties. We are using Grails 2.4.3. 

If I look at the source of grails in org.grails.databinding.converters.DateConversionHelper, the same format I want to use is listed in there as well.

**Comment by kpaxton** [comment]
setting a breakpoint in the source for DataBindingGrailsPlugin shows that it's successfully picking up the dateFormats, but when actually binding the data, I get validation errors for those dates.

**Comment by kpaxton** [comment]
So when stepping through the source in SimpleDataBinder.convert() in this instance it wants to go into conversionService.convert and ends up using the GenericConversionService and the ObjectToObjectConverter instead of any of the Date converters like FormattedDateValueConverter. Is there a configuration that needs to be set to have it recognize those date specific converters?

Also, I'm stepping through in Unit test scenarios. However the issue is not isolated to them alone.

**Comment by kpaxton** [comment]
Looks like there is a test in SimpleDataBinderSpec that handles my case and in there is a `binder.registerConverter new DateConversionHelper()` line. I'm guessing the DateConversionHelper is not registered by default, which could be my problem?

**Comment by jeffbrown** [comment]
> I'm guessing the DateConversionHelper is not registered by default, which could be my problem?

If the converter isn't being registered then there may be something else going wrong in your project.  See https://github.com/grails/grails-core/blob/f20d5f5628d729afdc0c6780776f5b360adca8a8/grails-plugin-databinding/src/main/groovy/org/codehaus/groovy/grails/plugins/databinding/DataBindingGrailsPlugin.groovy#L73.

I have created a sample 2.4.3 app to try and recreate the problem and I cannot.  The settings I define in Config.groovy are working.  See the app at https://github.com/jeffbrown/issue540.

That contains the following config:

    // grails-app/conf/Config.groovy

    // ...

    grails.databinding.dateFormats = ["yyyy-MM-dd'T'HH:mm:ss'Z'", "yyyy-MM-dd'T'HH:mm:ss.S'Z'"]
    
    // ...
    
And the following controller:

    // grails-app/controllers/demo/DemoController.groovy
    package demo

    class DemoController {

        def createWidget(Widget w) {
            render "The date that was bound: ${w.initialDate}"
        }
    }

    class Widget {
        Date initialDate
    }

I have copied and pasted your format strings and sample data directly from above and the data binding appears to work:

    $ curl -H "Content-Type: application/json" -d '{"initialDate":"2012-04-23T18:25:43.511Z"}' -i http://localhost:8080/issue540/demo/createWidget
    HTTP/1.1 200 OK
    Server: Apache-Coyote/1.1
    Content-Type: text/html;charset=utf-8
    Transfer-Encoding: chunked
    Date: Wed, 17 Jun 2015 21:25:35 GMT

    The date that was bound: Mon Apr 23 18:25:43 CDT 2012

Can you provide a sample app which demonstrates the behavior you are seeing?

**Comment by jeffbrown** [comment]
The title of this issue reads `3.0.2 grails.databinding.dateFormats does not affect binding at all`.  One of your comments says `We are using Grails 2.4.3`.

What version of Grails are you having the problem with?

**Comment by jeffbrown** [comment]
I can't reproduce the problem with 3.0.2 or 2.4.3 so far.

**Comment by kpaxton** [comment]
I'll try to put something together this weekend hopefully.

**Comment by kpaxton** [comment]
Looks like I'm an idiot and trying to do this stuff in unit tests and console. Moving the tests to Integration and running the full application seem to work fine.

**Comment by jeffbrown** [comment]
What I show below may or may not be the best solution depending on what it is that you are actually trying to unit test, but one option you have is to do something like this...

Controller:

    // grails-app/controllers/demo/DemoController.groovy
    package demo

    class DemoController {

        def createWidget(Widget w) {
            [dateThatWasBound: w.initialDate]
        }
    }

    class Widget {
        Date initialDate
    }

Unit test:

    // src/test/groovy/demo/DemoControllerSpec.groovy
    package demo

    import grails.test.mixin.TestFor
    import spock.lang.Specification

    @TestFor(DemoController)
    class DemoControllerSpec extends Specification {

        static doWithConfig(c) {
            c.grails.databinding.dateFormats = ["yyyy-MM-dd'T'HH:mm:ss.S'Z'"]
        }

        void "test date binding format"() {
            when:
            params.initialDate = '2012-04-23T18:25:43.511Z'
            def model = controller.createWidget()

            then:
            model.dateThatWasBound
        }
    }
    
I asked a question above trying to clarify which version of Grails you are using and never got an answer.  The code shown here will work with Grails 3.

I hope that helps.

**Comment by jeffbrown** [comment]
> setting a breakpoint in the source for DataBindingGrailsPlugin shows that it's successfully picking up the dateFormats, but when actually binding the data, I get validation errors for those dates.

When you run your unit tests, I wouldn't expect the `DataBindingGrailsPlugin` to be picking up the `dateFormats` defined in `Config.groovy`.  Is the comment there speaking to unit tests, the running app, or something else?  If there are scenarios where `DataBindingGrailsPlugin` is picking up the `dateFormats` but not using them, then that would be a bug.

**Comment by kpaxton** [comment]
All of this is in reference to Grails 2.4.3 and in unit tests. What seemed
to be happening is that the DateConversionHelper class was never registered
due to the fact that Spring and the application context doesn't exist with
unit tests or a console window. I've moved it to integration tests and it
seems to be working right now.

The dataBindingGrailsPlugin doWithSpring was never called so the converters
that are normally loaded were never registered. When it got to actually
trying to create my domain class instance, something created a new instance
of GrailsWebDataBinder and it only registered the ByteArray Converter and
nothing else. So the dates would just go to the basic Object to Object
converter which tried to create a new Date with the standard constructor
which doesn't like the JSON date format.

These tests are for a service as well which uses GORM to store to a mongo
instance. Is there a way to get these to work with a Unit test instead of
Integration?

**Comment by jeffbrown** [comment]
> Is there a way to get these to work with a Unit test instead of
Integration?

Yes.  In 2.4.3 you could do something like this:

Domain class:

    // grails-app/domain/demo/Person.groovy
    package demo

    class Person {
        String name
        Date birthDate
    }

Service:

    // grails-app/services/demo/PersonService.groovy
    package demo

    class PersonService {

        def createPerson(params) {
            new Person(params)
        }
    }

Unit test:

    // test/unit/demo/PersonServiceSpec.groovy
    package demo

    import grails.test.mixin.TestFor
    import grails.test.mixin.TestMixin
    import grails.test.mixin.web.ControllerUnitTestMixin
    import spock.lang.Specification

    @TestFor(PersonService)
    @TestMixin(ControllerUnitTestMixin)
    class PersonServiceSpec extends Specification {

        static doWithConfig(c) {
            c.grails.databinding.dateFormats = ["yyyy-MM-dd'T'HH:mm:ss.S'Z'"]
        }

        void "test domain date binding"() {
            when:
            def per = service.createPerson(name: 'JSB', birthDate: '1969-11-15T18:25:43.511Z')

            then:
            'JSB' == per.name
            per.birthDate
        }
    }
    
Using `@TestMixin(ControllerUnitTestMixin)` here is a little bit hinky and you shouldn't have to do that, but it is simple enough and yields the behavior that you probably want.  As described earlier, this has improved in more recent releases.

I hope that helps.

**Comment by kpaxton** [comment]
hmmmm... I'm also using Fongo to fake our mongodb for these tests. So I'm already using a `@TestMixin` attribute on the test class. Is that mixin absolutely needed?

**Comment by jeffbrown** [comment]
>  I'm also using Fongo to fake our mongodb for these tests.

You can pass as many mixins as you like to `@TestMixin(...)`.

**Comment by jeffbrown** [comment]
> Is that mixin absolutely needed?

No, but it is a really simple way to get the behavior described here.

**Comment by kpaxton** [comment]
Looks like that fixed my issue. thanks!

**Comment by ryanberckmans** [comment]
@jeffbrown it seems that `grails.databinding.dateformats` ignores timezone. In your example

```
$ curl -H "Content-Type: application/json" -d '{"initialDate":"2012-04-23T18:25:43.511Z"}' -i http://localhost:8080/issue540/demo/createWidget
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Date: Wed, 17 Jun 2015 21:25:35 GMT

The date that was bound: Mon Apr 23 18:25:43 CDT 2012
```

Your input is `{"initialDate":"2012-04-23T18:25:43.511Z"}` which is 6:25PM UTC, and the output is 6:25PM central.

It seems the `'Z'` is just the character Z and not understood as specified in ISO 8601. I've noticed Java 8 has DateTimeFormatter, but we're on Java 7. How should I be parsing ISO 8601 dates?

**Comment by jeffbrown** [comment]
@ryanberckmans It looks like the timezone isn't represented in your input string.

**Comment by jeffbrown** [comment]
If you use `'Z'` that represents the literal `Z`, not a code.
