### ISSUE TITLE
GORM collection-level methods broken in MongoDB integration tests

### ISSUE THREAD

**Issue by miffels** [grails/grails-data-mapping#545]
Hi,

When I populate my database with seed data in an init/*BootStrap.groovy file I seem to be unable to query the data via the collection-level methods in tests (e.g. `findAll()`, `count()`). Curiously, `findBy*` _does_ work, though.

You can find an SSCCE (minus the DB configuration) [here](https://github.com/miffels/catfood/tree/master/gorm-mongodb-statictest). In summary, these are the most important bits:

_grails-app/init/LanguageBootStrap.groovy_

```
assert languages.size() == Language.count() // PASS
```

I store an instance of the `Language` domain class in the database and assert that the document count in the database equals the number of instances to persist. The session is flushed beforehand.

_src/integration-test/groovy/gorm/mongodb/statictest/LanguageFunctionalSpec.groovy_

```
expect: "Default languages should be there"
Language.findByKey "en"  // PASS
Language.count() || Language.findAll() // FAIL
```

I assert that the language we persisted is still there via the dynamic finder. This check passes. Neither `count()` nor `findAll()` reports any persisted instances, though. This is also noticeable, e.g., in REST controller tests, where `/languages` would return an empty array in tests but specific instances can still be retrieved,  e.g., via `/languages/<id>`. In dev everything works as expected.

Best,
Michael

**Comment by graemerocher** [comment]
Please upload an example to Github that reproduces the problem

**Comment by miffels** [comment]
I did.

> You can find an SSCCE (minus the DB configuration) here.

The word "here" is a link.

**Comment by graemerocher** [comment]
A missed that, thanks

**Comment by graemerocher** [comment]
Tested in 3.2.2.. the issue is the `@TestFor(Language)` which is only appropriate for unit tests. Once that is removed the test passes
