### ISSUE TITLE
Ability to turn off _class attribute from queries and saves

### ISSUE THREAD

**Issue by mikedehaan** [grails/grails-data-mapping#546]
I'm experiencing the issue described in:

https://github.com/grails/grails-data-mapping/issues/334

As a result, I'm looking for a way to turn off the _class attribute altogether. I've seen there is a way to do this by setting the type mapper to DefaultMongoTypeMapper:

http://forum.spring.io/forum/spring-projects/data/nosql/105045-spring-data-mongodb-mappingmongoconverter-remove-class

However, I don't see how this is possible with GORM.

Is there a way to set the default type mapper within GORM to eliminate the _class attribute or otherwise disable the _class attribute altogether?

Thanks.

**Comment by graemerocher** [comment]
The way to "turn off" the _class attribute is not to use inheritance in you domain models
