### ISSUE TITLE
Adding Criteria to a named query at invocation results in immediate execution

### ISSUE THREAD

**Issue by bwagner5** [grails/grails-data-mapping#548]
Adding Criteria to a named query at invocation results in immediate execution not allowing the use of another method such as listDistinct(), list(), or count(). 

Example: 

Book.someNamedQuery{ isNotNull('id') }    <-- this returns an array list

I believe it should work like this:

Book.someNamedQuery{ isNotNull('id') }.count()

**Comment by graemerocher** [comment]
This is a breaking change, and since the named query feature as largely been replaced by `where` queries we won't be evolving this feature going foreward
