### ISSUE TITLE
Massive performance hit when building a large Domain object

### ISSUE THREAD

**Issue by kpaxton** [grails/grails-data-mapping#553]
We have a Domain class that is very large with multiple other Domain classes embedded. In our performance testing we have found that building this domain object is very slow when compared to using GMongo queries. When doing a GMongo query like `Domain.collection.find()` we get results back in around 17-30ms. When using a `Domain.withCriteria{}` call we get results back in around 900ms. Our Domain class has approx 40 properties in it with 3 or 4 of them being embedded Domain objects that can have up to 20 more properties.

Any ideas on how we can improve the performace?

Plugin version: 3.0.2
Grails Version: 2.4.3

**Comment by graemerocher** [comment]
Recent advancements in the MongoDB 3.0 driver (codec support) will improve this area. We have a work in progress implementation that utilises this feature to avoid marshalling to and from BSONObject instances, which is what causes performance hit.

**Comment by kpaxton** [comment]
Forgive the dumb question, but would this require Mongo to be running a 3.0+ version with a Grails 3.0+ version? 

What version of the plugin will have this new support and is there a timeline?

**Comment by graemerocher** [comment]
The Mongo 3.0 driver doesn't require MongoDB 3.0, but yes the new version being developed will be Grails 3.0+

I am working on the new implementation now (including native MongoDB async support) so it should be really in the next few weeks

**Comment by kpaxton** [comment]
Awesome thanks. What version of the plugin should I look out for then?

**Comment by graemerocher** [comment]
Current version for Grails 3.0.x is 4.0.4 so this will be in the 5.0.x line

**Comment by kpaxton** [comment]
Thanks!
