### ISSUE TITLE
BUG: No custom types in embedded List allowed. Custom Type writeInternal function not called on save

### ISSUE THREAD

**Issue by kpaxton** [grails/grails-data-mapping#554]
Grails 2.4.3
Mongo plugin 3.0.2

I have a domain class setup like this

```
class Q {
 S search

static embedded=[
"search"
]
}

class S{
 O obj

static embedded =[
"obj"
]
}

src/groovy:
class O extends List{
//list object containing many different types of other src/groovy classes.
}
class F implements Node{}
class G implements Node{}
class D implements Node{}
etc...
```

I've tried to create a new Type for custom marshalling between the database for the O class. The readInternal function gets hit and works correctly. However when trying to persist to the database, the writeInternal does not get hit at all and only the className gets persisted as a string. 

If I try to create an item like:
```
def query = new Q()
query.search = new S()
query.search.obj = new O()
def f = new F()
query.search.obj.add(f)
query.save()
```

Custom Type properly registered in resources.groovy for Spring bean creation:
```
class OType extends AbstractMappingAwareCustomTypeMarshaller<O, DBObject, DBObject>{
OType(){
super(O)
}
@Override
protected Object writeInternal(PersistentProperty property, String key, O value, DBObject nativeTarget){
//code not hit
}

@Override
protected O readInternal(PersistentProperty property, String key, DBObject nativeSource){
//code hit properly
}
```

Any ideas why the writeInternal never gets hit and it seems like they just call toString() on the classes ?

**Comment by kpaxton** [comment]
When trying to debug I got down into the NativeEntryEntityPersister in handleEmbeddedInstance. When it gets to this property for the class O it seems to interpret it as an instance of Association then of Basic instead of Custom. I'm assuming this is because I'm extending List in the class implementation. Is there a way to force it to read it as a type Custom? Should you check for the existence of a customTypeMarshaller as well? Looking at line 1254 of NativeEntryEntityPersister.java

**Comment by graemerocher** [comment]
Now possible with custom codecs instead of types. see http://gorm.grails.org/latest/mongodb/manual/index.html#customTypes
