### ISSUE TITLE
object.propertyId method returns null when objects returned from criteria and is a subclass of another domain object

### ISSUE THREAD

**Issue by jasonschwab** [grails/grails-data-mapping#555]
A domain object that has a property that is also a domain object has a method "propertyId" that returns the ID of the property's object.

If the domain object is a subclass of another domain object, and the object is retrieved via criteria, foo.propertyId returns null instead of the ID.  foo.property.id still returns the appropriate value.

Demonstration of the issue here:

https://github.com/jasonschwab/grailsobjid/

**Comment by jasonschwab** [comment]
I wasn't sure if this should go in grails-data-mapping or core, it does seem to be related to criteria.

**Comment by graemerocher** [comment]
Seems to work fine if I update your app to Grails 3.2.2 and GORM 6
