### ISSUE TITLE
GRAILS-10278 GORM default mapping doesn't work for domain inheritance

### ISSUE THREAD

**Issue by tcrossland** [grails/grails-data-mapping#556]
See https://jira.grails.org/browse/GRAILS-10278

The issue also affects mapping with table-per-hierarchy. For example:

```groovy
grails.gorm.default.mapping = {
    "user-type" type: org.jadira.usertype.dateandtime.joda.PersistentLocalDate, class: org.joda.time.LocalDate
}
```

```groovy
class Person extends Party {
    LocalDate birthDate
}
```

Using Grails 2.5.1 and `hibernate4:4.3.10`, the property `birthDate` will be mapped as an `org.hiberante.type.SerializableType` rather than an `org.jadira.usertype.dateandtime.joda.PersistentLocalDate`.

Workaround: explicitly specify the mapping for user types in subclasses.

**Comment by olliefreeman** [comment]
I'm having the same problem except using Grails 3 and `grails-datastore-gorm-hibernate4:4.0.6.RELEASE` and `hibernate4:4.3.10` or `hibernate4:4.3.11`

Seems like the SessionFactory passed to the GrailsHibernateTemplate has had all tables rendered with any static mapping closures which are in the domain class but the default mapping closure is not being read. 

Oddly it works fine when the tables are generated, as the below closure 
```
grails.gorm.default.mapping = {
    'table' schema: 'other_schema'
}
```
places all tables in the 'other_schema' namespace but I can't then query any data without adding
```
static mapping = {
   table schema: 'other_schema'
}
```

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/753b579f26dcbc409f3baf6f640de2b1c2fffb29
