### ISSUE TITLE
Support for MongoDB 3.0 and SCRAM-SHA-1 authSchema 

### ISSUE THREAD

**Issue by klemensz** [grails/grails-data-mapping#557]
It seems that version 3.0.3 of the plugin doesn't support the new authSchema http://docs.mongodb.org/manual/release-notes/3.0-scram/ in MongoDB yet? At least I haven't found a way to make it work and the plugin documentation says only about support for MongoDB 2.6 in the release notes.

**Comment by graemerocher** [comment]
MongoDB 3.0 driver support is coming in Grails 3.1

**Comment by klemensz** [comment]
Does that mean it won't work with older Grails versions?

**Comment by graemerocher** [comment]
There is no intention right now to backport the plugin to 2.5.x yes. The changes to GORM required to support the MongoDB 3.0 were significant and it would be problematic maintaining both lines.

**Comment by vbaarda** [comment]
See http://stackoverflow.com/questions/32858484/issue-with-mongodb-user-authentication for a possible workaround. In particular:
```
dependencies {
    compile "org.mongodb:mongo-java-driver:2.13.1"
}
```
