### ISSUE TITLE
Plugin adds domain name to list of dirtyPropertyNames on updates

### ISSUE THREAD

**Issue by robertoschwald** [grails/grails-data-mapping#560]
We found a potential problem in the plugin for updates after users reported problems with mongodb in the audit-logging plugin. The dirtyPropertyNames list contains the fully qualified domain name of the domain class. This does not happen with hibernate.

As a workaround, we filter the domain name in the audit-logging domain event listener.
See https://github.com/robertoschwald/grails-audit-logging-plugin/issues/103 for reference.

Our workaround: https://github.com/robertoschwald/grails-audit-logging-plugin/commit/e9779c6efe122ac62dec06379f8360b194071b92

**Comment by graemerocher** [comment]
The reason for this is there are two variations of the `markDirty()` method one that takes no arguments and one that takes the property name `markDirty(propertyName)`. The former uses the class name to indicate that the instance is dirty, but of course `listDirtyPropertyNames()` should not return the class name too.

**Comment by graemerocher** [comment]
Fixed in master
