### ISSUE TITLE
Grails 3 GORM querying using anything defined in grails.gorm.default.mapping fails on embedded domains

### ISSUE THREAD

**Issue by olliefreeman** [grails/grails-data-mapping#563]
Using Grails 3 and `grails-datastore-gorm-hibernate4:4.0.6.RELEASE` and `hibernate4:4.3.10` or `hibernate4:4.3.11`

Seems like the SessionFactory passed to the GrailsHibernateTemplate has had all tables rendered with any static mapping closures which are in the domain class but the default mapping closure is not being read. 

I works fine when the tables are generated, as the below closure 
```groovy
grails.gorm.default.mapping = {
    'table' schema: 'other_schema'
}
```
places all tables in the 'other_schema' namespace but I can't then query any data without adding
```groovy
static mapping = {
   table schema: 'other_schema'
}
```

The same goes for defining usertypes as described in #556 except the GORM DB is generated correctly but then querying the DB the queries fall as tables are defined in the public schema and user-types are ignored resulting in exceptions such as 

```
13:59:48.290 [http-nio-8080-exec-3] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column "details_start_date" is of type date but expression is of type bytea
```

Workaround is to define static mapping = {} in all domain classes to define schema and user types.
Just very confused as to why the DB generation is correct but the querying fails.

Also this was working for me last week, 29th Sept 2015, as thats when I set up the Jadira user-types.

**Comment by olliefreeman** [comment]
Just had a look at my code again.....

it seems the user-type issue is only on embedded domains

*Subject.groovy*
```groovy
import org.jadira.usertype.dateandtime.threeten.PersistentLocalDate
class Subject {

    Detail details

    static embedded = ['details']

    static constraints = {
        details nullable: false
    }

    static mapping = {
        table schema: 'other' // Required for querying
    }
}

class Detail {

    LocalDate startDate
    EventDetail eventDetails

    static constraints = {
        startDate nullable: true
        eventDetails nullable: false
    }

    static mapping = {
        table schema: 'other' // Required for querying
        startDate  type: PersistentLocalDate // Required for querying
    }
}
```

*EventDetail.groovy*
```groovy
class EventDetail {

    LocalDate eventDate
    String organisationId
    String eventReference

    static constraints = {
        eventDate nullable: false, max: LocalDate.now()
        organisationId blank: false
        eventReference blank: false
    }

    static mapping = {
        table schema: 'other' // Required for querying
    }
}
```

*application.groovy*
```groovy
import org.jadira.usertype.dateandtime.threeten.PersistentLocalDate
import org.jadira.usertype.dateandtime.threeten.PersistentOffsetDateTime

grails.gorm.default.mapping = {
    'user-type' type: PersistentLocalDate, class: LocalDate
    'user-type' type: PersistentOffsetDateTime, class: OffsetDateTime
    'table' schema:  'other'
}
```

The above examples demonstrate the issue, in all cases we need the `table schema: 'other'` mapping to enable querying otherwise all queries are executed against `public.subject` etc and for the embedded class ONLY we need the `type: PersistentLocalDate`, for EventDetails the LocalDate renders fine

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/753b579f26dcbc409f3baf6f640de2b1c2fffb29
