### ISSUE TITLE
GORM inside bootstrap doesn't always work

### ISSUE THREAD

**Issue by amadfida** [grails/grails-data-mapping#570]
If we have a service call and then GORM code (creating some domain objects) inside Init from bootstrap, the GORM changes dont' commit to database. For example consider following code,

```java
    def init = { servletContext ->
                uefaService.initialize()
		initEufa()    	        
    }
```

Any changes made in `initEufa()` method are not persisted, though there is no error thrown. However if we change the order and move the service call after `initEufa()` call, the changes are committed.

I have attached a sample app, to demonstrate that. You can just run the app, and then either using neo4j-shell or 

`http GET http://localhost:8080/neo4j-app/clubs` see if the records were created.

**Comment by graemerocher** [comment]
Sorry where can I find the sample app?

**Comment by amadfida** [comment]
Sending vi email, zip is not allowed

**Comment by amadfida** [comment]
In addition same behavior is seen in Controllers.

**Comment by graemerocher** [comment]
So I tried to reproduce this and modified to:

    def init = { servletContext ->
		initEufa()
    	uefaService.initialize()
        int totalClubs = eufa.collect{ it.value.size() }.sum() 
        assert Club.count() == totalClubs
    }

But no matter how many times I restart the assertion always passes. 

I made some changes to transaction handling this morning that might help, please ensure you have the latest snapshot JAR files:

    rm -rf ~/.m2/repository/org/grails/grails-datastore-*

**Comment by amadfida** [comment]
if you switch the order i.e. move service call first
```
uefaService.initialize()
initEufa()
```

Do you still see that ?

**Comment by graemerocher** [comment]
Ok yes I see the problem... looking into it...

**Comment by graemerocher** [comment]
So yeah the issue is that `initUefa` is running outside of any declared transactional boundaries. The `init` closure of bootstrap by itself is not transactional, so you either have to wrap it in one or do all the work in a service, you can't mix and match.

So the solution is to wrap all the logic in `withTransaction` or do all the work in the `service`

**Comment by amadfida** [comment]
OK - is that also true for Controllers? We have a transactional controller that calls a service and then also does some gorm operations which are not committed to the db, however they seemed to be in the session.

**Comment by graemerocher** [comment]
it is true that writes need to be wrapped in a transaction, but if you upload an example to github of what you believe is a problem I can take a look

**Comment by amadfida** [comment]
OK with @Transactional on controller or method - mixing of services and gorm inside method works - but not without, which i assume is the correct behaviour.

**Comment by graemerocher** [comment]
that is indeed the correct behaviour, thanks for confirming
