### ISSUE TITLE
Neo4j plugin doesn't resolve all dependencies

### ISSUE THREAD

**Issue by amadfida** [grails/grails-data-mapping#571]
After a clean start (`rm -rf ~/.m2 and rm -rf ~/.grails/2.5.2`) - running the app with neo4j plugin can't resolve `org.grails:grails-datastore-core:jar`

```
 Error The following artifacts could not be resolved: org.grails:grails-datastore-core:jar:5.0.0.BUILD-SNAPSHOT, org.grails:grails-datastore-gorm:jar:5.0.0.BUILD-SNAPSHOT, org.grails:grails-datastore-simple:jar:5.0.0.BUILD-SNAPSHOT: Could not find artifact org.grails:grails-datastore-core:jar:5.0.0.BUILD-SNAPSHOT in grailsCentral (https://repo.grails.org/grails/plugins)
| Run 'grails dependency-report' for further information
````

after explicitly adding 
`mavenRepo "http://repo.grails.org/grails/core` in the BuildConfig it gets resolved.

**Comment by graemerocher** [comment]
This is only a temporary problem until the actual release is published and the dependencies are synced to Maven central

**Comment by amadfida** [comment]
Sounds good..
