### ISSUE TITLE
[neo4j] Delete all is failing when having related objects

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#573]
Having a model like this:
`class League {
	static hasMany = [clubs: Club]
}
class Club {
    static belongsTo = [league: League]
}`

and trying to do:
`League.where{ }.deleteAll()`

is throwing an exception like the following:
`org.neo4j.kernel.api.exceptions.TransactionFailureException: Node record Node[1,used=false,rel=172,prop=-1,labels=Inline(0x0:[]),light] still has relationships`

It looks that the generated query is not deleting the relationships. This is the query:
`[MATCH (n:League) 
OPTIONAL MATCH(n)<-[:LEAGUE]-(a1)
 DELETE a1, n] for parameters [{}]`

Adding DETACH DELETE should fix it.
http://neo4j.com/docs/stable/query-delete.html#delete-delete-a-node-with-all-its-relationships

**Comment by graemerocher** [comment]
I did try to use DETACH DELETE, but note it is Neo4j 2.3+ only, if you are happy only supporting that version of Neo4j then we can add it

**Comment by mburak** [comment]
Yes, I think we can live with that.
