### ISSUE TITLE
[neo4j] Bug - 2 relations created to the same object 

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#575]
Having a simple object model like this:

```
class League { 
  String name

  static hasMany = [clubs: Club]
}

class Club {
  String name
}
```

When I try to update a league's club using rest api, it's duplicating the relationship from league to that club. 
So the call to api looks like this:
```echo '{"name":"Argentinian League", "clubs":[{ "class":"app.Club", "id":"-6934249022395187200", "name":"River Plate"}]}' | http PUT http://localhost:8080/neo4j-app/leagues/-6934249022375714816```

and the db looks like this:
```(Argentinian League,235)-[:TAGS]->(River Plate,110)
(Argentinian League,235)-[:TAGS]->(River Plate,110)```

The Rest API is just binding the object in the request to that League object.

**Comment by graemerocher** [comment]
Please upload an example to github that reproduces the problem.

**Comment by mburak** [comment]
https://github.com/mburak/neo4j-app

You can try this command to update a tag (similar to club, replace ids with yours):

```
echo '{"name":"A League", "tags":[{ "class":"app.Tag", "id":"-6934249022395187200", "name":"MAJOR"}]}' | http PUT http://localhost:8080/neo4j-app/leagues/-6934249022375714816
```
