### ISSUE TITLE
Using cypherStatic on domain classes is not working

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#577]
Since the last snapshot, when trying to do something like this:

`List leagues = League.cypherStatic("MATCH (n:League) RETURN n")`

we get this kind of error:

```groovy.lang.MissingMethodException: No signature of method: app.League.cypherStatic() is applicable for argument types: (java.lang.String) values: [MATCH (n:League) RETURN n]```

It also happens if we pass a list or a map as param to the cypherStatic method.

**Comment by graemerocher** [comment]
Make sure you do a `grails clean` and then compile again. It is working fine for me, but this would happen if you did not recompile your classes. The latest snapshot no longer uses meta programming for domain enhancement.

**Comment by mburak** [comment]
It looks that it's related to this issue: https://github.com/grails/grails-data-mapping/issues/576
Removing the Hibernate dependency made it work.
