### ISSUE TITLE
Object's collection is not properly updated when is bound from UI 

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#578]
It looks that if we remove an object from a collection (like removing a club from league's clubs) is not updating the db correctly.
The binding is done correctly, I see the collection without the removed object but after saving it's still in the database.
If in the other way we add an object to the collection, it works fine.

**Comment by graemerocher** [comment]
I wrote a test for this here:

https://github.com/grails/grails-data-mapping/commit/5ced2a261d7a1f67913f85b0b1631adcbc3732d0

Seems to work from an the GORM for Neo4j level, so could be a binding issue. If you believe it is a mapping issue please provide an example that reproduces the problem

**Comment by mburak** [comment]
What if instead of doing the removeFrom you just replace the teams collection for a new one with the removed object. I think that's what the binding is doing. Shouldn't that work?

**Comment by graemerocher** [comment]
if you are completely replacing the collection then yes that should probably work, however this is not a new bug and the behaviour is the same as the previous Neo4j plugin implementation in that it monitors the collection for changes:

https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-neo4j/src/main/groovy/org/grails/datastore/gorm/neo4j/collection/Neo4jPersistentSet.groovy#L92

**Comment by mburak** [comment]
After the binding the collection is the same but with an object removed, so I guess it's not going through that monitor? This wasn't working with the previous Neo4j either.

**Comment by mburak** [comment]
You can see an example of the issue in this project: https://github.com/mburak/neo4j-app 

If you send a json like this to update a league removing one club:

```
echo '{"class":"app.League","id":-6934246299024384000,"clubs":[{"class":"app.Club","id":-6934246299024367608},{"class":"app.Club","id":-6934246299024375802},{"class":"app.Club","id":-6934246299024367605},{"class":"app.Club","id":-6934246299024359416},{"class":"app.Club","id":-6934246299024375799},{"class":"app.Club","id":-6934246299024351232},{"class":"app.Club","id":-6934246299024367611},{"class":"app.Club","id":-6934246299024375805},{"class":"app.Club","id":-6934246299024359422},{"class":"app.Club","id":-6934246299024359419},{"class":"app.Club","id":-6934246299024367614}],"dateCreated":"2015-11-10T17:14:48Z","lastUpdated":"2015-11-10T17:14:48Z","name":"German Bundesliga","tags":[{"class":"app.Tag","id":-6934246299038711808}]}' | http PUT http://localhost:8080/neo4j-app/leagues/-6934246299024384000
```

you will see that the club is not removed in the db.

(You should to change those ids in the json to the ids generated for you)

**Comment by mburak** [comment]
Hi @jeffbrown, did you have a chance to look at this one?
Thanks.

**Comment by jeffbrown** [comment]
> Hi @jeffbrown, did you have a chance to look at this one?

Yes, and it isn't a simple fix.  There are some complexities around this that will need to be sorted out.

**Comment by mburak** [comment]
Is there any workaround you think we can apply while this is fixed?

**Comment by jeffbrown** [comment]
For now you could exclude the collection from mass property binding and then just add your own code that manipulates the collection.  That isn't great, but isn't as horrible as it sounds either.  It would not be much code.
