### ISSUE TITLE
No converter found capable of converting from type java.lang.Class<?> to type java.lang.String

### ISSUE THREAD

**Issue by wwarlock** [grails/grails-data-mapping#593]
That Exception throwed in `HibernateDatastoreSpringInitializer.getBeanDefinitions()` on line
```groovy
def dialect = config.getProperty("${dsConfigPrefix}.dialect", (String)hibernateProperties['hibernate.dialect']?.toString())
```
There is the option to rewrite this line to
```groovy
def dialect = config."${dsConfigPrefix}.dialect" ?: (String)hibernateProperties['hibernate.dialect']?.toString()
```
I've verified in debug mode that `config."${dsConfigPrefix}.dialect"` returns the value.
And I think that must work, but I am not tested it in plugin, just looking to the code.

Oh, yes, my DB is Postgress.

**Comment by jeffbrown** [comment]
Is your `hibernate.dialect` value being assigned a `java.lang.Class` or a `String` that is the name of a `java.lang.Class`?

**Comment by wwarlock** [comment]
It's a class. Do you want to know the exact class name?

**Comment by jeffbrown** [comment]
If you make a `String` does that solve the problem?

**Comment by jeffbrown** [comment]
> Do you want to know the exact class name?

No.

**Comment by wwarlock** [comment]
No, making String do not solve problem. And Exception exactly about that.
I've tried the next form
```groovy
def dialect = config.getProperty("${dsConfigPrefix}.dialect", (String)hibernateProperties['hibernate.dialect']?.toString()).toString()
```

**Comment by wwarlock** [comment]
I think the next line bellow may throw that error too
```groovy
def hibConfigClass = config.getProperty("${dsConfigPrefix}.configClass", (String)hibernateProperties['hibernate.config_class']?.toString())
```

**Comment by rvanderwerf** [comment]
if I put single quotes around class name  for dialect it appears to work for me?
