### ISSUE TITLE
Failed to apply plugin [id 'org.grails.grails-web']

### ISSUE THREAD

**Issue by wwarlock** [grails/grails-data-mapping#595]
When using Grails3 with versions of plugin below
```
org.grails.plugins:hibernate4:5.0.0.RC1
org.grails.plugins:hibernate5:5.0.0.RC1
```
Gradle throws error on every command even on cleaning
```bash
$ gradle clean
```
```bash
* What went wrong:
A problem occurred evaluating root project '<MyProjectName>'.
> Failed to apply plugin [id 'org.grails.grails-web']
   > Cannot add task ':urlMappingsReport' as a task with that name already exists.
```
With the older `org.grails.plugins:hibernate:4.3.10.7` that problem didn't exist.

**Comment by graemerocher** [comment]
You can continue to use the old version of the plugin in the `buildscript` block until this is fixed. It is only needed for the `schema-export` command

**Comment by wwarlock** [comment]
Actually, I can't. Please look at issue #593.
But I'll try to make temporary custom fixes for my own.
