### ISSUE TITLE
Calling deleteAll() on a where query for a domain class with a composite identity fails

### ISSUE THREAD

**Issue by burtbeckwith** [grails/grails-data-mapping#602]
I saw this testing spring-security-core with Grails 3.1.0.M3. The generated UserRole class fails when calling `deleteAll()` on a where query because `JpaQueryBuilder.validateProperty()` calls `entity.getIdentity().getName()` but the identity is null. `compositeIdentity` seems properly configured though.

You can see this with these simple domain classes

    class User {
       String name
    }

    class Role {
       String name
    }

    class UserRole implements Serializable {

       User user
       Role role

       static mapping = {
          id composite: ['user', 'role']
          version false
       }
    }

Insert some instances:

    User.withTransaction {
       def user = new User(name: 'admin').save(failOnError: true)
       def role = new Role(name: 'ROLE_ADMIN').save(failOnError: true)
       new UserRole(user: user, role: role).save(failOnError: true)
    }

and then any of these three `deleteAll()` calls will fail:

    User.withTransaction {

       def u = User.first()
       def r = Role.first()

       println UserRole.where { user == u && role == r }.deleteAll()
       println UserRole.where { user == u }.deleteAll()
       println UserRole.where { role == r }.deleteAll()
    }

**Comment by graemerocher** [comment]
Thanks will check it out
