### ISSUE TITLE
GORM public API for composite primary keys

### ISSUE THREAD

**Issue by mjcmatrix** [grails/grails-data-mapping#606]
Please could you consider adding the following methods to the GORM public API `GrailsDomainClass`?

    boolean isCompositePrimaryKey()
    
    GrailsDomainClassProperty[] getIdentifierProperties()

Or alternatively, formal documented access to an abstract CompositeKey representation, accessible somehow via the Public API, perhaps via `GrailsDomainClass.getIdentifier().getType()`.

My external implementation of `isCompositePrimaryKey()` uses `grails-datastore-gorm-hibernate4` directly:

	public isCompositePrimaryKey(GrailsDomainClass targetClass) {
		def binder = new GrailsDomainBinder()
		def idMapping = binder.getMapping(targetClass).identity
		return idMapping instanceof CompositeIdentity
    }

My external implementation of `getIdentifierProperties()` is based around this pseudo-code:

    def binder = new GrailsDomainBinder()
    def idMapping = binder.getMapping(targetClass).identity
    if(idMapping instanceof CompositeIdentity) {
        identity = ((CompositeIdentity)idMapping).propertyNames
    }

**Comment by graemerocher** [comment]
There is already an API for this via `PersistentEntity.getCompositeId()` in GORM 5. Usage of the Grails interfaces (i.e. `GrailsDomainClass` ) is largely discouraged now in favour of the GORM ones (`MappingContext` and `PersistentEntity`)

**Comment by mjcmatrix** [comment]
Thanks for your response Graeme. If there is existing API that I simply haven't come across yet then lets close this feature request.

Once I have finished migrating my Grails 2.4 app to 3.1.0.M3 I am keen to refactor the code to the new GORM 5 APIs.

I must confess I have been unable so far to find useful online documentation or SO posts that will help me refactor my Grails app towards these interfaces.

I can't find an introduction to GORM Datastores and other concepts, or a bridging guide for existing Grails 2.x users to migrate to the new Grails-independent GORM APIs. (Perhaps I can contribute some doc content once I have done so.)

I don't know how to access these interfaces from the applicationContext or Grails artefacts so it is hard to get started. What replaces GrailsDomainClass (is it PersistentEntity?) How do I access this from a typical Grails service (as metadata)? (Not from an entity instance.)

I might not be using the correct Google search terms.

My app contains an extensive CRUD taglib and supporting services that introspect the GORM entities mainly from a GrailsDomainClass argument, to auto-generate ajax forms, action buttons from method arguments, and other aspects of the CRUD UI. It also includes a NonDomainClass concept to allow the UI to consume Command objects and method arguments as entities.) My API consumption so far is primarily based on the excellent Grails 2.x user documentation and various SO answers to questions posed by other people for Grails 2.x trying to access entity metadata.

**Comment by mjcmatrix** [comment]
I can see now that the key interfaces have been there in the API Javadocs and source code for a long time, most from at least Grails 2.2 / 1.0 in some cases but are never mentioned in the Grails docs! Seems I can simply access this via the GormStaticApi.
