### ISSUE TITLE
Enums do not persist with Mongo datastore

### ISSUE THREAD

**Issue by paulfairless** [grails/grails-data-mapping#609]
Upgrading an existing grails 2.4 app to `grails 2.5.3` and `mongodb:5.0.0.RC3`. Our enum types no longer persist into the database. I'm not sure if this is a deprecated feature?

Person.groovy
```
class Person {
    String name
    PersonState state

    static constraints = {
    }

    enum PersonState {
        GOOD, BAD
    }
}
```

Bootstrap.groovy
```
class BootStrap {

    def init = { servletContext ->
        Person p = new Person(name:'bloggs', state: PersonState.GOOD)
        p.save(flush:true)

        Person p2 = Person.findByName('bloggs')
        assert p.state == PersonState.GOOD

    }
    def destroy = {
    }
}
```

returns:
```
ERROR context.GrailsContextLoaderListener  - Error initializing the application: 
assert p2.state == PersonState.BAD
       |  |     |              |
       |  null  false          BAD
       mongo.test.Person : 1
```

**Comment by graemerocher** [comment]
Thanks for the feedback, keep it coming.. very useful!

**Comment by graemerocher** [comment]
I wrote a test for this and it seems to work fine. https://github.com/grails/grails-data-mapping/issues/609

Please upload an example that reproduces the problem

**Comment by paulfairless** [comment]
This was the test project I was using: `grails-2.5.3`

[mongo-test.zip](https://github.com/grails/grails-data-mapping/files/78556/mongo-test.zip)

**Comment by graemerocher** [comment]
Thanks will, take another look

**Comment by paulfairless** [comment]
looking again, it seems my test isn't doing a good job of re-creating the issue, using `withNewSession` seems to help

Bootstrap.groovy:
```
import mongo.test.Person
import mongo.test.Person.PersonState
class BootStrap {

    def init = { servletContext ->
        Person p = new Person(name:'statesman2', state: PersonState.GOOD)
        p.save(flush:true)

        Person.withNewSession {
            Person p2 = Person.findByName('statesman2')
            assert p2.state == PersonState.GOOD
        }

    }
    def destroy = {
    }
}
```

**Comment by graemerocher** [comment]
The issue seems to be that inner enums are compiled as domain classes, so they have all of the GORM methods etc. So this is definitively a bug
