### ISSUE TITLE
Could not find matching constructor for: org.grails.datastore.gorm.bootstrap.AbstractDatastoreInitializer(groovy.util.ConfigObject, java.util.ArrayList)

### ISSUE THREAD

**Issue by webeasymail** [grails/grails-data-mapping#610]
version:
 app.grails.version=2.5.2
 compile ":mongodb:3.1.5"

Start the error ：

2015-12-23 18:29:14,985 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Could not find matching constructor for: org.grails.datastore.gorm.bootstrap.AbstractDatastoreInitializer(groovy.util.ConfigObject, java.util.ArrayList)
Message: Could not find matching constructor for: org.grails.datastore.gorm.bootstrap.AbstractDatastoreInitializer(groovy.util.ConfigObject, java.util.ArrayList)
    Line | Method
->>   33 | doCall                    in MongodbGrailsPlugin$_closure1
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    754 | invokeBeanDefiningClosure in grails.spring.BeanBuilder
|    584 | beans . . . . . . . . . . in     ''
|    527 | invokeMethod              in     ''
|    262 | run . . . . . . . . . . . in java.util.concurrent.FutureTask
|   1145 | runWorker                 in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                       in java.lang.Thread
Error |

**Comment by graemerocher** [comment]
Fixed in 5.0.1
