### ISSUE TITLE
while updating save is not working if we modify a single field-mongodb plugin 5.0.0.RC3

### ISSUE THREAD

**Issue by PreethiSakar7** [grails/grails-data-mapping#611]
If i edit all fields in domain class save is working properly. If i edit a single field and try to save with flush= true, mongodb plugin 5.0.0.RC3 does not write to disk.

Domain class
class Book{
   String name
   String author
}

def b = Book.get(Id)
b.name = "Grails Cook Book"
b.author = "TOM"
b.save()

Above works properly. Because all fields are marked dirty.

if i edit only the author and try to save grails does not save or throws any error. The edit is taking place only in the memory but not flushing it to the disk. Even if  i use 

b.save(flush:true)

Help to solve this problem

**Comment by graemerocher** [comment]
Please upload an example to github that reproduces the issue. In the meantime you can probably workaround with:

    b.markDirty()

**Comment by PreethiSakar7** [comment]
Thanks for Response.

I have retify my mistake. I set a constrain for both field. 

class Book{
String name
String author

 static constraints = {
        name nullable:false, blank: false, unique: true
        author nullable:false, blank: false, unique: true
    }
}

So if i save a single field it doesn't update in database. After remove constrain i can upadate single field.

I set constrain using static mapping. It works perfect.

 static mapping = {
        name index:true, indexAttributes: [unique:true, dropDups:true]
        author index:true, indexAttributes: [unique:true, dropDups:true]
    }
