### ISSUE TITLE
Neo4j - Dynamic associations are not inserted/modified or deleted on object update

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#613]
Dynamic associations work fine when you are creating an object with some dynamic property pointing to another domain class object, but when you are updating the object, dynamic associations are not considered at all, you add any or modify an existing one but the object relationships are not updated.
You can find an example of this problem by starting the app at https://github.com/mburak/neo4j-app and starting it up on a clean db.

**Comment by graemerocher** [comment]
This is probably the dirty checking, since there is no way to know with dynamic associations if an object is dirty or not. Can you try add `obj.markDirty()` before the call to `save()` and see if that helps. Thanks.

**Comment by mburak** [comment]
I still see an issue on one to many associations. Let's say we have an association called buddies, and we create an object and set buddies = [john], then we edit it and add a new buddy to the list, so we save [john, max], then john is not related any more to the object but max is. Even if i create it with 2 buddies only one is saved.

**Comment by graemerocher** [comment]
Will take a look

**Comment by mburak** [comment]
I still see one last issue which is the when you remove a relationship setting the property to null like john.bestFriend = null, the association is not removed.
