### ISSUE TITLE
No longer able to configure alternative ID type (e.g. UUID) globally in Grails 3

### ISSUE THREAD

**Issue by mjcmatrix** [grails/grails-data-mapping#620]
In Grails 2.4 it was possible to implement an alternative identity type (such as _UUID_) globally for applications that require it, instead of the default _long_ identity type.

This was achieved with a combination of a global mapping in `Config.groovy` and an abstract base class for domain entities, declaring an explicit `UUID id` property, that all domain classes extend. (The abstract class would be declared in ``src/main/`` and behave the same way as a JPA **@MappedSuperclass**.)

In Grails 3 I have explored different ways to achieve this, but have been unable to find a solution that satisfies DRY principals. UUID identity *can* be defined for individual concrete domain classes.

#### Objective:
To use `UUID` generated identity on domain classes globally within an application (and plugins: specifically _audit-logging_), instead of the default `long` identity type.

#### General method:

Declare an explicit (or automatic) id property of type UUID (`UUID id`) on a common base class for all domain entities and set the column generator and type somewhere, i.e.:
```
static mapping = {
    id(generator: "uuid2", type: "uuid-binary") // H2
}
```

#### Working implementation in Grails 2.4:

**1.** Declare `UUID id` on a common abstract base class for entities (declared in `src/main/groovy`)  and configure a global id mapping for the 'id' column in `Config.groovy`.

#### Strategies tried in Grails 3:

**1.** Declare `UUID id` on an abstract base class and put global id mapping into `application.groovy` (as per Grails 2.4)

**THIS FAILS**: GORM does not detect the entity (seen from domain entity count) - and exceptions are thrown on use. Example exception:
```
java.lang.IllegalStateException: Either class [co.example.domain.User] is not a domain class or GORM has not been initialized correctly or has already been shutdown. If you are unit testing your entities using the mocking APIs
	at org.grails.datastore.gorm.GormEnhancer.stateException(GormEnhancer.groovy:159) ~[grails-datastore-gorm-5.0.0.RC3.jar:na]
	at org.grails.datastore.gorm.GormEnhancer.findInstanceApi(GormEnhancer.groovy) ~[grails-datastore-gorm-5.0.0.RC3.jar:na]
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.currentGormInstanceApi(GormEntity.groovy:1311) ~[grails-datastore-gorm-5.0.0.RC3.jar:na]
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:140) ~[grails-datastore-gorm-5.0.0.RC3.jar:na]
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$save.call(Unknown Source) ~[na:na]
```

(I have tried putting the base class in `grails-app/domain` instead of `src/main/groovy` the latter.

**2.** Declare `UUID id` and put id mapping into the concrete domain class

**THIS WORKS** but is not DRY, requiring declaration in every domain class

**3.** Declare only the id mapping on the concrete domain class

**THIS FAILS** with Exception:
```
org.hibernate.PropertySetterAccessException: IllegalArgumentException occurred while calling setter for property [co.example.domain.User.id (expected type = java.lang.Long)]; target = [User()], property value = [ff71d73a-d499-4be5-a46d-31d5c9d16f70] setter of co.example.domain.User.id
```

**4.** Declare `UUID id` and id mapping on the abstract base class

**THIS FAILS**: GORM does not detect the entity and exceptions are thrown for 'no such domain class'

**5.** Do not declare `UUID id` on any class and put global id mapping into `application.groovy`

**THIS FAILS**: GORM declares id field as 'long' but generator is UUID. Exception: 
```
org.hibernate.PropertySetterAccessException: IllegalArgumentException occurred while calling setter for property [co.example.domain.User.id (expected type = java.lang.Long)]; target = [User()], property value = [1a86c51c-fd85-459d-b973-2269a3ff0dd6] setter of co.example.domain.User.id
```

I cannot find in the official documentation how to change the identity type from the default `long` type.

In Grails 2.4, global mapping configuration always seemed to be a workaround if used to define to-be-inherited mappings for common fields that are declared in a base class; however I was certainly grateful for it's existence. I also notice that the `importFrom` method in constraints has been removed in Grails 3; I used this extensively in Grails 2.4. Therefore I now need to find out if Grails 3 does the inheritance of properties, constraints and mappings that are defined in a tree of parent classes automatically, or if such declarations are still ignored, as they appeared to be in Grails 2? (The expected behaviour would be IMHO to inherit constraints and mappings from superclasses along with properties, including from abstract base classes declared outside of the `grails-app/domain` directory; i.e. the Grails equivalents of JPA @MappedSuperclass.)

Am I doing something wrong here, or is global identity type change currently an ability not supported in Grails 3?

**Comment by graemerocher** [comment]
Have you tried moving the abstract base class to `grails-app/domain`?

**Comment by mjcmatrix** [comment]
Yes Graeme. When the abstract base class is moved to `grails-app/domain`a persistent table is created in the database of the root abstract class (table-per-hierarchy) and I get exceptions about not being able to instantiate an abstract class as a spring bean.

**Comment by graemerocher** [comment]
ok, and what about making the abstract base class a `trait` ?

**Comment by mjcmatrix** [comment]
I've confirmed that if the abstract base class is moved to `grails-app/domain` a persistent table is created for the base class (for all entities), which is undesirable (though no exceptions are thrown in my small test app at least).

Should I add `@MappedSuperclass` to indicate that the abstract class should not be persisted?

I considered **traits** as a path to go down earlier on but figured that since Groovy is an OO language (and inheritance worked in Grails 2.4) then I should be able to use inheritance __or__ traits, so I would persist in trying inheritance first. (The document also says inheritance is supported from abstract and concrete base classes, same as Grails 2.x and I've seen nothing yet anywhere about using traits in a domain model.)

There is a hierarchy of abstract base classes in my app: `Persistable <- Auditable <- ReferableAuditable <- SomeDomainClass` (also `Schedulable`). All classes descend from `Persistable` or one of the subclasses (typically `Auditable` which adds change auditing behaviour and fields).

I could try traits instead of inheritance next, if you think I should.

The simple test app I am currently using to explore domain and startup issues (such as this) contains the basic _spring-security-core_ domain model only (`User`, `Role`, `UserRoleGroup`, etc.) with 2 abstract base classes introduced and UUID identity.

**Comment by mjcmatrix** [comment]
`@MappedSuperclass` appears to be ignored on an abstract base class (in `grails-app/domain`, so a persistent table per-hierarchy is still created for the base class).

**Comment by mjcmatrix** [comment]
I've tried `trait` for the common behaviour too now. Many problems seem to result from that approach.

I've tried both a single trait parent class (below) and also a trait that inherits from another trait (per my model) which is worse. Where I declare `trait` or `abstract trait` (if there is such a thing) seems to make no difference.

Issues include:
  - I am unable to override key Domain Class behaviours using traits instead of inheritance, such as `toString()`, without build errors
  - Each trait implemented gains it's own `id` and `version` field and getId() and other methods seem to conflict unless I declare `UUID id` on all traits
  - The GORM and Hibernate traits/enhancements don't seem to like this. See build report below.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.

| Error Failed to start server (Use --stacktrace to see the full trace)
| Running application...
startup failed:
testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: -1: The method 'java.lang.Object $static_methodMissing(java.lang.String, java.lang.Object)' from trait 'co.example.domain.Persistable' must not be static. Only fields may be static in an interface.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: -1: The method 'java.lang.Object $static_propertyMissing(java.lang.String, java.lang.Object)' from trait 'co.example.domain.Persistable' must not be static. Only fields may be static in an interface.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: -1: The method 'java.lang.Object $static_propertyMissing(java.lang.String)' from trait 'co.example.domain.Persistable' must not be static. Only fields may be static in an interface.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: -1: The method 'java.lang.Object getTransients()' from trait 'co.example.domain.Persistable' must not be static. Only fields may be static in an interface.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: -1: The method 'void setTransients(java.lang.Object)' from trait 'co.example.domain.Persistable' must not be static. Only fields may be static in an interface.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: -1: The field 'version' is not 'public static final' but is defined in trait 'co.example.domain.Persistable'.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: -1: The field 'instanceControllersDomainBindingApi' is not 'public static final' but is defined in trait 'co.example.domain.Persistable'.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: -1: The field 'instanceConvertersApi' is not 'public static final' but is defined in trait 'co.example.domain.Persistable'.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: 34: Repetitive method name/signature for method 'java.lang.String toString()' in trait 'co.example.domain.Persistable'.
 @ line 34, column 2.
   			return this.name
    ^

testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: 34: Repetitive method name/signature for method 'java.lang.String toString()' in trait 'co.example.domain.Persistable'.
 @ line 34, column 2.
   			return this.name
    ^

testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: -1: Repetitive method name/signature for method 'java.lang.String toString()' in trait 'co.example.domain.Persistable'.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: -1: Repetitive method name/signature for method 'java.lang.String toString()' in trait 'co.example.domain.Persistable'.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: -1: Repetitive method name/signature for method 'java.lang.String toString()' in trait 'co.example.domain.Persistable'.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Persistable.groovy: -1: Repetitive method name/signature for method 'java.lang.String toString()' in trait 'co.example.domain.Persistable'.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Auditable.groovy: -1: The field 'version' is not 'public static final' but is defined in trait 'co.example.domain.Auditable'.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Auditable.groovy: -1: The field 'instanceControllersDomainBindingApi' is not 'public static final' but is defined in trait 'co.example.domain.Auditable'.
 @ line -1, column -1.
testapp_lessdomain2/grails-app/domain/co/example/domain/Auditable.groovy: -1: The field 'instanceConvertersApi' is not 'public static final' but is defined in trait 'co.example.domain.Auditable'.
 @ line -1, column -1.
17 errors

```

**Comment by mjcmatrix** [comment]
It is worth mentioning that having the domain abstract base classes in `src/main/groovy` does appear to work, in terms of it behaving the same way as a `@MappedSuperClass`. The base classes can successfully contribute properties and behaviour to the domain classes that extend them.

I raised this issue because the base class longer works and exceptions result as soon as I try to declare a `UUID id` field in the base class.

**Comment by mjcmatrix** [comment]
I have attached a test app for this issue (the domain model of spring-security-core with added inheritance and UUID identity).

[issue620_uuid_baseclass.zip](https://github.com/grails/grails-data-mapping/files/82931/issue620_uuid_baseclass.zip)

**Comment by ctoestreich** [comment]
I get the application to boot just fine removing the abstract from the `auditable` and `persistable` classes.  

<img width="519" alt="screen shot 2016-01-09 at 4 20 18 pm" src="https://cloud.githubusercontent.com/assets/691357/12218696/02843676-b6ed-11e5-9eba-d9250bd55ba0.png">
[testapp_lessdomain2.zip](https://github.com/grails/grails-data-mapping/files/83867/testapp_lessdomain2.zip)

**Comment by mjcmatrix** [comment]
Hi ctoestreich,

Thanks for looking at this. I have followed your steps and yes, if you make the abstract base classes non-abstract the app does compile and it is now possible to log in.

However if you look at the database schema in `http://localhost:8080/dbconsole` you will see that if the base classes are no longer abstract then the three main entities are modelled as a single 'Persistable' table (i.e. table-per-hierarchy). That is not the correct schema and why an abstract base class is used. (In Grails, the equivalent of a `@MapperSuperclass`.)

**Comment by graemerocher** [comment]
This issue can be worked around by annotating your domain classes with `grails.persistence.Entity`

**Comment by driverpt** [comment]
@graemerocher Is there any ETA on the non-annotation workaround ?
