### ISSUE TITLE
Neo4j - dynamic property marked as dirty even when it didn't change

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#629]
Setting the same value to a dynamic property is marking it as dirty when it shouldn't.

Shouldn't this be cheked in Neo4jEntity propertyMissing method?
```
    def propertyMissing(String name, val) {
        def unwrappedInstance = unwrappedInstance(this)
        def session = AbstractDatastore.retrieveSession(Neo4jDatastore)
        if (name == Neo4jQuery.UNDECLARED_PROPERTIES) {
            return getOrInitializeUndeclared(session, unwrappedInstance)
        } else {

            Map undeclaredProps = getOrInitializeUndeclared(session, unwrappedInstance)
            undeclaredProps.put(name, val)

            def mappingContext = session.mappingContext
            if (mappingContext.isPersistentEntity(val)) {
                session.persist(val)
            } else if (Neo4jSession.isCollectionWithPersistentEntities(val, mappingContext)) {
                session.persist((Iterable)val)
            }
            if (unwrappedInstance instanceof DirtyCheckable) {
                ((DirtyCheckable)unwrappedInstance).markDirty(name)
            }
        }
    }
```

It's setting it as dirty even when you can check if the value is the same looking at the undeclaredProps map.

**Comment by graemerocher** [comment]
Yup seems like this could be improved.

**Comment by mburak** [comment]
Cool. And it also looks that marking the dynamic property as dirty is setting a wrong original value. It seems that it's setting the new value to the $changedProperties instead of the old one so there's no way to know what was the old value.

**Comment by mburak** [comment]
It looks that same thing happens to static properties? On binding it's setting the properties even when they didn't change so then the object is dirty and it's persisting it again and throwing the preupdate and postupdate events. You can see the problem in https://github.com/mburak/neo4j-app.  You can run this to update a league so you can see that it's throwing the preupdate and postupdate event to the related club even when this is not updated at all:
```echo '{"name":"French Ligue 1", "clubs": [ {"id": 2757560765373775873 } ] }' | http --session=test PUT http://localhost:8080/neo4j-app/leagues/2757560765373775872```
I added a GormEventsListener that is debugging all this events.

**Comment by mburak** [comment]
What about the static ones? The DirtyCheckableTransformer doesn't seem to consider if the value has changed. It's marking it as dirty always.

**Comment by graemerocher** [comment]
I'm not sure I understand what you mean, static properties are not persistable

**Comment by mburak** [comment]
I mean not dynamic, just normal properties.

**Comment by graemerocher** [comment]
yeah that is much trickier to solve looking at the current implementation
