### ISSUE TITLE
mongodb doesn't recognize databaseName prop from application.yml

### ISSUE THREAD

**Issue by pocket5s** [grails/grails-data-mapping#63]
May not be specific to application.yml as this works in grails 2.4.x and the associated plugin, but doesn't work in plugin 4.x and grails 3.0. have a fix and will do a pull request.

**Comment by miffels** [comment]
Can confirm that ``grails.mongodb.databaseName`` is ignored for the most part. @pocket5s Are you working on a PR?

**Comment by pocket5s** [comment]
you beat me to it :) The merge happened a week or two ago. Can't say what release it will be in however.

**Comment by bond-** [comment]
+1 for the issue
@graemerocher as per the latest code: https://github.com/grails/grails-data-mapping/blob/40102e8f2341c1cd560aa94e6219c3c9dd097775/grails-datastore-gorm-mongodb/src/main/groovy/grails/mongodb/bootstrap/MongoDbDataStoreSpringInitializer.groovy

MongoDB plugin seems to be reading databaseName from connectionString and databaseName is ignored. Looks like either the documentation or code need to be fixed.

**Comment by bond-** [comment]
Never mind I forgot to read the manual. The old plugin used to look for:
grails { mongo { ... } }

New plugin is looking for grails { mongodb {} }
