### ISSUE TITLE
Allow to define multiple Server Connections / Hosts / Replica-Sets per Domain

### ISSUE THREAD

**Issue by timo-klarshift** [grails/grails-data-mapping#630]
It is possible to map different Domains to different databases and collections via configuration. But how can I specify DomainA persists on Host A and Domain on Host B ?

Also see:
- http://grails.1312388.n4.nabble.com/Using-multiple-mongoDB-servers-td4644827.html
- http://forum.spring.io/forum/other-spring-related/grails/126696-multiple-mongodb-hosts-with-mongodb-plugin
- http://grails.1312388.n4.nabble.com/Connect-to-multiple-Mongodb-hosts-td4632269.html

So, what I want to do is either in config

```
grails {
  mongo {
    host = 'localhost'
    
    collection_a {
      host = '222.12.12.12'
    }

    collection_b {
      host = '127.0.0.1'
      port = 27088
    }
  }
}
```

Or in Domain 

```groovy
class DomainA {
  static mapping = {
    database 'foo'
    collection 'collection_a'
    connection host: '123...', port: 27088
  }

  // ...
}
```

Or more advanced:

```groovy
class DomainA {
  static mapping = {
    database 'foo'
    collection 'collection_a'
    replicaSet [[host: '123...', port: 27088], [...]]
  }

  // ...
}
```

I am talking about grails2, but I guess it applies to v3 as well.

You can point me into the right direction and I will create a PR if I am able to fix it

**Comment by graemerocher** [comment]
Relates to #608 since the MongoDB plugin doesn't currently support multiple datasources

**Comment by graemerocher** [comment]
Multiple data source supported was added to MongoDB in 6.0.0.M2
