### ISSUE TITLE
RestBuilder throws NullPointerException

### ISSUE THREAD

**Issue by Eylen** [grails/grails-data-mapping#635]
In grails 3.1.0 RestBuilder (5.0.0.RELEASE) is throwing a NullPointerException at least when in test environment with check task.

Diving a bit in the code the problem seems to be in these lines of RestBuilder.groovy:

```groovy
if(ConvertersConfigurationHolder.getConverterConfiguration(JSON) instanceof DefaultConverterConfiguration) {
    // init manually
    new ConvertersConfigurationInitializer().initialize()
}
```

In the initialize method grailsApplication is null and it throws a NullPointerException when it tries to get the configuration. May be related to manually creating ConvertersConfigurationInitializer?

**Comment by graemerocher** [comment]
Duplicates #633
