### ISSUE TITLE
Can't use authentication with MongoDB

### ISSUE THREAD

**Issue by burtbeckwith** [grails/grails-data-mapping#636]
If you configure MongoDB authentication by setting the `username` and `password` config values, e.g.

    grails {
       mongodb {
          username = '...'
          password = '...'
       }
    }

the database name doesn't get set and startup will fail.

The database name attribute is correctly resolved in `MongoDbDataStoreSpringInitializer.getBeanDefinitions` whether it's the default (app name) or overridden in the config. But the value isn't used to set the name when configuring the `MongoClientFactoryBean`, only for replicaSet/replicaPair. This causes the `MongoCredential.createCredential` call in `MongoClientFactoryBean.afterPropertiesSet` to fail and throw an exception.

**Comment by graemerocher** [comment]
Thanks for the report, the MongoDB folks recommend going forward that connection strings are used https://docs.mongodb.org/manual/reference/connection-string/

So this is probably a viable (and recommended) workaround for the current situation.

**Comment by marcDeSantis** [comment]
:+1: this had me scratching my head for a few hours this morning.
