### ISSUE TITLE
autoRetrieveAssociation error for one-to-many association

### ISSUE THREAD

**Issue by CoreKnowledge** [grails/grails-data-mapping#638]
In AbstractHibernateGormInstanceApi.groovy,
line 301 looks like following:
` ((GroovyObject)propValue).setProperty(prop.name, propValue)`
I think it should look like:
` ((GroovyObject)target).setProperty(prop.name, propValue)`

However, I have following problem.
In SpringSecurity User Class (I named it 'Person') I declared:
`static hasMany = [
         shouts     : Shout
]`
In another Domain Class 'Shout' I delcared:
`static belongsTo = [
        person: Person
]`

I am not able to save a new Shout, because of error
"groovy.lang.MissingPropertyException: No such property: person for class: market.springsecurity.Person"

Thanks very much in advance for help and taking care of!
Best Regards!

**Comment by graemerocher** [comment]
This was already fixed by https://github.com/grails/grails-data-mapping/commit/29113859899fb3f06abb7736c5a66c9869e33e80
