### ISSUE TITLE
Polymorphic queries do not work when adding mongodb -plugin to app and domain classes are in the plugin

### ISSUE THREAD

**Issue by smakela** [grails/grails-data-mapping#642]
Polymorphic queries do not work when adding mongodb -plugin to app and domain classes are in the plugin.

Created a sample project to Github:
https://github.com/smakela/mongo-polymorphic

Just run the tests with and without the mongodb -plugin.

**Comment by smakela** [comment]
Added two Domain classes Foo and Bar to the plugin and queries work with them, but not with Animal and Dog.

**Comment by graemerocher** [comment]
One issue I see with the sample is that most of the domain classes use Hibernate for persistence as there is no `mapWith` defined and you have the hibernate plugin in the `build.gradle`. In fact if I comment out the `hibernate` plugin from `build.gradle` all the tests pass. The bigger mystery is why one of the domain classes is uses MongoDB at all.

**Comment by smakela** [comment]
@graemerocher Yep. But that is the case in our apps. We have mongo domains with mapWith -attribute and hibernate ones without the mapWith. And that is where i figured out this bug.

I just did not add those domain objects that are persisted with hibernate to this app because it does not matter for this case.

And I know that the tests pass when commenting out the hibernate. But the thing is that you can use multiple datastores for the app. And it should work.

**Comment by graemerocher** [comment]
right, and that bug should be fixed, however I did note that in the same app none of the domains defined `mapWith`

**Comment by smakela** [comment]
Sorry. I did not add those domains that are persisted with mongodb to this example :)
But anyways. Hope this fixes the problem. Thanks!
