### ISSUE TITLE
[Grails 2.4.4] GORM Criterions silently ignored -> bad generation of the SQL request

### ISSUE THREAD

**Issue by Guigoz** [grails/grails-data-mapping#643]
The problem is simple : when using Criterias, sometime some Criterions are silently ignored.

The problem comes from AbstractHibernateCriterionAdapter in the grails-datastore-gorm-hibernate-core JAR.
The criterionAdaptors HashMap is not properly populated.

This map is a final static HashMap used to map GORM Criterions to Hibernate ones.

The problem randomly occurs when the application starts.
Sometime the HashMap is populated without any problem, sometimes problem occurs...
This Hashmap is static final and is kept corrupted for the rest of the application lifetime. That's why you sometime encounter this problem and everything goes well after a restart.

The HashMap can be corrupted when several threads are creating a AbstractHibernateCriterionAdapter object at the same time.
Each thread calls the constructor and the initialize() method.
This method is synchronized but the synchronized idiom is only effective for several threads accessing the same object (https://docs.oracle.com/javase/tutorial/essential/concurrency/syncmeth.html)

As a result, the synchronized doesn't lock properly the initialize() method and several threads can try to populate the criterionAdaptors HashMap at the same time.
HashMap is not thread safe, as a result the HashMap gets corrupted and some Criterions are missing.

If a GORM Criterion is not found in this HashMap, the Criterion is silently ignored... Which explains why it disapears from the generated request.

Source : http://stackoverflow.com/questions/35136648/where-query-creates-wrong-sql-on-production/35198559#35198559

**Comment by Guigoz** [comment]
Hi Graeme and thanks for your fix.
Do you plan to add this fix in the next Grails 2.X release?

**Comment by graemerocher** [comment]
the next release of GORM 5 (5.0.2) which supports 2.x yes

**Comment by tomasbartalos** [comment]
Hi, we're experiencing this issue with catastrophic consequences (our paying users are being cancelled). I'm using grails 2.4.4, gorm-3.1.3. What would you recommend as a quickfix without changing the grails version? I was thinking to add to BootStrap.init {} something like: 
```
AbstractHibernateCriterionAdapter.initialized = false
//force re-init the criterionAdaptors map
new HibernateCriterionAdapter(new Query.IsNull("whatever"))
```

**Comment by graemerocher** [comment]
Running any `where` query on startup in `BootStrap.groovy` should avoid the problem, the issue only occurs when multiple threads access `HibernateCriterionAdapter` at the same time

**Comment by tomasbartalos** [comment]
Thanks for your quick reply. I'm trying to re-init the criterionAdaptors map (`AbstractHibernateCriterionAdapter.initialized = false`), because I'm worried, that in BootStrap its already corrupted by initialization of some plugin (so where query would not help me here).

**Comment by graemerocher** [comment]
plugins are not initialised in parallel so how would that happen? The issue only occurs when multiple threads initialise at the same time

**Comment by tomasbartalos** [comment]
By opening a thread pool with some query workers in plugin's init code. Which is very unlikely but still not impossible. 
However in that case we have no guarantees, since those threads can interfere with our bootstrap :-/

**Comment by graemerocher** [comment]
And which plugin does that and will do that? You have an application where you are unsure whether a plugin is opening a thread pool and accessing GORM in bootstrap?

**Comment by tomasbartalos** [comment]
I think we've slipped down the road, but I'll explain my concerns. I have a
plugin, which do access gorm in bootstrap, currently its not doing it in
parallel, however how can I be sure weather next versions will not
introduce this kind of optimization? Is there any best practice or
recommendation stating not to do it? This issue has so devastating
financial impact, that I need to have 100% guarantee, not 99%...
