### ISSUE TITLE
ERROR grails.boot.GrailsApp - Application startup failed

### ISSUE THREAD

**Issue by sunilpes** [grails/grails-data-mapping#644]
Environment details: MongoDB Windows 10 Grails 3.0.12 java version "1.8.0_25" Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
[build_gradle.txt](https://github.com/grails/grails-data-mapping/files/123584/build_gradle.txt)
[application_yml.txt](https://github.com/grails/grails-data-mapping/files/123586/application_yml.txt)

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoTransactionManager': Cannot resolve reference to bean 'mongoDatastore' while setting bean property 'datastore'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDatastore': Cannot resolve reference to bean 'mongo' while setting bean property 'mongo'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongo': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: source can not be null`

**Comment by sunilpes** [comment]
please help me to resolve this error. I am waiting for your reply

**Comment by graemerocher** [comment]
Upload an example to github that reproduces the problem

**Comment by sunilpes** [comment]
[samatvam.zip](https://github.com/grails/grails-data-mapping/files/126933/samatvam.zip)

Attached project.

**Comment by graemerocher** [comment]
There are several issues with the example attached, it seems to be referencing Grails 2.x plugins? Upload a reproducible example or the issue will be closed.
