### ISSUE TITLE
Unique index name for multi columns may exceed database maximum index name length

### ISSUE THREAD

**Issue by droggo** [grails/grails-data-mapping#657]
This worked fine in Grails 2 + Hibernate 3 but fails in Grails 3.1.1 with Hibernate 4. Unique key name is now generated from class and property names.

Simplified domain which causes this issue:
```
class CollaborationTeamTemplateMember {

	User user
	Role role
	static belongsTo = [collaborationTemplate: CollaborationTeamTemplate]

	static constraints = {
		collaborationTemplate unique: ['user', 'role']
	}
}
```

This generates following foreign key in schema:
```
alter table collaboration_team_template_member 
        add constraint unique_collaboration_team_template_member_collaboration_template_id unique (role_id, user_id, collaboration_template_id);
```

And name `constraint unique_collaboration_team_template_member_collaboration_template_id` is too long for MariaDB/MySQL where limit is 63. It will also fail for Oracle where limit is 30.

In Grails 2, unique index was not generated as separate instruction but was part of database table definition so this problem did not occur with syntax like:
```
create table collaboration_team_template_member (
	...columns, PK, etc...
	unique (role_id, user_id, collaboration_template_id)
);
```

Indexes for single properties have static length names hashed with MessageDigest (`AbstractGrailsDomainBinder.setUniqueName(UniqueKey)`). If the same would be used here, this would probably fix the issue.

We feel this is a bug but if its intended please close this issue. Workaround for us is quite easy, we just have to use other property to define multi-column index and in this case this is not an issue for the app.

**Comment by sponiro** [comment]
The reason for the change is discussed here: https://github.com/grails/grails-data-mapping/issues/623 and here https://github.com/grails/grails-data-mapping/pull/626
The problem with too long names was in there before yet not as likely to occur.

I suggest extracting the name generation into a separate class with interface. The implementation could switch depending on the database to react to different limitations. Also, it would be nice if the user could configure the implementation in use.

So a default implementation would be most strict and could digest them to very short and unreadable names. Another implemention could use parts (or the whole) domain class name or whatever to generate nice names.

**Comment by droggo** [comment]
Another solution could be to allow developer to set unique index name manually, just like standard named index may be defined in mapping
