### ISSUE TITLE
ObjectId is being stored as String

### ISSUE THREAD

**Issue by mikedehaan** [grails/grails-data-mapping#661]
I have the following domain object:

```
class Person {
    @Id
    ObjectId id;
    String name;
    String description;
    ObjectId scopeId
}
```

When I set the scopeId `person.scopeId = new ObjectId()` and save it to the database, I am unable to recall the row using the same ObjectId:

`Person scopePerson2 = Person.findByScopeId(scopePerson.scopeId);`

I am able to find the row if I use MongoCollection and query as a String:

```
MongoCollection collection = Person.collection;
Person scopePerson3 = collection.findOne([scopeId : scopePerson.scopeId.toString()]) as Person;
```

A sample project is provided that duplicates the issue:
https://github.com/mikedehaan/gormTest

**Comment by mikedehaan** [comment]
This appears to be specific to:

```
grails {
    mongodb {
        engine = "codec"
    }
}
```

If I change to `engine = "mapping"` the test works as expected.

**Comment by ChiranjibKarn** [comment]
This issue seems re-surfaced, am using mongodb plugin 5.0.5 in Grails 3.1.1, when storing ObjectId it saves as String in MongoDB 3.2
