### ISSUE TITLE
Grails 2.4.2 support mongodb 3.x

### ISSUE THREAD

**Issue by sayhong** [grails/grails-data-mapping#662]
Can anyone change mongodb plugin support down to Grails2.4.2?
We have many Grails2.4.2 system want to change mongodb 3.x from 2.x.
Or any way can I go?
Thank you a lot~

**Comment by graemerocher** [comment]
Upgrade to Grails 2.5.x

**Comment by sayhong** [comment]
some another plugin don't support grails 2.5.x ...
