### ISSUE TITLE
MongoDB don't save properly a Domain Class that implements org.springframework.security.core.userdetails.UserDetails

### ISSUE THREAD

**Issue by grails-coder** [grails/grails-data-mapping#664]
I have a project that is attempting to integrate a grails application and MongoDB, SDK details are:

- Grails 2.5.3
- MongoDB plugin: org.grails.plugins:mongodb:5.0.0.RC1
- Java 7
- Spring Security: 3.2.9.RELEASE

The problem occurs whenever I need to configure a Domain Class to implement the org.springframework.security.core.userdetails.UserDetails interface, by default I have to implement some methods: getAuthorities(), isAccountNonExpired(), isAccountNonLocked(), isCredentialsNonExpired(), and isEnabled(). For each method, except for getAuthorities(), I need to persist the status in the database, that's why I created 4 Boolean properties: accountNonExpired, accountNonLocked, credentialsNonExpired, and enabled respectively. The problem is that when I save the object to the MongoDB database I can't see the 4 properties stored, kindly notice I have another Boolean field, forceLocalLogin, which is sucessfully persisted to the database.

It's necessary to mention I tested the same code with the Hibernate plugin and Oracle database, in that case the problem is not present, I mean, all of the fields are correctly persisted to the Oracle database.

Here the class definition:

`package mx.blogspot.decibelelektrobeat
import org.springframework.security.core.GrantedAuthority
import org.springframework.security.core.authority.SimpleGrantedAuthority
import org.springframework.security.core.userdetails.UserDetails
class ApplicationUser implements UserDetails, Serializable {

    String username
    String password
    Boolean accountNonExpired
    Boolean accountNonLocked
    Boolean credentialsNonExpired
    Boolean forceLocalLogin
    Boolean enabled

    static hasMany 		= [roles: ApplicationRole]

    static constraints = {
        username nullable:false, blank:false, unique:true
        password nullable:false, blank:false
        accountNonExpired nullable:false, blank:false
        accountNonLocked nullable:false, blank:false
        credentialsNonExpired nullable:false, blank:false
        forceLocalLogin nullable:false, blank:false
        enabled nullable:false, blank:false
    }

    @Override
    Collection <? extends GrantedAuthority> getAuthorities(){
        return roles.collect {ApplicationRole authority ->
            new SimpleGrantedAuthority(authority.name)
        }
    }

    @Override
    boolean isAccountNonExpired() {
        return accountNonExpired
    }

    @Override
    boolean isAccountNonLocked(){
        return accountNonLocked
    }

    @Override
    boolean isCredentialsNonExpired(){
        return credentialsNonExpired
    }

    @Override
    boolean isEnabled(){
        return enabled
    }
}`

Attached a project sample
[mongo-integration.tar.gz](https://github.com/grails/grails-data-mapping/files/166441/mongo-integration.tar.gz)

Kindly refer also to a github repository: [https://github.com/grails-coder/mongo-integration.git](mongo-integration)

**Comment by graemerocher** [comment]
The plugin requires you have setters as well as getters, in your code you only have getters `isAccountNonLocked` etc.

**Comment by grails-coder** [comment]
I already tried adding the setters but the result was exactly the same, in the end I sorted it out by changing the class definition to this one:

`class ApplicationUser implements UserDetails, Serializable {

    String username
    String password
    Boolean nonExpiredAccount
    Boolean nonLockedAccount
    Boolean nonExpiredCredentials
    Boolean forceLocalLogin
    Boolean isAccountEnabled

    static hasMany 		= [roles: ApplicationRole]

    static constraints = {
        username nullable:false, blank:false, unique:true
        password nullable:false, blank:false
        nonExpiredAccount nullable:false, blank:false
        nonLockedAccount nullable:false, blank:false
        nonExpiredCredentials nullable:false, blank:false
        forceLocalLogin nullable:false, blank:false
        isAccountEnabled nullable:false, blank:false
    }

    @Override
    Collection <? extends GrantedAuthority> getAuthorities(){
        return roles.collect {ApplicationRole authority ->
            new SimpleGrantedAuthority(authority.name)
        }
    }

    @Override
    boolean isAccountNonExpired() {
        return nonExpiredAccount
    }

    @Override
    boolean isAccountNonLocked(){
        return nonLockedAccount
    }

    @Override
    boolean isCredentialsNonExpired(){
        return nonExpiredCredentials
    }

    @Override
    boolean isEnabled(){
        return isAccountEnabled
    }

}`
In this last case now it's saving the data up in the mongo database. Code already uploaded in the [github repo](https://github.com/grails-coder/mongo-integration)
