### ISSUE TITLE
Grails 3.1.3 ignores gorm default constraints from application.groovy

### ISSUE THREAD

**Issue by salex772** [grails/grails-data-mapping#666]
Attached application cannot startup because of validation errors during bootstrapping. Bootstrap adds just one record to a domain class.

Bootstrap code: 

```
import defaultgormvalues.SystemSettings

class BootStrap
{

	def init = { servletContext ->

		new SystemSettings(name: "book_price", value: "10").save(failOnError: true)

	}

	def destroy = {

	}
}

```

```
package defaultgormvalues

class SystemSettings {

    static constraints = {
        value blank: false, nullable: false
        name blank: false, nullable: false
    }

    static mapping = {
        table '`tbl_system_settings`'
    }

    String name
    String value
    String description

}
```

Error:
     
    NULL not allowed for column "DESCRIPTION";

In test environment also cannot start.

Application.grrovy

```
grails.gorm.default.constraints = {
	'*'(nullable: true, blank: true)
}
```

[defaultGormValues.zip](https://github.com/grails/grails-data-mapping/files/172198/defaultGormValues.zip)

**Comment by salex772** [comment]
Unfortunately it has another issue. If put something like this to a domain class (in attached example app)

```
static mapping = {
		table '`tbl_system_settings`'
		otherStringValue column: 'Lalala'
                //or whatever put here
	}

String otherStringValue
```

App will not launch.

**Comment by graemerocher** [comment]
Create a new issue and upload an example that reproduces the issue
