### ISSUE TITLE
Issues when upgrading from Mongo GORM 3.0.2 to 5.0.2

### ISSUE THREAD

**Issue by shiranr** [grails/grails-data-mapping#667]
Hi,

We are seeing issues when trying to upgrade to grails 3.1.3 using GORM 5.0.2 and java driver 3.0.2.
The two issues we encountered are reproduced in this project: 
https://github.com/shiranr/reproduce

The readme file explains how to see them in runtime.

Both issues happen when using GORM 5.0.2 trying to get existing data, which was pushed with an old GORM version.

The first exception is:
readInt64 can only be called when CurrentBSONType is INT64, not when CurrentBSONType is INT32.

and the second:
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for interface java.util.Set.

More details can be found in the readme file.
can you please advice? 

Thanks,
Shiran

**Comment by graemerocher** [comment]
The first exception is not a bug, you're storing an integer in the `version` field, but field type is `Long` so you have a data integrity issue. You can fix this by ensuring your insert statement is using a long:

```
collection.insert(new BasicDBObject('name', 'bla2').append('_id',new ObjectId().toString()).append('version', 0L).append('profiles', [] as Set))
```

**Comment by shiranr** [comment]
Hi Graem, 

You are correct for this specific example. 
But it seems that the version which was inserted by GORM 3.0.2 as `0` got inserted as integer and not as `NumberLong`. We see this in our database.
When upgrading to GORM 5.0.2 we see this exception being thrown.

Thanks,
Shiran

**Comment by shiranr** [comment]
You can find the issue reproduced in here:
https://github.com/shiranr/reproduce2
under the path: http://127.0.0.1:8080/reproduce2/  in test controller under the index action.

**Comment by graemerocher** [comment]
Yeah I understand the issue, unfortunately there is nothing we can do about it. You have 3 options:

1) Use the the mapping engine (the old less efficient implementation):

```
grails:
    mongodb:
        engine: mapping
```

2) Correct the data at the database level

or

3) Change all of your `version` properties to `Integer` types

**Comment by mlentzner** [comment]
This mongo command will update all your version fields from Int to Long:

`db.getCollectionNames().forEach(function (c) { db.getCollection(c).find({version: {$type: 16}}).forEach(function (x) {x.version=new NumberLong(x.version);db.getCollection(c).save(x)}) });`

**Comment by zakrzew** [comment]
I had similar problem migrating to GORM 5.x.x, with similar error message.
Editing model class and changing type of version field from Integer to Number helped in my case.
So this:

`Integer version
`
I chagned to that:

`Number version`
