### ISSUE TITLE
Grails 3.1.4 ignores gorm default constraints if a field has a record in mapping block

### ISSUE THREAD

**Issue by salex772** [grails/grails-data-mapping#671]
This issue is similar to #666
NULL not allowed for column "OTHER_STRING_VALUE";

the same problem if put something to 'mapping' block.
[defaultGormValues 2.zip](https://github.com/grails/grails-data-mapping/files/178317/defaultGormValues.2.zip)
 

```
static mapping = {
		table '`tbl_system_settings`'

		//-----ALL THIS DO NOT ALLOW TO STARTUP WITH THE SAME ISSUE-------

		otherStringValue sqlType: 'text'
		settingsDate sqlType: 'date'
		otherStringValue2 column: 'First_Name'
	}

	String name
	String value
	String description
	String otherStringValue
	String otherStringValue2
	Date   settingsDate

```

**Comment by salex772** [comment]
Hallo, how to upgrade grails 3.1.4 to data-mapping 5.0.4?

**Comment by codeconsole** [comment]
I am wondering the same thing.  What is the best way to force a specific version of gorm?
I tried     
    compile "org.grails.plugins:hibernate4:5.0.4.BUILD-SNAPSHOT" 
but I am getting version mismatches on sub-packages where 5.0.3 is taking preference

**Comment by codeconsole** [comment]
https://github.com/grails/grails-data-mapping/issues/695

**Comment by salex772** [comment]
So this issue is closed but I still do not know how to bring this fix to my project.

**Comment by codeconsole** [comment]
salex722, see https://github.com/codeconsole/grails3bugs for an example
