### ISSUE TITLE
Issues when upgrading to Mongo GORM 5.0.3

### ISSUE THREAD

**Issue by shiranr** [grails/grails-data-mapping#675]
Hi, 

Two scenarios which cause the same exception:
1. When inserting an empty Set field through the driver and then trying to find it through GORM
2. When trying to save domain with Set fields either with values or without any values
We get back the exception:
Can't find a codec for interface java.util.Set.. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null

This can be seen in:
https://github.com/shiranr/reproduce 
in the TestController under the paths:
http://127.0.0.1:8080/setBug
http://127.0.0.1:8080/anotherSetBug

Thanks,
Shiran

**Comment by dda-christopher-kessler** [comment]
I'm also getting a similar issue, but for Maps

org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class java.util.LinkedHashMap
