### ISSUE TITLE
Error when casting MongoDB `Document` to domain object

### ISSUE THREAD

**Issue by bessb** [grails/grails-data-mapping#679]
According to the documentation, this should be possible: 
```groovy
def person = Person.collection.findOne(name: 'John Doe') as Person
```
But when I try to do this in a controller, I get an Exception
```
ERROR org.grails.web.errors.GrailsExceptionResolver - ConnectionNotFoundException occurred when processing request: [GET] /person/index
No datastore session found. Call Datastore.connect(..) before calling Datastore.getCurrentSession(). Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.grails.datastore.mapping.core.ConnectionNotFoundException: No datastore session found. Call Datastore.connect(..) before calling Datastore.getCurrentSession()
    at example.PersonController.index(PersonController.groovy:14)
    ... 3 common frames omitted
```
I've uploaded an example  Grails 3.1.4 project to reproduce the issue.
https://github.com/bessb/grails-mongodb-issue

**Comment by bessb** [comment]
It looks like when I move the query to a service it works fine. I don't see anything in the documentation that mentions this, and this same code works fine in a Grails 2.5.4 project with version 3.0.3 of the MongoDB plugin.

**Comment by jeffbrown** [comment]
> It looks like when I move the query to a service it works fine.

I think there has to be some other variable in the mix.  Maybe transaction management?

**Comment by bessb** [comment]
@jeffbrown Adding `@Transactional` to the controller fixes it. Is this required when making calls directly via the MongoDB driver?

**Comment by jeffbrown** [comment]
> Adding @Transactional to the controller fixes it. Is this required when making calls directly via the MongoDB driver?

Possibly, but I am not a mongo expert.  @graemerocher Do you know if the above is expected behavior?

**Comment by graemerocher** [comment]
When you do `as Person` we have to lookup the current mongodb connection from somewhere, the way we do that now is via the current session so `withSession` would work too
