### ISSUE TITLE
Controller respond syntax does not include embedded objects in JSON output

### ISSUE THREAD

**Issue by mlentzner** [grails/grails-data-mapping#680]
If I use respond on a DO with embedded objects then I get only class and id for those objects. But in the Mongo document they are fully contained in the BSON of the document. 

Seem like the respond command should be modified for Mongo DB to inflate embedded objects to JSON. It's a 1:1 relationship with the BSON object so it seems like this should be the default behavior.

**Comment by graemerocher** [comment]
This is related to Grails core and not GORM so report here https://github.com/grails/grails-core/issues

Please also provide an example that reproduces the problem
