### ISSUE TITLE
[3.1.4 + Hibernate4] criteria.listDistinct() returns only last projected property instead of all

### ISSUE THREAD

**Issue by droggo** [grails/grails-data-mapping#684]
Having domain like:
```
class Parent {
	String name
	static hasMany = [children: Child]
}
```
User could create criteria like:
```
new Parent(name: 'IntegrationSpec').save(failOnError: true)
Parent.createCriteria().listDistinct {
	projections {
		property 'id'
		property 'name'
	}
}
```
But instead of expected list with two entries as a result, only name is returned - `['IntegrationSpec]`
If `list()` is used instaed of `listDistinct()` results are correctly returned - `[[1, 'IntegrationSpec']]`

Example project is here: https://github.com/droggo/GrailsSubqueries
Integration Spec to demo this problem: https://github.com/droggo/GrailsSubqueries/blob/master/src/integration-test/groovy/error/ListDistinctWithPropertyProjectionsIntegrationSpec.groovy

**Comment by graemerocher** [comment]
probably this needs to be 

```
    projections {
        property id() 
        property 'name'
    }
```

**Comment by droggo** [comment]
`id` was just example, we tried with many different fields and it always returns just last one for `listDistinct` but works for `list`. I just tried on this example to add `String description` field to domain and use description instead of id and problem is the same.

I also verified with `id()` as you suggested - there is no difference to `property 'id'`

**Comment by graemerocher** [comment]
thanks for the feedback

**Comment by graemerocher** [comment]
The way you would write this query is:

```
Parent.createCriteria().list {
    projections {
        distinct ['id', 'name']
    }
}
```

We could add complicated logic to the builder to detect the fact you had called `listDistinct` and make every called to `property(..)` go into a list that would invoke `distinct`, but frankly that will just over complicate matters for something that is already possible.

**Comment by droggo** [comment]
This approach is completely fine, thank you!
