### ISSUE TITLE
Driver is now very fussy about property access

### ISSUE THREAD

**Issue by mlentzner** [grails/grails-data-mapping#688]
If a DO does not contain the property the driver throws a ConnectionNotFoundException. Not only is this counter-intuitive, but it makes it more of hassle to use, and violates the Law of Demeter since the consuming code needs to know more about the objects it is being passed. 

This used to be fine:

println address.zip ? 'has US zip code' : 'does not have US zip code'

Now throws error ConnectionNotFound if the address DO does not contain the property zip. Expected behavior would be for address.zip to return null.

**Comment by graemerocher** [comment]
upload an example with steps to reproduce

**Comment by mlentzner** [comment]
Is it acceptable to put this in a public github repository? There are
several issues and it would be more convenient for me to keep them all in
one place.



On Tue, Apr 5, 2016 at 11:49 PM, graemerocher <notifications@github.com>
wrote:

> upload an example with steps to reproduce
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/grails/grails-data-mapping/issues/688#issuecomment-206153012>
>



-- 
Matt Lentzner
Manager
RoseRyan Inc.

**Comment by graemerocher** [comment]
sure

**Comment by mlentzner** [comment]
public gh repo at mlentzner/grails-issues

%{--Mongo Plugin #688 - Can't use commented code anymore - used to be valid--}%

Not the best example are far as practical code, but the old behavior is useful in general for an extended class hierarchy.

**Comment by mlentzner** [comment]
Don't intend to be a pest but having to call `<domain object>.hasProperty('<property name>')` or check class with `instanceof` (the worse option IMO) before each property call to a subclass in the hierarchy is a huge PITA. 

Is this a result of more static compiling being done? It seems very java-like and not very duck-typey groovy-like. If you don't consider this a bug, I'd like to know so I can move forward and put in the required code. 

If you do intend to change the behavior just know I'm eagerly awaiting this. :)

**Comment by graemerocher** [comment]
This was fixed by https://github.com/grails/grails-data-mapping/commit/481f7f4602b8c85bada5ae12ab963ba153595b7e

**Comment by mlentzner** [comment]
Confirmed fixed. Thanks for taking care of this so quickly!
