### ISSUE TITLE
Embedded Object: Error fetching property's constraints value from class

### ISSUE THREAD

**Issue by puneetbehl** [grails/grails-data-mapping#689]
**Grails 2.5.4
MongoDB GORM 5.0.3.RELEASE**

While using embedded object in the domain class an exception is thrown in the console. Here is what's happening:

Domain Class: `grails-app/domain/sampleApp/Person.groovy`
```groovy
class Person {
	String name
	String emailAddress
	Address address

	static embedded = ['address']

	static constraints = {
		emailAddress nullable: true
	}
}	
```

Embedded Groovy class: `src/groovy/sampleApp/Address.groovy`
```groovy
class Address {
	String street
	String streetLine2
	String postalCode
	String city
	String state
	String country

	static constraints = {
		streetLine2 nullable: true
	}
}
```
In the Bootstrap.groovy, create one record
```groovy
new Person(name: "John Doe",
	address: new Address(street: "123 Main St.", state: 'TX', city: 'Dallas', postalCode: '238873')).save(flush: true)
```

Now, run the application and following exception is shown is shown in the console/terminal
```groovy
| Error Error fetching property's constraints value from class sampleApp.Address: null
```

**Comment by nitin-singh** [comment]
Link for the repository of sample application showing above mentioned issue is:
https://github.com/nitin-singh/constraintsissue.git

**Comment by graemerocher** [comment]
This appears to be a bug in Grails 2.5.x and can't be fixed in GORM itself. The problem doesn't occur in Grails 3.x
