### ISSUE TITLE
New plugin seems to require and explicit flush:true or data never arrives in database

### ISSUE THREAD

**Issue by mlentzner** [grails/grails-data-mapping#690]
Simple controller action call to `<domain object>.save()` does not persist object to database.

All calls must be explicit call `<domain object>.save(flush: true)`

**Comment by mlentzner** [comment]
public gh repo at mlentzner/grails-issues

Comment: //MongoDB Plugin issue #690 - remove flush:true and object is never persisted

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/481f7f4602b8c85bada5ae12ab963ba153595b7e

**Comment by mlentzner** [comment]
Confirmed fixed. Thanks!
