### ISSUE TITLE
Adding default constraints to application.groovy causes any class that has static column mappings throw an exception at startup

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-data-mapping#695]
Grails **3.1.4**  Gorm >= **5.0.4**

Please see the following link for a fully documented example: 

https://github.com/codeconsole/grails3bugs

modified generated **application.groovy** (Creates **BUG #1** requires Gorm **5.0.4**)

	grails.gorm.default.constraints = { 
 	   '*'(nullable: true) 
	} 

domain class:

	static mapping = {
		password column: '`password`'
	}

	... nested exception is org.hibernate.MappingException: Repeated column in mapping for entity: example.User column: password (should be mapped with insert="false" update="false")
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)

**Comment by codeconsole** [comment]
https://github.com/grails/grails-data-mapping/issues/671

**Comment by codeconsole** [comment]
Updated https://github.com/codeconsole/grails3bugs to demonstrate the bugs still exist in Grails 3.1.5

**Comment by graemerocher** [comment]
Duplicates #702

**Comment by codeconsole** [comment]
@graemerocher #702 was created 3 days after this issue and duplicated me!  
:P

**Comment by graemerocher** [comment]
@codeconsole yeah I know, but I spotted and closed the other one first, thanks for the reports!
