### ISSUE TITLE
HibernateDatastoreSpringInitializer ignores hibernate parameters

### ISSUE THREAD

**Issue by vforchi** [grails/grails-data-mapping#698]
I'm trying to port my application from GORM3 to GORM5, and I think HibernateDatastoreSpringInitializer does not take into account the hibernate parameters I define in the environment.

I tried many scenarios, the simplest one being the one described in https://grails.github.io/grails-data-mapping/latest/hibernate/manual/guide/gettingStarted.html#springBoot (although the query does not work outside a service):

```
def initializer = new HibernateDatastoreSpringInitializer(['hibernate.log_sql':'true'], Person)
def applicationContext = initializer.configureForDataSource(dataSource)
println Person.findAll().size()
```

It all boils down to HibernateDatastoreSpringInitializer:149
`def hibConfig = config.getProperty("hibernate$suffix", Map, Collections.emptyMap())`

which returns an empty Map, although `config.getProperty("hibernate.log_sql") == true`

Is this a bug or am I misinterpreting the code and I'm doing something wrong?

Note: in GORM3 that line was:
`def hibConfig = configurationObject["hibernate$suffix"] ?: configurationObject["hibernate"]`
and this returns the expected Map

**Comment by graemerocher** [comment]
Use 

      def initializer = new HibernateDatastoreSpringInitializer([hibernate:[log_sql':'true']], Person)

**Comment by vforchi** [comment]
Thanks, that works if I initialize with the Map, which I use in some unit tests.

In the application I use the spring boot plugin, and if I define the properties in application.properties I have the same proplem (they are not configured, although config.getProperty returns the proper value)

My application.properties looks something like this:
```
hibernate.cache.use_second_level_cache=false
hibernate.dialect=org.hibernate.dialect.SybaseASE15Dialect
```

**Comment by graemerocher** [comment]
Fixed as part of commit https://github.com/grails/grails-data-mapping/commit/641f6ccc33fcc00013e249dc703add8131e638fa#diff-b21926befc8660d40887bc51a455b403R95

**Comment by vforchi** [comment]
Hi Graeme,
I tested the latest version, but I still have the same behaviour.
If I put those parameters in a file named hibernate.properties it works, but I still have this [problem](https://github.com/grails/grails-data-mapping/issues/551) with hbm2ddl. As a workaround I have to override HibernateGormAutoConfiguration and set ddlAuto to "", but it's far from optimal.

**Comment by graemerocher** [comment]
have you tried setting `hbm2ddl` to `none`?

**Comment by vforchi** [comment]
Yes, but I get a warning *after* it tries to perform the update.

```
12:33:00.772 [main] INFO  org.eso.phase3.IngestionTool - No active profile set, falling back to default profiles: default
12:33:14.609 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 7218, SQLState: ZZZZZ
12:33:14.612 [main] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - Site 'my_schema' not found in sysservers.
12:33:14.616 [main] ERROR o.h.tool.hbm2ddl.SchemaUpdate - HHH000299: Could not complete schema update
java.lang.NullPointerException: null
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
<cut>
12:33:15.222 [main] WARN  org.hibernate.cfg.SettingsFactory - Unrecognized value for "hibernate.hbm2ddl.auto": none
```
