### ISSUE TITLE
Abstract base class inheritance with MongoDB

### ISSUE THREAD

**Issue by marcDeSantis** [grails/grails-data-mapping#701]
Using hibernate, I can extend an abstract base class in a domain object, inheriting its `beforeInsert` and `beforeUpdate` methods (to set date and other audit columns, for example). Using this same pattern in Mongo allows the properties to be inherited from the base class, but the before methods are not executed.

**Comment by marcDeSantis** [comment]
This appears to work fine in Grails 2.5, but it does not work in Grails 3.1.4

Perhaps related to #699 ?

**Comment by graemerocher** [comment]
Quite possibly, will take a look... thanks

**Comment by graemerocher** [comment]
I cannot reproduce this, see the test at https://github.com/grails/grails-data-mapping/commit/64e4c556f4ba632a5e9dd08ca2ac4ae07bc97ce6

If you upload an example that reproduces the problem I am happy to re-open the issue.
