### ISSUE TITLE
Add support for Java 8 Date Time Library

### ISSUE THREAD

**Issue by edwardotis** [grails/grails-data-mapping#704]
Use of Date should be replaced by OffsetDateTime for database use

http://www.oracle.com/technetwork/articles/java/jf14-date-time-2125367.html
https://docs.oracle.com/javase/tutorial/datetime/iso/legacy.html

Classes like org.grails.datastore.gorm.timestamp.DefaultTimestampProvider break on the Java 8 replacement classes.

This in turn breaks Automatic Timestamping feature in grails 2.x

OffsetDateTime dateCreated = OffsetDateTime.now(ZoneId.of("UTC"))

| Error 2016-04-16 13:26:46,770 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Could not find matching constructor for: java.time.OffsetDateTime(java.lang.Long)
Message: Could not find matching constructor for: java.time.OffsetDateTime(java.lang.Long)
    Line | Method
->>   54 | createTimestamp                  in org.grails.datastore.gorm.timestamp.DefaultTimestampProvider

**Comment by jameskleeh** [comment]
Fixed in GORM 6.0.1
