### ISSUE TITLE
[Neo4j] Neo4jDatastore is using deprecated code

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#722]
In lines 181 to 183 of Neo4jDatastore.java, it's calling to GraphDatabaseSettings.cache_type which is deprecated for Neo4j 2.3+
This code should be removed.

```        if(!dbProperties.containsKey(GraphDatabaseSettings.cache_type.name())) {
            graphDatabaseBuilder.setConfig(GraphDatabaseSettings.cache_type, "soft");
        }```

**Comment by graemerocher** [comment]
This is fixed following the refactor for Neo4j 3
