### ISSUE TITLE
Inheritance in classes with MONGO DB with Hibernate maps classes to mongo instead of hibernate

### ISSUE THREAD

**Issue by mehtaabhishek** [grails/grails-data-mapping#728]
I have grails app created using 3.1.4, Hibernate5 & MongoDB plugin 5.0.7

I have two domain classes as below

class Book {
String name
String author
static constraints = {
}

static mapping = {
    tablePerHierarchy(false)
    id generator: 'sequence', params: [sequence: 'PK_BOOK_SEQ']

}
}

Its child class

class FoodBook extends Book{
String category
static constraints = {
}
}

Now when i start my app & try to do criteria query as below the application comes up successfully.
Long maxId = Book.createCriteria().get { projections { max "id" } }

But when I add more domain classes to this application it start failing.

import org.hibernate.type.LocaleType
class MetaDataLabel {
    Locale locale
    String value
    static mapping = {
        locale type: LocaleType
        id generator:'sequence', params:[sequence:'meta_data_label_id_seq']
    }
}

-------

import org.hibernate.type.LocaleType
class MetaDataDescription {
    Locale locale
    String value
    static mapping = {
        locale type: LocaleType
        id generator:'sequence', params:[sequence:'meta_data_description_id_seq']
    }
}

-----

class Institution implements Serializable{
    static mapping = {
        id generator:'sequence', params:[sequence:'institution_id_seq']
    }
}

-----

I got the below stack trace as it fails on createCriteria query. All the domain objects are hibernate objects. The institution object not even get printed.

Class:class cgw_sample.FoodBook
sessionFactory.getClassMetadata(it):GroovyAwareJoinedSubclassEntityPersister(cgw_sample.FoodBook)
tableName:food_book
Max ID ******:null
Class:class cgw_sample.MetaDataDescription
sessionFactory.getClassMetadata(it):GroovyAwareSingleTableEntityPersister(cgw_sample.MetaDataDescription)
tableName:meta_data_description
Max ID ******:null
Class:class cgw_sample.MetaDataLabel
sessionFactory.getClassMetadata(it):GroovyAwareSingleTableEntityPersister(cgw_sample.MetaDataLabel)
tableName:meta_data_label
Max ID ******:null
Class:class cgw_sample.Book
sessionFactory.getClassMetadata(it):GroovyAwareJoinedSubclassEntityPersister(cgw_sample.Book)
tableName:book
ERROR org.springframework.boot.SpringApplication - Application startup failed
org.springframework.dao.InvalidDataAccessResourceUsageException: Attempt to project on a non-existent project [id]
	at org.grails.datastore.mapping.mongo.query.MongoQuery.executeQuery(MongoQuery.java:936)
	at org.grails.datastore.mapping.query.Query.list(Query.java:567)
	at org.grails.datastore.mapping.query.Query.singleResult(Query.java:585)
	at grails.gorm.CriteriaBuilder.get(CriteriaBuilder.java:297)
	at org.grails.datastore.mapping.query.api.BuildableCriteria$get.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.grails.datastore.mapping.query.api.BuildableCriteria$get.call(Unknown Source)
	at edu.wustl.cgw.service.OracleDatabaseSequenceService$_resetSequence_closure1.doCall(OracleDatabaseSequenceService.groovy:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)

According to https://github.com/grails/grails-data-mapping/issues/712 it is resolved but it looks like the issue still exist.

I have tried following things to verify if the domain objects defined are correct or not. It looks like the domain object defined are correct. Below table shows how the domain objects are added in the project and application status after adding the domain classes.

Domain Object Added	Application Status
Book, FoodBook, Institution	UP
Book, FoodBook, Institution, MetaDataDescription	UP
Book, FoodBook, Institution, MetaDataDescription, MetaDataLabel	FAILED
Book, FoodBook, MetaDataDescription, MetaDataLabel	 UP
Book, FoodBook, Institution, MetaDataLabel	UP
Book, FoodBook, MetaDataDescription, MetaDataLabel, Institution	FAILED

**Comment by graemerocher** [comment]
You will need to upload an example that reproduces the issue please

**Comment by mehtaabhishek** [comment]
Added sample application https://github.com/mehtaabhishek/Issue728
