### ISSUE TITLE
Grails plugin listing outdated

### ISSUE THREAD

**Issue by martyychang** [grails/grails-data-mapping#731]
The [Grails plugin site](https://grails.org/plugin/mongodb) lists the plugin as having "Latest: 5.0.0.RC1", when in reality the [most recent release is v5.0.8](https://github.com/grails/grails-data-mapping/releases/tag/v5.0.8).

**Comment by graemerocher** [comment]
that is for Grails 2, the Grails 3 site lists the right version https://grails.org/plugins.html#plugin/mongodb

**Comment by martyychang** [comment]
Oh fascinating. Those URLs are kinda confusing. Thanks for that info, @graemerocher . I presume this means the last Grails 2-compatible release of GORM for MongoDB was **5.0.0.RC1**, then?

**Comment by graemerocher** [comment]
no, I'm just saying that only the Grails 2 portal is out of date ;-) 5.0.8 is also usable in Grails 2

**Comment by martyychang** [comment]
Good to know, @graemerocher and thanks again. By the way FYI the Grails 2 portal says to look for Grails 3 plugins on Bintray: https://bintray.com/grails/plugins

My $0.02: if the Grails 2 portal is out of date perhaps it should be retired, or force a redirect to the Grails 3 portal. Especially since there are Grails 3 plugins listed (e.g., GORM for MongoDB 5.0.8) that are actually compatible with Grails 2.
