### ISSUE TITLE
No effect on setting failOnError in application.yml with MONGO DB plugin 5.0.8

### ISSUE THREAD

**Issue by dreampursuer** [grails/grails-data-mapping#734]
I have grails app created using 3.1.8, MongoDB plugin 5.0.8 without Hibernate plugin.
I use the following setting in application.yml for mongodb:
<pre>
grails:
    gorm:
        failOnError: true
---

grails:
    mongodb:
        host: "xxx"
        port: 27018
        databaseName: "xxx"
---
</pre>

There's no exception thrown when call domainInstance.save() on bad data.
But it works fine on calling domainInstance.save(failOnError:true).

It seems like it caused by removing the doWithDynamicMethods in MongodbGrailsPlugin.groovy on MONGO DB plugin 5.x version.

**Comment by jeffbrown** [comment]
I have not setup an environment to verify the details but I recently was told that this setting was also not working for Hibernate when using GORM5 in a Grails 2.5.4 application.

**Comment by dreampursuer** [comment]
The change was made at the selected version:
![default](https://cloud.githubusercontent.com/assets/2177130/16184006/3ffbc248-36eb-11e6-98ac-7ffffa546791.png)

There's a failOnError property in GormEnhancer( or MongoGormEnhancer) class but did not set the value from config by "grails.gorm.failOnError".

The 4.x plugin will set the value by config as the following codes described:
methodsConfigurer.failOnError = config.getProperty('grails.gorm.failOnError', Boolean, false)

**Comment by graemerocher** [comment]
Found the issue in MongoDB, seems to work fine in Hibernate
