### ISSUE TITLE
MissingPropertyException for class: HibernateMappingBuilder

### ISSUE THREAD

**Issue by RNiesler** [grails/grails-data-mapping#735]
When using a closure from static field in constraints, MissingProperty exception is thrown from HibernateMappingBuilder. For example: 
```
class Activity {
    static constraints = {
        name(validator: validatorClosure)
    }

    String name

    static validatorClosure = { String name, Activity activity ->
        return true
    }
}
```
Grails version is 3.1.8, GORM 5.0.8. Full example here: https://github.com/RNiesler/grails-sandbox/blob/validator-problem/grails-app/domain/rniesler/impact4270/Activity.groovy

**Comment by jeffbrown** [comment]
Does the following work?


    static constraints = {
        name(validator: Activity.validatorClosure)
    }

**Comment by jeffbrown** [comment]
https://github.com/grails/grails-core/blob/v3.1.8/grails-validation/src/main/groovy/org/grails/validation/DefaultConstraintEvaluator.java#L237 sets the `resolveStrategy` to `DELEGATE_ONLY` so your reference to `validatorClosure` is problematic.

**Comment by RNiesler** [comment]
Yes, the workaround works. When I was debugging before and changed the ''resolveStrategy'' to take the owner into account it works as well. Anyway it worked in the previous version (4.0.7) of GORM.

**Comment by jeffbrown** [comment]
Setting the resolve strategy only to owner is going to cause other problems.  It needs to be either `DELEGATE_ONLY`, `DELEGATE_FIRST` or `OWNER_FIRST`.  `OWNER_ONLY` would cause problems.

**Comment by graemerocher** [comment]
This won't be fixed, there are too many other issues which can cause conflicts. Also https://issues.apache.org/jira/browse/GROOVY-7866 is blocking to allow the resolve strategy to be anything other than `DELEGATE_ONLY`
