### ISSUE TITLE
One to One Relationship with Hibernate5 does not work

### ISSUE THREAD

**Issue by Macros1977** [grails/grails-data-mapping#736]
There seems to be an issue with one to one mappings within hibernate 5.

If I have two simple domain classes Foo :

class Foo {

    String fooDesc

    Bar bar

    static mapping = {
        id generator:'identity'
    }

    static constraints = {
       bar(nullable: true)
    }
}

and Bar:

class Bar {

    String barDesc

    static belongsTo = [ foo: Foo ]

    static mapping = {
        id generator:'identity'
    }

    static constraints = {
    }
}

Looking up the Bar entities from Foo will work, however, looking up the Foo entities from Bar will return the Foo entries with the same ids as the corresponding Bar Ids.

So for instance, my data looks like this: 

Foo contains:

"id"	"version"	"bar_id"	"foo_desc"
"1"	"0"	"2"	"foo 1"
"2"	"0"	"3"	"foo 2"
"3"	"0"	"1"	"foo 3"

and Bar contains:

"id"	"version"	"bar_desc"
"1"	"0"	"bar 3"
"2"	"0"	"bar 1"
"3"	"0"	"bar 2"

Running the following code:

        def foos = Foo.findAll()
        log.info("Foos:")
        foos.each{ f ->
            log.info(f.fooDesc + " -> " + f.bar.barDesc)
        }

        def bars = Bar.findAll()
        log.info("Bars:")
        bars.each{ b ->
            log.info(b.barDesc + " -> " + b.foo.fooDesc)
        }

Will produce:

 Foos:
 foo 1 -> bar 1
 foo 2 -> bar 2
 foo 3 -> bar 3
 Bars:
 bar 3 -> foo 1
 bar 1 -> foo 2
 bar 2 -> foo 3

**Comment by graemerocher** [comment]
Although we have other tests for this I added another one anyway https://github.com/grails/grails-data-mapping/commit/c34b429f43a2e271f6859277bd58e7944fbc3ec4

Seems to behave as expected for me. Please upload an example that reproduces the problem.

**Comment by Macros1977** [comment]
Please see https://github.com/Macros1977/grailstest

I'm running on Wildfly 10 using Java 8

**Comment by graemerocher** [comment]
Where is the code that reproduces the issue in that example?

**Comment by Macros1977** [comment]
The project here: https://github.com/Macros1977/grailstest is a small grails app containing both those domain classes and a controller.

If I build a WAR using that, deploy it on Wildfly 10 and visit http://localhost:8080/grailstest-0.1/test/index it will print out the values as per the above example.

I've added a mysql script to create the database and tables.

**Comment by graemerocher** [comment]
Your `bar` table has no `foo_id` column, so I don't see how this would work anyway.

**Comment by Macros1977** [comment]
The bar table doesn't need a foo_id as long as the foo table has a bar_id. As a matter of fact, if you were to set your datasource dbCreate to create, that is the structure that hibernate will create for you.

**Comment by Macros1977** [comment]
Also, just to confirm, this issue only happens with Hibernate 5, if you were to update your build.gradle to point back to Hibernate 4 and leave everything else the same it works as expected.

**Comment by graemerocher** [comment]
Thanks for the feedback and the report.
