### ISSUE TITLE
Feature request: Default mapping config per datasource

### ISSUE THREAD

**Issue by mjcmatrix** [grails/grails-data-mapping#741]
GORM has support for sharing default mappings across all entities. These are configurable as `grails.gorm.default.mapping`.

The scope of shared mappings is actually the datasource in many applications. Datasources may need different common mappings for their tables (such as identity and naming strategy). Mappings can also vary by environment (e.g. H2 <-> PostgreSQL. These require different settings for UUID identity mapping). It would be helpful if shared mappings could be defined with the datasource scope, rather than globally (or in addition).

Example:
```
production {
    grails.gorm.default.mapping = {
        id(generator: 'assigned', type: "pg-uuid") // PostgreSQL
    }
}
development {
    grails.gorm.default.mapping = {
        id(generator: 'assigned', type: "uuid-binary") // H2
    }
}
```
In production environment, `pg-uuid` might be the required ID strategy for both default and secondary datasource(s), but in development mode, the default database is probably H2 but the secondary datasource(s) could still be PostgreSQL (especially read-only / lookup datasources), requiring different common mappings per datasource.

The current workaround is to declare the most common default mappings and override these mappings on every mapped entity within secondary datasources. This is an option where the overridden mappings apply to all environment modes.

**Comment by graemerocher** [comment]
This is possible in GORM 6 with `dataSource.default.mapping`. You can replace `dataSource` without whatever other data source you are using. eg. `myDataSource.default.mapping`
