### ISSUE TITLE
Constraint 'nullable: false' in domain classes is ignored when the default setting is: 'nullable: true' in 'application.groovy'

### ISSUE THREAD

**Issue by maria-leotech** [grails/grails-data-mapping#746]
Constraint `nullable: false` in domain classes is ignored when we set 
`grails.gorm.default.constraints = { '*'(nullable: true) }` in `application.groovy`

Steps to reproduce that:

1. Delete changelog.groovy
2. grails dbm-drop-all
3. Make the changes as described above 
4. grails dbm-generate-gorm-changelog changelog.groovy

Open `changelog.groovy`: Instead of seeing a column, e.g. 

`(name: "my_column", type: "VARCHAR(255)") {
 	constraints(nullable: "false")
 }`

where is defined in a domain class and as a constraint:
`String my_column`

`static constraints = {
	my_column nullable: false
}`

I see a nullable (i.e. without a constraint that states otherwise) field in changelog

My system runs:

|Grails Version: 3.1.8
|Groovy Version: 2.4.6
|JVM Version: 1.8.0_31

**Comment by burtbeckwith** [comment]
A simpler way to view the configured constraints is by running `grails schema-export` which generates a `ddl.sql` file in the `build` directory.
