### ISSUE TITLE
Multitenancy - No Session found for current thread - with SubDomainTenantResolver

### ISSUE THREAD

**Issue by snimavat** [grails/grails-data-mapping#750]
I am using org.grails.datastore.mapping.multitenancy.web.SubDomainTenantResolver

And i have two domains configured in my hosts file as 

127.0.0.1 test.com
127.0.0.1  sub.test.com

I have two corrosponding datasources configured

I have a very simple controller, that just creates and saves a new book record.

Now when i try to access the controller using any of the domain (test.com:8080/book/save or sub.test.com:8080/book/save), i get the error `No Session found for current thread`

I read the docs, which says

> When working with GORM typically you need a session bound to the current thread in order for GORM and transactions to work consistently. If you switch to a different tenant then it may be that the session bound to the current thread no longer matches the underlying SessionFactory being used by the tenant. With this in mind you may wants to use the Tenants class to ensure the correct session is bound for the current tenant:

```
withCurrent {
  new Book(name: "xx").save()
}
```

However shouldnt that be required only if I use some thing like SessionTenantResolver and switch the tenant manually at run time ?

Does the above exception mean, all the MultiTenant domains operation has to be always executed within the `withCurrent {}` closure.

I would expect that proper session is bound to thread, unless i am changing the tenant explicitely (after its resolved by the configured TenantResolver)

@graemerocher

**Comment by graemerocher** [comment]
you have to always wrap the logic in `withCurrent`, in the future we plan to make this easier with an `@Tenant` transformation, but that is not implemented yet

The session that is bound to the thread is always for the default data source and there is no specific handling that can know what domain class you plan to use ahead of time

**Comment by graemerocher** [comment]
See https://github.com/grails/gorm-hibernate5/blob/master/examples/grails31-database-per-tenant/grails-app/controllers/example/BookController.groovy for an example

**Comment by snimavat** [comment]
Thanks for confirming .. Annotation would be a great relief.

**Comment by graemerocher** [comment]
Agreed, add a `@Tenant` transformation is on the roadmap

**Comment by snimavat** [comment]
Or may be, when a tenant is resolved by TenantResolver, the session factory for that tenant is set as default for that request thread, and if i want to use another tenant then the one which is resolved, i have to use the ```withId {}```

Generally speaking, when a tenant is resolved, most of the time app will want to use that datasource as default for the given request, but if there are some domains which are in another tenant/default datasource, i would just do withId for those domains only, rather then doing withTenant {} for every thing.

**Comment by graemerocher** [comment]
That is not possible, because you need to know at what point that session should be closed and disconnected otherwise you would leak connections. You need  clear boundaries, hence `withCurrent` and the potential future `Tenant` transformation

**Comment by snimavat** [comment]
Ok, you understand it better then me, but i am thinking why cant that work. As i understand, the session for default datastore is created and attached to current thread when the request is received.
With what i suggested above, instead that session would be from the session factory resolved for the current tenant... and whenever I want to use another tenant then the one resolved, i can use ```withId(xx) {}`` - that will set the session for the specified tenant for the given thread, and at the end of ```withId{}``` the session would be closed, just like how it would be doing currently.. probably.

hope to not speaking something nonesense..

**Comment by graemerocher** [comment]
because not every request is multi tenant, not every controller is multi tenant and not every domain class is multi tenant so you would still have to say which controllers are multi tenant and which are not. 

In your case the tenant id is the subdomain so it is always known, but that may not always be the case. For example the tenant may be resolved from the currently logged in user, and for that you need to expose a login page without the tenant id resolution.

**Comment by snimavat** [comment]
Ok, i understand, what i suggested may not suite for all applications. 
But lets say, i have a multitenant app, and have a DomainTenantResolver, each tenant has its own full domain. And i want to make it such that the default session bound for the request thread is from the SessionFactory resolved for the tenant and not the default datastore. What would be the right approch to do this, may be some thing like OpenSessionInViewInterceptor ? but instead it will create the session for the resolved tenant, and not the default.. any suggestions on the right approach ?

**Comment by graemerocher** [comment]
Then the solution is that your default database is the "main" tenant and your tenant resolve should return `ConnectionSource.DEFAULT` for the default tenant

**Comment by snimavat** [comment]
@graemerocher i tried to grab your attenion over my question on slack, but couldnt get an answer. So posting it here... can you clarify it here, it may help others as well..

As we have multiple session factories now..
I m trying to test almost same thing as this question - 

http://stackoverflow.com/questions/8700160/spring-hibernatetransactionmanager-handling-multiple-datasources

Trying to get my head over the multitenancy before i start using it on the real project. 
I Was doing a test for @Transactional and see how it works with multitenancy

https://gist.github.com/snimavat/64dc275f44b5f3e26063020802cf72c6

So, i have two domains, Book and Author, Book implements MultiTenant Trait, but Author does not.
If you look at the above gist, the service throws the exception at the end of the method to trigger rollback.

Now what is confusing me is,  rollback is being applied to both of the domains, i thought the rollback would apply to just the domain which is bound to default datasource, as TransactionManager would be using the default datasource (session factory). It dint change even if I do Tenants.withCurrent {}.. Hows does that happen even when there's no JTA transaction manager ?

So.. what is the semantics of transaction, or Transactional annotation.. when MultiTenant and non MultiTeanant domain operations are mixed in a transaction ?

**Comment by graemerocher** [comment]
There `@Transactional` annotation currently always uses the default connection / session factory and there is not yet any interaction between it and Multi tenancy, we have plans in the future to add multi tenant transforms but these are probably beyond the scope of 6.0

In the meantime you should remove any `@Transactional` annotations are use `withCurrent` etc.

**Comment by graemerocher** [comment]
Relates to / duplicated by #767

**Comment by goeh** [comment]
Ok I understand. But it's a major limitation because I might not know what other service calls my code will trigger, and those services might use @Transactional. I will replace @Transactional with withCurrent and see how it goes. Thanks.
