### ISSUE TITLE
Persistence of an object withing an afterInsert method doesn't work.

### ISSUE THREAD

**Issue by fsogni** [grails/grails-data-mapping#758]
I have a domain class call Permission. Every time a permission is created or updated I want to create and entry in the database (sybase 16), recording some properties of the permission object (delegator, permission, resource, etc.) 
The afterUpdate works fine and I see entries in the audit table, the afterInsert doesn't. This is my method:

 def afterInsert = {

        if (Environment.current != Environment.TEST) {
            //create a new session to force the save of the object
                AceHistoryEvent.withNewSession {
                    AceHistoryEvent auditEvent = new AceHistoryEvent()
                    auditEvent.who = delegator
                    auditEvent.action = EActionType.PermissionGranted
                    auditEvent.permission = this
                    def permissionId = this.id
                    println "Saving audit for permission ${this.id}"
                    if (!user) {
                        //we are delegating to a group
                        auditEvent.delegateGroup = group
                    } else {
                        //we are delegating to a user
                        auditEvent.delegateUser = user
                    }
                    auditEvent.resource = resource
                    auditEvent.date = new Date()
                    auditEvent.save(failOnError: true)
                    println "Audit line saved with id ${auditEvent.id}"
                }
        println "Audit saved for permission ${this.id}"
        }
    }

In the logs i see lines like:
"Saving audit for permission 6566"
"Audit line saved with id 13545"
"Audit saved for permission 6566"

It seems everything is fine, but in the database there is no track of this line and no exception is thrown.
I'm using grails 2.5.0

**Comment by graemerocher** [comment]
Please upgrade to a the latest versions of GORM 5 and if the problem persists upload an example that reproduces the issue

**Comment by fsogni** [comment]
Unfortunately we are not allowed (yet) to move to grails 3.1.x 
We moved in the mean time to grails 2.5.5 and the problem persists. Should I upload an example anyway?

**Comment by graemerocher** [comment]
you don't need Grails 3.1.x to use GORM 5
