### ISSUE TITLE
TypeMismatchException: while using refersh method with inheritance (upgrading from 4.0.7 to 5.0.10)

### ISSUE THREAD

**Issue by liorhson** [grails/grails-data-mapping#759]
Hey,

We are using **org.grails.plugins:mongodb:5.0.10** with the latest grails core version.
This issue started after upgrading from 4.0.7

Considering Gorm domains:
``
class A {}
``
``
class B extend A {}
``
``
class X {
  A myMember
}
``
``
class Y extends X {}
``
``
Y.myMember = new B()
``

While using the refresh method **Y.refresh()**, the following exception happens:

> org.springframework.beans.TypeMismatchException:
 Failed to convert property value of type [**A**] to required type [**A**] for property '**myMember**'; nested exception is org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'null' with class '**A**' to class '**B**'

Regards,
Jfrog

**Comment by graemerocher** [comment]
Please provide an example that reproduces this issue.
