### ISSUE TITLE
Generated setters in domain classes calls markDirty() multiple times

### ISSUE THREAD

**Issue by goeh** [grails/grails-data-mapping#764]
I was decompiling a Grails 3.2.0.M2 domain class with JD-GUI and noticed that markDirty() is called three times in each setter.

**Steps to reproduce**
1. grails create-app foo
2. cd foo
3. grails create-domain-class foo.Person
4. Add a String property to the domain class
5. ./gradlew build
6. Use a decompiler like JD-GUI to look at the generated class file (Person.class). The setter for the domain property contains three calls to markDirty() after each other.

```
public void setFirstName(String firstName)
{
  markDirty("firstName", firstName);
  null;
  markDirty("firstName", firstName);
  null;
  markDirty("firstName", firstName);
  null;
  String str = firstName;
  this.firstName = str;
}
```

I suspect that `DirtyCheckingTransformer` visits the setter method multiple times and is missing a check that is has already done the job, but I'm not sure.

Test application here: https://github.com/goeh/grails-mark-dirty-issue

**Comment by graemerocher** [comment]
Fix for this issue as the same as the fix for #761
