### ISSUE TITLE
multi tenancy flappy as soon as you change EhCacheRegionFactory

### ISSUE THREAD

**Issue by kiteflo** [grails/grails-data-mapping#778]
Hi,

[Grails 3.2, Gorm 6]

we are banging our heads against walls. Enabling schema based multi tenancy via application.yml results in the exception below:

Caused by: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: DefaultConfigurationSource [ ehcache.xml or ehcache-failsafe.xml ]
    at net.sf.ehcache.CacheManager.assertNoCacheManagerExistsWithSameName(CacheManager.java:628)
    at net.sf.ehcache.CacheManager.init(CacheManager.java:392)
    at net.sf.ehcache.CacheManager.<init>(CacheManager.java:270)
    at org.hibernate.cache.ehcache.EhCacheRegionFactory.start(EhCacheRegionFactory.java:69)
    ... 82 common frames omitted

we came across a fix for this one and it was recommended to simply use SingletonEhCacheRegionFactory instead of EhCacheRegionFactory which is what we did. The server now comes up as expected...

**BUT**

Now multi tenancy results in total flappy behavior in terms of continuously writing to the wrong database schema instead of using current tenant's schema. We pretty much feel this is related to the "EhCache-Fix".

Could anybody please help us in order to make the server booting up again by using a recommended fix instead of just exchanging things like EhCacheRegion without knowing the consequences?

Thanx in advance,
Florian

**Comment by graemerocher** [comment]
Sure, please provide an example that reproduces the behaviour and we can take a look

**Comment by kiteflo** [comment]
hi graeme,

actually we made progress (will share our findings as soon as we have everything up&running...).

Right now we are facing the issue that DATABASE multi tenancy is basically working. But as soon as we start using "findBy..." methods the wrong database is connected and not the database of the corresponding tenant.

Using simple XY.get(id) works.

Is findBy... currently not supported in combination with multi tenancy?

**Comment by kiteflo** [comment]
ok...it's me again...it looks like de default datasource is always tied in as soon as we use findBy...

which brings us back to our basic suspicion that something with this ehcache is going wrong.

So we created a little demo project with a grails 3.2 multi tenant default configuration and which causes the exception listed above during startup.

Can you please help with this issue as we are afraid all this "wrong database being tied..." stuff somehow is related to this caching issue?

sources can be found here:

git@github.com:kiteflo/ehcache.git

thanx in advance,
Florian

**Comment by graemerocher** [comment]
Thanks for the report, we will look into this.

**Comment by graemerocher** [comment]
So changing to `SingletonEhCacheRegionFactory` fixes the startup issue. How do I reproduce the "flappiness" you refer to with this sample app?

**Comment by kiteflo** [comment]
Hi Graeme,

we just re-created the repository and put a clean project with some descriptions into the repository:

https://github.com/kiteflo/ehcache

In the MongoController you can find a method called test() as well as a very quick description of the flappy behavior. 

If you simply delete/pull the repository again you should have a clean test case and clean description.

Thanx for your help in advance, as already said, currently we are only guessing and maybe in the end it turns out the ehache configuration has nothing to do with the flappyness. But any hint/help what's going wrong with our scenario is highly appreciated...

thanx a lot, best regards from Switzerland,
Florian

**Comment by graemerocher** [comment]
Thanks will take a look

**Comment by graemerocher** [comment]
This was not related to ehcache, but was a bug in the registration of dynamic finders. Fixed by https://github.com/grails/gorm-hibernate5/commit/de325a3f045a5731d8c9d8a8467a2ad2d6b64366

**Comment by kiteflo** [comment]
hi Graeme,

thanx for fixing this one - quick question: can you create a new RC with this fix? Currently we are entirely blocked :(

Snapshot repository would work as well...

thanx,
Florian

**Comment by graemerocher** [comment]
just use `3.2.0.BUILD-SNAPSHOT` by following these instructions http://grails.io/post/143431711043/how-to-use-a-specific-version-of-gorm-in-grails-3

Note that the issue only impacts dynamic finders, if you replace the query with a `where` query it works fine.

A new RC will be out in a couple of weeks.
