### ISSUE TITLE
Using MongoDB Driver Directly is not Working like Docs

### ISSUE THREAD

**Issue by caiocmpaes** [grails/grails-data-mapping#779]
## I am having trouble to use low-level API as It is in the Docs.

The documentation section [Using MongoDB Driver Directly](http://gorm.grails.org/latest/mongodb/manual/index.html#lowLevelApi) shows the use of the low level API with a direct access to the collection objects. However, I'm getting a "No Such Property X for class com.mongodb.MongoDatabaseImpl" error.

```
// Get a db reference in the old fashion way
def db = mongo.getDatabase("mydb")

// Insert a document
db.languages.insert([name: 'Groovy'])
// A less verbose way to do it
db.languages.insert(name: 'Ruby')
// Yet another way
db.languages << [name: 'Python']
```

I am using the plugin with version 5.0.0.RC1.
Is the documentation outdated (Because you removed Gmongo support)? Or I forgot some configuration?

**Comment by graemerocher** [comment]
Please upgrade to a newer version of the plugin try again

**Comment by caiocmpaes** [comment]
I've updated to version 6.0.0.RC1 and the API is still not working. It only works when I use `mongo.getDatabase('mydb').getCollection('collname')`.

I am using grails 2.5.5 and my BuildConfig is looks like this:
```
...
    dependencies {
		compile 'org.grails:grails-datastore-gorm:6.0.0.RC1'
		compile 'org.grails:grails-datastore-core:6.0.0.RC1'
        compile 'org.springframework:spring-aop:4.0.5.RELEASE'
        
        test 'org.grails:grails-datastore-simple:6.0.0.RC1'
    }

    plugins {
        build ":tomcat:7.0.52.1"
        compile ":mongodb:6.0.0.RC1"
        compile ":scaffolding:2.1.2"
	compile ":google-visualization:0.6.2"
        ...
    }
```

I am just trying to understand if I'm making some mistake on my configurations. As a quickfix I adding GMongo jar to my classpath and passing the `mongo` reference to Its constructor. It is working with the external GMongo. Without GMongo, the shell way doesn't work.

**Comment by rkimaoui** [comment]
Hello,
Which Gmongo version do you use ?
I can't make it work with: Grails 3.1.11 and mongodb:5.0.10 and com.gmongo:gmongo:1.5

**Comment by caiocmpaes** [comment]
That was tricky, @rkimaoui . In GMongo's GitHub repository the author registered only until release 1.2 ([poati/gmongo/releases](https://github.com/poiati/gmongo/releases)). Most recent versions are available in maven repository ([Maven Repository - GMongo](http://repo1.maven.org/maven2/com/gmongo/gmongo/))

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/gorm-mongodb/commit/d0876aa8a4f17b7f3a95707c71ceb365d57fe82b
