### ISSUE TITLE
How to create sub query to joined tables

### ISSUE THREAD

**Issue by keizo2** [grails/grails-data-mapping#781]
Grails version 3.2.0.M2

I made models like these
```
class Sales {

    String custName
    static hasMany = [salesDetail: SalesDetail]
    static constraints = {
    }
}

class SalesDetail {

    int price
    Item item
    static belongsTo = [sales: Salse]

    static constraints = {
    }
}

class Item {

    String name
    static constraints = {
    }
}
```
I want to retreive data from joined models with sub query, and
limit on Sales. Like below SQL.
```
select * from sales s1 
where exists (
select s2.id from sales s2 
inner join sales_details sd on s2.id = sd.sales_id 
inner join item i on sd.item_id = i.id where s1.id = s2.id)
where i.name = 'book'  // search conditions on Sales, SalesDetails, or Item
limit 10; // limit Sales 
```
I read 
http://gorm.grails.org/6.0.x/hibernate/manual/#detachedCriteria,
but I don't know how to create like above query.
Where can I find hint or examples?

**Comment by jeffbrown** [comment]
The issue tracker is for bug reports and feature requests.  Please ask questions on the mailing list at https://groups.google.com/forum/#!forum/grails-dev-discuss or in our Slack channel at http://grails.slack.com/.

Thanks!

**Comment by keizo2** [comment]
I'm sorry. Thanks.
