### ISSUE TITLE
NullPointerException thrown when saving a domain object with a transient property

### ISSUE THREAD

**Issue by donalmurtagh** [grails/grails-data-mapping#788]
I've found a bug in Grails 2.5.4 that causes a `NullPointerException` if you attempt to save a domain object which references another object with a transient property

I've pushed an [example app](https://github.com/domurtag/databinding) that demonstrates the issue. The README.md describes how to reproduce it. The name of the project is a bit of a misnomer. I originally thought it was a databinding bug, but it doesn't seem to be.

**Comment by graemerocher** [comment]
Can't reproduce with GORM 6
