### ISSUE TITLE
Setting projections through closure on DetachedCriteria doesn't work

### ISSUE THREAD

**Issue by RNiesler** [grails/grails-data-mapping#793]
Setting the projection through criteria closure doesn't have any effect:
```
final detachedCriteria = new DetachedCriteria(DetachedEntity).build {
  projections {
    distinct 'entityId'
  }
  eq 'field', 'abc'
}
```
while this works correctly:
```
final detachedCriteria = new DetachedCriteria(DetachedEntity).build {
  eq 'field', 'abc'
}
detachedCriteria.projections << new Query.DistinctPropertyProjection('entityId')
```

Here is some code that reproduces the problem:
https://github.com/RNiesler/grails-sandbox/blob/detachedCriteria/src/integration-test/groovy/rniesler/IntegrationTest.groovy

**Comment by graemerocher** [comment]
@jameskleeh I believe you fixed this no?

**Comment by jameskleeh** [comment]
@graemerocher The grails and gorm version in that sample app is old. @RNiesler can you attempt to reproduce in a fresh 3.1.12 or 3.2.0 application?

**Comment by RNiesler** [comment]
Sorry for not answering for such a long time but somehow the notification got lost. Anyway I've tried with the 3.2.2 and the issue is indeed fixed.
