### ISSUE TITLE
Can not persist list of maps in mongodb throws CodecConfigurationException

### ISSUE THREAD

**Issue by ChiranjibKarn** [grails/grails-data-mapping#796]
I have a domain
```
class Course {
    ObjectId id
    Integer points = 0
    List lessons //List of maps

    static embedded = ['lessons']
}
```
And in service am doing something like this, (lesson is a POGO here)

```
course.lessons = new ArrayList<>()
def lessonMap = [:]
lessonMap  << lesson.properties.findAll { !['class', 'metaClass'].contains(it.key) }
course.lessons.add(lessonMap)
course.save(flush: true, failOnError: true)
```

On saving I am getting following error:

> org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class java.util.LinkedHashMap

Java Version: 1.8
Grails Version: 3.1.1
MongoDb: 3.2
MongoDB GORM: 5.0.5 (org.grails.plugins:mongodb:5.0.5)

**Comment by graemerocher** [comment]
instead of `def lessonMap = [:]` use `def lessonMap = new Document()`

**Comment by ChiranjibKarn** [comment]
Thanks for your quick response Graeme.
Actually, I wanted list of documents, got your hint and problem solved, 

I did like following,

```
class Course {
    ObjectId id
    Integer points = 0
    List<Document> lessons //List of maps //Changed here

    static embedded = ['lessons']
}
```
and in service,

```
course.lessons = new ArrayList<>()
def lessonMap = [:]
lessonMap  << lesson.properties.findAll { !['class', 'metaClass'].contains(it.key) }
course.lessons.add(new Document(lessonMap)) //Changed here
course.save(flush: true, failOnError: true)
```


Thanks again for your quick and valuable response.
Am closing this issue now.
