### ISSUE TITLE
Grails 3.1.10 - Issues with binding Single-ended Associations

### ISSUE THREAD

**Issue by kalpanaDasireddy** [grails/grails-data-mapping#798]
I'm migrating grails application from 2.2.3 to 3.1.10. 
Id is not mapped to object for single ended associations
public class Item {
      LookupValue status
     static constraints = {
		status nullable:false
     }
}

Item item = new Item()
item.properties = params

params map looks like this ['status.id':'123']

save() fails with exception 

Field error in object 'com.xms.core.order.job.Item' on field 'status': rejected value [null].

If I change the param map to ['status.id':'123', status:['id':123]] it works. 

This was working with the first map ['status.id':'123'] in older version.

**Comment by graemerocher** [comment]
Not a GORM bug. Report here https://github.com/grails/grails-core/issues
