### ISSUE TITLE
Is there a way to avoid flush when doing a findBy or get?

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#799]
On binding we are looking for some objects in the database but that it's triggering the flush which at the end tries to persist an object which is not compete yet (binding didn't finish). How can we avoid this?

**Comment by graemerocher** [comment]
You have to configure the flush mode https://github.com/grails/gorm-neo4j/blob/master/grails-datastore-gorm-neo4j/src/main/groovy/org/grails/datastore/gorm/neo4j/Neo4jDatastore.java#L103

possible values are `AUTO` or `COMMIT`, what you want is `COMMIT`:

```groovy
grails {
     neo4j {
            flush { mode = "COMMIT" }
     }
}
```

**Comment by mburak** [comment]
Can i do it just for that binding? I don't want to change the whole application to do a save(flush: true)

**Comment by graemerocher** [comment]
probably by wrapping the call in `withSession` and calling `session.flushMode = ...`

**Comment by mburak** [comment]
Yeah that works. thanks.
