### ISSUE TITLE
GPMONGODB-374: Projecting id in criteria with mongodb plugin

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-data-mapping#80]
Original Reporter: sagrawal14
Environment: Grails 2.3.5, jdk 1.7.55, mongodb 2.0.1 or 3.0.0, no hibernate, ubuntu 14.04
Version: 3.0.0
Migrated From: http://jira.grails.org/browse/GPMONGODB-374

My grails 2.3.5 app have mongodb installed with no hibernate. When I try to project id of a domain class it throws following exception:

{code}
| Error 2014-05-09 19:45:00,916 [http-bio-8080-exec-1] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET] /mongo-id/user
Stacktrace follows:
Message: null
    Line | Method
->>  678 | doInDB       in org.grails.datastore.mapping.mongo.query.MongoQuery$39
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    598 | doInDB       in     ''
|    516 | list . . . . in org.grails.datastore.mapping.query.Query
|    244 | list         in grails.gorm.CriteriaBuilder
|     13 | index . . .  in test.UserController
|   1145 | runWorker    in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run          in java.lang.Thread

{code}

For example:

{code:title=User.groovy|borderStyle=solid}
class User {

    static constraints = {
    }

    String name
}
{code}

{code:title=UserController.groovy|borderStyle=solid}
package test

class UserController {

    def index(Integer max) {
        println User.withCriteria {
            projections {
                property("name")    // Will run okay
            }
            eq("name", "Test1")
        }

        println User.createCriteria().list {
            projections {
                property("id")      // Will fail
            }
            eq("name", "Test1")
        }

        println User.withCriteria {
            projections {
                property("id")      // Will fail
            }
            eq("name", "Test1")
        }
    }
}
{code}

I had also tried with mongodb 3.0.0 version. It also fails but throws a different exception:

{code}
| Error 2014-05-09 19:51:15,956 [http-bio-8080-exec-4] ERROR errors.GrailsExceptionResolver  - InvalidDataAccessResourceUsageException occurred when processing request: [GET] /mongo-id/user
Attempt to project on a non-existent project [id]. Stacktrace follows:
Message: Attempt to project on a non-existent project [id]
    Line | Method
->>  915 | doInDB       in org.grails.datastore.mapping.mongo.query.MongoQuery$58
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    833 | doInDB       in     ''
|    516 | list . . . . in org.grails.datastore.mapping.query.Query
|    244 | list         in grails.gorm.CriteriaBuilder
|     13 | index . . .  in test.UserController
|   1145 | runWorker    in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run          in java.lang.Thread
{code}

**Comment by brajendraSwain** [comment]
I am also facing the same issue. The solution provided is not here in the post. Could anybody help here, please?

**Comment by sagrawal31** [comment]
Oh! I raised this issue years ago. Here you go:

```
projections {
    id()
}
```

**Comment by sagrawal31** [comment]
Here is the original post that was migrated http://grails.1312388.n4.nabble.com/Projecting-id-in-mongo-criteria-td4656762.html

**Comment by brajendraSwain** [comment]
Thanks for the quick reply :)
