### ISSUE TITLE
Make it possible to define constraints and mapping DSL using static compilation

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-data-mapping#804]
Currently both constraints and mapping DSLs require special IDE support and knowledge for each GORM implementation. The DSL should be enhanced to use `@DelegateTo` and allow code completion and static compilation.

Current situation:

``` groovy
    static mapping = {
        table "books"
        author column: "auth_id"
    }
```

Possible syntax:

``` groovy
import static grails.gorm.hibernate.Mapping.*

    static mapping = define {
        table "books"
        id {  generator "sequence" }
        author column {
           name "auth_id"
        } 
    }
```

Discuss possible enhancement in Groovy to support `@DelegateTo` on named arguments and automatic dispatch to `invokeMethod` when `CompileStatic` is used in combination with a builder.

**Comment by fredgalvao** [comment]
@graemerocher @jameskleeh 
Even though this was added to [the changelog](http://gorm.grails.org/6.1.x/whatsNew/manual/#_improved_mapping_dsl), the docs never mention the new {compile-static/type-checked}-friendly sintax (every `/static mapping =/` is a `/static mapping = \{/`, and no mention of `/(orm|define|property) \{/`, and it's not quite clear to me how the `constraints` side of things are covered by the commits/PRs linked here (without debugging or taking a deeper look at the `Property` component and its uses). I also couldn't find any other issue on static compilation other than this, so I'd guess this is the best place, not necessarily the right one.

This came from a conversation on the Micronaut gitter, in which I had the following conclusion/question (please correct me if I'm wrong, I probably am):
> Wouldn't the static compilation be better solved on gorm entities if the @GrailsCompileStatic annotation was partially moved to GORM?

**Comment by alanbino** [comment]
Currently experiencing the same issue. Now using MappingBuilder for static compilation of an entity but I see no way to define the column constraints without removing @CompileStatic.
