### ISSUE TITLE
3.1.11: Composite key example from docs broken

### ISSUE THREAD

**Issue by miffels** [grails/grails-data-mapping#806]
The [composite key example linked in the latest Grails docs](http://docs.grails.org/3.1.11/guide/single.html#compositePrimaryKeys) does not seem to work as intended. Please find an [SSCCE here](https://github.com/miffels/catfood/tree/master/grails-isDomainClass-bug). I also checked in the [test reports](https://github.com/miffels/catfood/tree/master/grails-isDomainClass-bug/build/reports/tests) for your reference.

Please disregard the folder/package name - I initially thought I had some other issue related to `DomainClassArtefactHandler#isDomainClass()` heuristics failing because domain classes with composite keys no longer have an `id` property. This may or may not be true once the composite key is properly generated.
### Observation:

GORM still generates the `id` key and fails to mark the declared composite key `GrailsDomainClassProperty`s as `identity`. 
### Expected behavior:

The domain class has a `firstName` and `lastName` `GrailsDomainClassProperty` marked as `identity` instead of the generated `id` identity field.
### Grails version

```
>grails -version

| Grails Version: 3.1.11
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_102
```

As always, I hope there is some obvious mistake that I can fix on my side :)

Looking forward to hearing from you,
Michael

**Comment by graemerocher** [comment]
Thanks for the report, will look into it

**Comment by graemerocher** [comment]
The `GrailsDomainClass` API is a limited subset of the core GORM API. You should instead use `PersistentEntity`: http://gorm.grails.org/latest/hibernate/api/org/grails/datastore/mapping/model/PersistentEntity.html#getCompositeIdentity()

You can obtain a reference to a `PersistentEntity` from the `MappingContext`
