### ISSUE TITLE
hibernate3 for grails 3.x.x dependency issue

### ISSUE THREAD

**Issue by xavs** [grails/grails-data-mapping#807]
Hi,
It seems that the published plugin is requiring  https://repo.grails.org/grails/core/org/grails/grails-datastore-gorm-hibernate/6.0.0.RELEASE/grails-datastore-gorm-hibernate-6.0.0.RELEASE.jar

This release has not been published on the repository repo.grails.org, so it just won't work, couold i fix it using an overriding grails-datastore-gorm-hibernate-6.0.0.M1 dependency and excluding grails-datastore-gorm-hibernate-6.0.0 from the plugins dependency declaration?

Thanks!

PS: I did so with org.grails.plugins:hibernate3:5.0.12 
```
dependencies {
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.grails:grails-datastore-gorm-hibernate:6.0.0.M1"
    compile "org.grails:grails-core"
    console "org.grails:grails-console"
    profile "org.grails.profiles:base"
    compile ('org.grails.plugins:hibernate3:5.0.12'){
        exclude module: 'grails-datastore-gorm-hibernate'
    }
}
```
and I get runtime exception 
```
ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.NoClassDefFoundError: grails/validation/Constraint
```

**Comment by graemerocher** [comment]
Hibernate 3 support was dropped in GORM 6
