### ISSUE TITLE
java.lang.NoSuchMethodError: org.hibernate.Session.close()Ljava/sql/Connection;

### ISSUE THREAD

**Issue by bdbogjoe** [grails/grails-data-mapping#811]
Environment : 
jdk 1.8.0_102
Grails 3.2.0
GORM 6
hibernate5 with version 5.1.1.Final

I'm trying to query beans using `MyDomain.class.createCriteria().list(...)`

and having exception : 
```
java.lang.NoSuchMethodError: org.hibernate.Session.close()Ljava/sql/Connection;
	at org.grails.orm.hibernate.query.AbstractHibernateCriteriaBuilder.invokeMethod(AbstractHibernateCriteriaBuilder.java:1694)
	at org.grails.orm.hibernate.query.AbstractHibernateCriteriaBuilder.list(AbstractHibernateCriteriaBuilder.java:1558)
```

issue at this line : https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/query/AbstractHibernateCriteriaBuilder.java#L1694

According to @graemerocher the gorm6 is compiled against hibernate4 but the org.hibernate.Session::close() method signature has changed between 4 and 5 so it is creating issue when GORM is calling close method

Version 4.3
https://github.com/hibernate/hibernate-orm/blob/4.3/hibernate-core/src/main/java/org/hibernate/Session.java#L170

Version 5.1
https://github.com/hibernate/hibernate-orm/blob/5.1/hibernate-core/src/main/java/org/hibernate/Session.java#L75

In version 5.x, Session implement java.io.close() which return void instead of java.sql.Connection

**Comment by sascharitter** [comment]
I created an example app reproducing the problem: https://github.com/sascharitter/grails-issue-hibernate-session-close (I replaced the bean "grailsUrlMappingsHolder" by a custom implementation that calls the database)

Just start the app and open http://localhost:8080. It throws the aforementioned exception.

**Comment by graemerocher** [comment]
Thanks will take a look

**Comment by bdbogjoe** [comment]
one solution can be to call this method by reflection

**Comment by bdbogjoe** [comment]
the commit https://github.com/grails/grails-data-mapping/commit/7a621c5cae67b1a782d31eb2487e5f8d8316005b can solve the issue ?

**Comment by bdbogjoe** [comment]
i confirm works fine with version 6.0.1, thanks

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/7a621c5cae67b1a782d31eb2487e5f8d8316005b
