### ISSUE TITLE
Named query cannot reference embedded object properties

### ISSUE THREAD

**Issue by nagysz** [grails/grails-data-mapping#814]
Using embedded class' properties in namedQueries is currently not possible.
Working with:
- Grails 3.2
- Gorm for Hibernate 5 6.0.0

Hibernate criterias handle it in the following form: `Restriction('embedded.property', value)`. Using the former format results in: `java.lang.IllegalArgumentException: Property [embedded.property] is not a valid property of class [Domain]`. For a complete example please take a look at my [stackoverflow question](https://stackoverflow.com/questions/40116208/how-to-reference-embedded-object-properties-in-named-queries-in-grails-3-2).

**Comment by graemerocher** [comment]
It is recommended to use where queries instead of named queries.
