### ISSUE TITLE
Hibernate 5.2 support

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-data-mapping#820]
We need to provide Hibernate 5.2 support. Some notes:
- Hibernate 5.2 is Java 8+ only and merges `hibernate-java8`, `hibernate-core` and `hibernate-entity-manager` into a single JAR
- Hibernate 5.2 includes significant API changes so we may need a separate `grails-datastore-gorm-hibernate52` subproject
- Spring Boot compatibility thread https://github.com/spring-projects/spring-boot/issues/6111
- Grails Core issue https://github.com/grails/grails-core/issues/10030
- Migration Guide https://github.com/hibernate/hibernate-orm/wiki/Migration-Guide---5.2

**Comment by todoubaba** [comment]
Hibernate 5.2 is already supported in Spring boot https://github.com/spring-projects/spring-boot/issues/7230#issuecomment-256460674
