### ISSUE TITLE
composition problem

### ISSUE THREAD

**Issue by jfernandosilva** [grails/grails-data-mapping#831]
I need use composition in gorm 6, I replicated the example from the documentation
http://gorm.grails.org/6.0.x/hibernate/manual/#gormComposition, but I obtained a bad behavior, fields of class Addres were embedded correctly in Person class but **also a Address table was create in database**. I included the Address class below the Person class in the grails-app/domain/Person.groovy file, according with the documentation.

Database generated
![grails](https://cloud.githubusercontent.com/assets/8558969/20467104/8f9e4460-af45-11e6-9789-0b8f79f25306.png)
I used the next environment:
- Grails Version: 3.2.3
- JVM Version: 1.8.0_111

Test [repository](https://github.com/jfernandosilva/test-composition)

**Comment by graemerocher** [comment]
Move the `Address` class to `src/main/groovy`

**Comment by jfernandosilva** [comment]
Thanks, this workaround worked fine
