### ISSUE TITLE
Grails 3.1.6, Hibernate 4. Composite foreign key

### ISSUE THREAD

**Issue by gmborisov** [grails/grails-data-mapping#835]
```
class Tooth {
  Integer id
  ToothDisease toothDisease
   static mapping = {
    table name: 'AK_TOOTH'
    id generator: 'sequence', params: [sequence: 'SEQ_AK_TOOTH']
    columns{
        toothDisease {
        column: 'FK_AK_TOOTH_ID' 
        column: 'FK_AK_TOOTH_NR_VERSION' 
        }
    }
} 
```

```
class ToothDisease implements Serializable{
  Integer idColumn
  Integer nrVersion
   static mapping = {
    table name: 'AK_TOOTH_DISEASE'
    idColumn column: 'ID', generator: 'sequence', params: [sequence: 'SEQ_AK_TOOTH_DISEASE']
    nrVersion  column: 'NR_VERSION',
    id composite ['idColumn','nrVersion']
 
   int hashCode () {
    def builder = new HashCodeBuilder ()
    builder.append (idColumn)
    builder.append (nrVersion)
    builder.toHashCode ()
  }

  boolean equals (other) {
    if (other == null) {
      return false
    }
    def builder = new EqualsBuilder ()
    builder.append (idColumn, other.idColumn)
    builder.append (nrVersion, other.nrVersion)
    builder.isEquals ()
  }
} 
```

When I try to bootRun my app I get BeanCreationException Caused by: org.hibernate.MappingException: Foreign key (FK_1rnajvolkf4rkav5w1hl0l9fk:AK_TOOTH [tooth_disease_id,FK_AK_TOOTH_ID,FK_AK_TOOTH_NR_VERSION,tooth_disease_id_column,tooth_disease_nr_version])) must have same number of columns as the referenced primary key (AK_TOOTH_DISEASE [ID,NR_VERSION]).

When I removed column mapping section in Tooth, then I got the same error without those columns
[tooth_disease_id,tooth_disease_id_column,tooth_disease_nr_version]. 
Is it possible to explicitly define key column and  referencedColumnName like in hibernate?
Why there are three columns? especially tooth_disease_id and tooth_disease_id_column columns in the same time. I tried to use 'primaryKey' name as composite primary key for Tooth and 'id' simple as id column, but in this way, I had the same error
 Caused by: org.hibernate.MappingException: Foreign key (FK_1rnajvolkf4rkav5w1hl0l9fk:AK_TOOTH [tooth_disease_id,FK_AK_TOOTH_ID,FK_AK_TOOTH_NR_VERSION,tooth_disease_id_column,tooth_disease_nr_version])) must have same number of columns as the referenced primary key (AK_TOOTH_DISEASE [ID]).But there is only one referenced primary key.

Unfortunately, I have no chance to change schema structure and avoid composite key.

**Comment by graemerocher** [comment]
The following tests now passes in 6.0.x snapshots:

https://github.com/grails/gorm-hibernate5/commit/0c424fba40e1a66433e827c8ca852f6b0a18184e#diff-a09d869f2687396eef55180d20014dd8R22
