### ISSUE TITLE
No effect on setting failOnError in application.yml with MONGO DB plugin 6.0.4 

### ISSUE THREAD

**Issue by dreampursuer** [grails/grails-data-mapping#837]
I have grails app created using 3.2.3 MongoDB plugin 6.0.4 without Hibernate plugin.
I use the following setting in application.yml for mongodb:

grails:
    gorm:
        failOnError: true

---

grails:
    mongodb:
        host: "xxx"
        port: 27017
        databaseName: "xxx"

---
There's no exception thrown when call domainInstance.save() on bad data.

This bug has been fixed in MONGO DB plugin 5.0.9, but it reproduced now.
The related bug is https://github.com/grails/grails-data-mapping/issues/734.

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/gorm-mongodb/commit/4d12ea187cc73641070db170034c2b1f81bafcdf
