### ISSUE TITLE
FlushMode seems to be always automatic

### ISSUE THREAD

**Issue by Guigoz** [grails/grails-data-mapping#839]
Hello,

Thanks for your work on Grails.

I was looking at the sources to search an explanation for a strange behaviour I encounter.

But instead I found this : [GrailsOpenSessionInViewInterceptor.java#L85](https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-support/src/main/groovy/org/grails/orm/hibernate4/support/GrailsOpenSessionInViewInterceptor.java#L85)

`boolean isNotManual = session.getFlushMode() != FlushMode.MANUAL || session.getFlushMode() != FlushMode.COMMIT;`

It can't evaluate to true. I don't think it's a wanted behaviour. :)

Greetings,
Guillaume.

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/ff460d92fa52a77a08578912dc7f27ac4660d98e
