### ISSUE TITLE
Add UUID.class to MappingFactory.SIMPLE_TYPES

### ISSUE THREAD

**Issue by abryzakez** [grails/grails-data-mapping#848]
I have a domain class with a field defined as a UUID.

```groovy
class MyDomainClass {
    UUID someId
}
```

In a Spock unit test, if I `@Mock` this class and try to use a `findBySomeId` dynamic finder it gets an error: `InvalidDataAccessResourceUsageException: Cannot query … on non-existent property: someId`

I've tracked this down to the `GormMappingConfigurationStrategy.getPersistentProperties` method skipping the property as it's not a simple or custom type in the default configuration. The `mappingFactory` which devices it is a `GormKeyValueMappingFactory` which extends `MappingFactory` which has the list of `SIMPLE_TYPES`.

I believe it should be a simple type as it's supported by Hibernate out of the box with `org.hibernate.type.UUIDBinaryType` and `org.hibernate.type.UUIDCharType`

**Comment by abryzakez** [comment]
Note, I've found a few other people that have run into the problem with poor solutions (using a String instead of a UUID):
* http://stackoverflow.com/questions/25939798/using-findby-method-on-non-primary-key-uuid-type-field-causes-an-exception
* http://grails.1312388.n4.nabble.com/findByUuid-in-unit-test-claims-property-does-not-exist-td4653880.html

Also there was an open issue I just found in grails-core : https://github.com/grails/grails-core/issues/9911

**Comment by abryzakez** [comment]
If anybody else runs into this, I've worked around it for the moment by overriding that method in my unit tests. I created these classes:

```groovy
class UUIDSupportingSimpleMapDatastore extends SimpleMapDatastore {
    UUIDSupportingSimpleMapDatastore(ConfigurableApplicationContext ctx) {
        super(new UUIDSupportingKeyValueMappingContext(""), ctx)
    }
}
```

```groovy
class UUIDSupportingKeyValueMappingContext extends KeyValueMappingContext {
    UUIDSupportingKeyValueMappingContext(String keyspace) {
        super(keyspace)
    }

    protected void initializeDefaultMappingFactory(String keyspace) {
        mappingFactory = new UUIDSupportingGormKeyValueMappingFactory(keyspace)
    }
}
```

```groovy
class UUIDSupportingGormKeyValueMappingFactory extends GormKeyValueMappingFactory {
    UUIDSupportingGormKeyValueMappingFactory(String keyspace) {
        super(keyspace)
    }

    boolean isSimpleType(Class propType) {
        return super.isSimpleType(propType) || propType == UUID.class
    }
}
```

Then in tests that need to mock a domain class that contains a UUID, I do the following instead of using `@Mock`:

```groovy
def setupSpec() {
    defineBeans {
        grailsDatastore(UUIDSupportingSimpleMapDatastore, grailsApplication.mainContext)
    }
    mockDomains(MyDomainClassContainingUUIDField)
}
```

**Comment by edwardotis** [comment]
@graemerocher Will this fix be available to grails 3.1.x line?
I'm running into this bug on 3.1.14 with my domain classes that use UUID.

My gorm version is:
compile 'org.grails:grails-datastore-gorm:5.0.12.RELEASE'

**Comment by edwardotis** [comment]
Confirmed that the workaround by @abryzakez works with Gorm5, grails 3.1.x

**Comment by edwardotis** [comment]
Upon further use, the workaround is only working for Domain classes that have no relationships to other domain classes. 

java.lang.IllegalStateException: Either class [com.myNonUUIDContainingForeignKeyDomainClass] is not a domain class or GORM has not been initialized correctly or has already been shutdown. If you are unit testing your entities using the mocking APIs

So, this bug still blocks domain unit testing in Gorm5, grails 3.1.x. for devs that have chosen to use UUIDs

**Comment by edwardotis** [comment]
@graemerocher Is there anything I can do to help get this fix published to a GORM5 release faster? It's blocking a significant portion of my domain unit tests. I made an attempt to upgrade my code base to grails3.2.11/GORM6 but it failed. Thank you.

**Comment by jukin-jerry** [comment]
https://github.com/grails/grails-data-mapping/pull/1030
