### ISSUE TITLE
Multi-level domain inheritance mapping loses some leaf class mappings

### ISSUE THREAD

**Issue by gorgiev** [grails/grails-data-mapping#857]
Given a domain mapping hierarchy of Root->Base->Child, when Grails loads domain classes into a mapping context, some of the Children registrations are missed in the context's persistentEntitiesByDiscriminator map entry for the Root. 

After this occurs, when a polymorphic domain query against the whole hierarchy is done using Root, the Child instances with missed registration are loaded as Root type (Child-specific properties not mapped).   

The scenario is as follows:  AbstractMappingContext.addPersistentEntities() gets passed classes ChildA, Base, ChildB, ChildC. When the method returns the persistentEntitiesByDiscriminator entry for Root only has Base, ChildB and ChildC. Instances of ChildA will be loaded as Root type.

The logic in AbstractMappingContext.initializePersistentEntity is order-sensitive. Here is a test case to replicate the described scenario.

Add to GormMappingInheritanceTests suite:

    @Test
    void testInheritedMultiLevelMapping() {
        def context = new TestMappingContext()
        context.addPersistentEntities(DerivedEntityChildA, DerivedEntity, DerivedEntityChildB, DerivedEntityChildC)
        assertEquals 2, context.persistentEntitiesByDiscriminator.size()
        def secondEntityMappingKey = context.persistentEntitiesByDiscriminator.keySet().find { it.decapitalizedName == 'secondEntity' }
        assertNotNull secondEntityMappingKey
        def secondEntityMappings = context.persistentEntitiesByDiscriminator.get(secondEntityMappingKey)
        assertEquals 4, secondEntityMappings.size()
    }

and add to the same file alongside other Test domain class definitions:

    @grails.persistence.Entity
    class DerivedEntityChildA extends DerivedEntity {
    }

    @grails.persistence.Entity
    class DerivedEntityChildB extends DerivedEntity {
    }

    @grails.persistence.Entity
    class DerivedEntityChildC extends DerivedEntity {
    }

The test will fail on the final assert, with persistentEntitiesByDiscriminator for SecondEntity (the Root in the described scenario) containing DerivedEntity, DerivedEntityChildB, DerivedEntityChildC, and missing DerivedEntityChildA.

This bug was observed when running a Grails 3.2.4 app. I would consider this a serious issue as it breaks the multi-level inheritance mapping feature.

**Comment by graemerocher** [comment]
Thanks for the detailed report. Will take a look.

**Comment by gorgiev** [comment]
Thank you for the quick action on this, Graeme.
