### ISSUE TITLE
Dynamic finder methods cannot be referenced

### ISSUE THREAD

**Issue by berdario** [grails/grails-data-mapping#858]
Groovy can use method references for methods dispatched dynamically with `method_missing` just fine:

```
groovy:000> class B{
groovy:001>   def method_missing(n, args){
groovy:002>     if (n == 'print'){
groovy:003>         return {x -> println x}
groovy:004>       }
groovy:005>   }
groovy:006> }
===> true
groovy:000> b = new B()
===> B@3cdf2c61
groovy:000> b.&print(42)
42===> null
```

But apparently the same thing doesn't work for Grails/GORM dynamic finders. Given a domain class `Foo`:

```Foo.&countById(42)```

fails with

```
groovy.lang.MissingMethodException: No signature of method: crap2.Foo.countById() is applicable for argument types: (java.lang.Integer) values: [42]
Possible solutions: count()
```

reproduced with Grails 3.2.3

**Comment by graemerocher** [comment]
This doesn't work in Groovy either:

```groovy
class B {
   static $static_methodMissing(String name, args) {
     println name
     return name
   }
}

B.foo()
def test = B.&foo
test()
```

Feel free to report an issue there https://issues.apache.org/jira/browse/GROOVY

**Comment by berdario** [comment]
For those who are wondering: the confusing bit is that `print` is not really a builtin function, but a method of `Object`, and thus that's it's only by chance than in my example I was able to get a reference to the method that I defined, because I inadvertently picked the same name as one of a preexisting method
