### ISSUE TITLE
GORM Embedded domain changes are not persisted since 6.0.5

### ISSUE THREAD

**Issue by benorama** [grails/grails-data-mapping#865]
### Steps to Reproduce

1. Create a domain class A with embedded domain components B
2. Create and save a new domain A-1 instance with some B-1 instance (which will be persisted in A-1 DB table)
3. Load A-1, update B-1 and save A-1

### Expected Behaviour

It should persist B-1 embedded domain change (in A-1 table).

### Actual Behaviour

Changes are not persisted.

This was working fine with Grails **3.2.3** and started to brake with Grails **3.2.4** (GORM **6.0.5**).

Workaround: wrap the call around a `withTransaction`

### Environment Information

- **Operating System**: Mac OSX 10.12.3
- **Grails Version:** 3.2.5
- **JDK Version:** 1.8.0_25

### Example Application

- https://github.com/benorama/grails-gorm-embed-issue

**Comment by benorama** [comment]
I suspect that this change https://github.com/grails/grails-data-mapping/issues/844 has a lot of side effects issues.
We have a lot of other cases where domain changes are not persisted if not wrapped in a `withTransaction`.
We just rolled back to Grails 3.2.3 because we had too much GORM issues with Grails 3.2.4 and GORM 6.0.5.

**Comment by graemerocher** [comment]
Probably related to https://github.com/grails/grails-core/issues/10444

**Comment by benorama** [comment]
Indeed, it might be related.
I checked a little more about this issue: even a simple property change is not persisted.
It looks like the Hibernate session is not flushed at the end of the request.
Only updates wrapped inside a transaction are correctly persisted.

**Comment by graemerocher** [comment]
See the discussion in #10444 

you should never do write operations without a transaction, granted it is wrong that this broke a point release and we will look into fixing it. 

In Hibernate 5.2+ and JPA for example a write operation without a transaction is an exception.

**Comment by snorith** [comment]
Embedded objects don't seem to be updating, even within a transaction

```
grailsVersion=3.3.0.RC1
gormVersion=6.1.5.RELEASE
```

...

```
@Autowired
TransactionService transactionService
```

...

```
transactionService.withTransaction { TransactionStatus status ->
    domain.embedded.field = 'newvalue'
    domain.save flush:true            // same for .merge(flush:true)
}
```

The new value of the embedded field is not saved. It appears that the domain object is not marked as being dirty. Tried manually incrementing `domain.version` but that doesn't save the embedded object either

**Comment by graemerocher** [comment]
call `domain.markDirty('embedded')`

**Comment by snorith** [comment]
Thanks Graeme

**Comment by cseewald** [comment]
Had the same issue as @snorith. Fix was `domain.markDirty('embedded')`.

**Why is this not a bug?**

**Comment by snorith** [comment]
@cseewald The GORM docs mention a new annotation for GORM 6.1. Embedded classes have to be marked as:

```
@DirtyCheck
class Embedded {
   ...
}
```

Also, they should be declared in the `/src/Groovy` directory rather than in the `grails-app` directory

**Comment by cseewald** [comment]
Thanks snorith for pointing out the new annotation.
