### ISSUE TITLE
Transients not inherited from non-root parents

### ISSUE THREAD

**Issue by bryndavies** [grails/grails-data-mapping#866]
Given the following domain hierarchy:

    class ClassA {
        static constraints = {}
        static transients = ['prop2']
        String prop1
        String prop2
    }

    class ClassB extends ClassA {
        static constraints = {}
        static transients = ['prop4']
        String prop3
        String prop4
    }

    class ClassC extends ClassB {
        static constraints = {}
        static transients = ['prop6']
        String prop5
        String prop6
    }

on creating and saving an instance of ClassC, properties 1, 3, 4 and 5 are persisted to the database. The transient nature of prop2 is inherited from the root ClassA, but the transient nature of prop4 is not inherited from the intermediate ClassB.

Grails 3.2.4
Hibernate 5.1.2
Gorm 6.0.5
MySql driver 5.1.40

**Comment by jameskleeh** [comment]
Please provide an example application

**Comment by bryndavies** [comment]
Example app here: https://github.com/bryndavies/gormissue

This application creates an instance of ClassC in the bootstrap, in local sql database 'gormissue'. 

Expected result:
Persisted fields: prop1, prop3, prop5
Not persisted: prop2, prop4, prop6

Actual result: 
Persisted fields: prop1, prop3, prop4, prop5
Not persisted: prop2, prop6
