### ISSUE TITLE
Cannot connect to AS/400 (Grails 3.2.5)

### ISSUE THREAD

**Issue by gsartori** [grails/grails-data-mapping#869]
Hi there, we are having this issue: https://hibernate.atlassian.net/browse/HHH-11470

The hibernate team is asking to try realease 5.2.7.
We have the environment to test it but not the skills to repackage the plugin.

Please let me know how we can help with testing,
regards,
Gianluca

**Comment by graemerocher** [comment]
Only the GORM 6.1 milestones/snapshots support Hibernate 5.2 at the moment

**Comment by graemerocher** [comment]
Since the Hibernate bug was fixed ,closing this.
