### ISSUE TITLE
Add tenant during runtime

### ISSUE THREAD

**Issue by andersb** [grails/grails-data-mapping#870]
Hi,
This is more of a question/request rather then an issue (and apologies if this isn't the correct forum)

The documentation clearly states that GORM doesn't offer creating new databases during run time but on the other hand, you can hook into GORM via the ConnectionSource API.

The example shows how to add tenants in run time but only during start up and here is where I'm stuck.

Looking at HibernateDataStore, the property datastoresByConnectionSource would be the place where one would like to add more connections for newly created tenants.

Now I don't really know the inner workings/constraints of GORM, other then it's seriously awesome to work with, but is there a reason why adding connections to this property can not be done after start up?

I'm using SCHEMA as multi-tenancy mode and my plan is to create/migrate schemas outside of GORM.

Regards
Anders

**Comment by graemerocher** [comment]
Seems that we have some code missing for hibernate for this use case. The equivalent code to this in MongoDB:

https://github.com/grails/gorm-mongodb/blob/master/grails-datastore-gorm-mongodb/src/main/groovy/org/grails/datastore/mapping/mongo/MongoDatastore.java#L209

Needs to be added

**Comment by hmtmcse** [comment]
Hi,
I am working on a app which will allow signup and create new site with sub domain,  for the requirement i need to deploy database on runtime, i checked the MongoDatastore, it quite difficult to manage for me and also implement, is there any quick way to addConnectionSource without implementing the InMemoryConnectionSources. 

I am using, MySQL Database.
Thanks
