### ISSUE TITLE
How to prevent GORM schema / DDL generation for certain domain classes?

### ISSUE THREAD

**Issue by timbonicus** [grails/grails-data-mapping#880]
I'm working on an application that uses PostgreSQL views in place of tables for some domain classes. I'd like to skip schema generation for these domain classes (even with dbCreate="create"), since the view definitions are managed elsewhere.

In gorm-hibernate4, we used hibernate.configClass to provide a subclass of GrailsAnnotationConfiguration and overrode the generate*Script methods to exclude the schema in question.

In gorm-hibernate5, I see that GrailsAnnotationConfiguration has changed to HibernateMappingContextConfiguration, and it doesn't seem as straight-forward to override the schema generation.

I tried overriding HibernateMappingContextConfiguration.setHibernateMappingContext to remove these domain classes from the list of persistentEntities, but this causes a NPE with GrailsDomainBinder when another domain class has an association to one of the excluded entities.

It feels like I'm overlooking an easier way to achieve this. Is there a recommended way to skip schema / DDL generation for certain domain classes? Or a better way to override HibernateMappingContextConfiguration?

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)

**Comment by graemerocher** [comment]
In Hibernate 5 there is a specific setting for this it seems `hibernate.schema_management_tool`. See https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/tool/schema/spi/SchemaManagementTool.html

**Comment by timbonicus** [comment]
Thank you @graemerocher for pointing me in the right direction. I set hibernate.hbm2ddl.schema_filter_provider to my own SchemaFilterProvider, then implemented a SchemaFilter to return. SchemaFilter has includeNamespace/includeTable functions to prune the DDL generation.

**Comment by timbonicus** [comment]
For the benefit of future ticket-viewers, I posted a solution on [this StackOverflow thread](http://stackoverflow.com/a/43548589/99021) that uses SchemaManagementTool as @graemerocher suggested to provide complete control over the DDL commands.
