### ISSUE TITLE
GORM persistence listener invokes PreUpdate on insert

### ISSUE THREAD

**Issue by jameskleeh** [grails/grails-data-mapping#885]
A GORM event listener with the following method:

```    
    @Override
    protected void onPersistenceEvent(AbstractPersistenceEvent event) {
        if (event.entityObject instanceof User) {
            User user = (User)event.entityObject
            if (user.password) {
                if (event.eventType == EventType.PreInsert || user.isDirty('password')) {
                    user.password = springSecurityService.encodePassword(user.password)
                }
            }

        }
    }
```

The line that sets the password on the user object causes 2 further `PreUpdate` events to fire, even though the object is new

`new User('foo', 'bar').save()`

Example project: https://github.com/jameskleeh/test-gdm-885

To reproduce, run the app

**Comment by jameskleeh** [comment]
Just to note I also attempted modifying the domain with `event.entityAccess` with the same result

**Comment by jameskleeh** [comment]
Another note - I attempted to do the same thing with hibernate event listeners and also got the same result

**Comment by sdelamo** [comment]
I believe I am experiencing this issue as well. When doing findByUsername, I am getting an event PreUpdate with password dirty. See: 

 https://github.com/sdelamo/grails-spring-security-core/blob/abstractPersistenceEventListener/functional-test-app/src/integration-test/groovy/com/testapp/TestUserServiceIntegrationSpec.groovy#L31

**Comment by graemerocher** [comment]
So just to summarise, there is no direct solution to this, using an objects setter, however you can use the `EntityAccess` object. So the example here becomes

```groovy
event.getEntityAccess().setProperty("password", springSecurityService.encodePassword(user.password))
````

With this change, GORM will sync the state with Hibernate and no additional update will be triggered.
