### ISSUE TITLE
Error in GORM developer manual website

### ISSUE THREAD

**Issue by rmorrise** [grails/grails-data-mapping#892]
I am looking at the GORM developer guide 6.0.x:
http://gorm.grails.org/6.0.x/developer/manual/index.html

In the guide itself, under "Secondary Indexing", it looks like there is a section of the page that is not being rendered properly. That section of the guide only contains an error:
"Unresolved directive in index.adoc - include::understandingApi/secondaryIndexes.adoc[]"

![gorm guide - error](https://cloud.githubusercontent.com/assets/8999824/24268944/ddbc9c86-0fe5-11e7-84a8-08163cadff7d.png)

**Comment by puneetbehl** [comment]
For future reference please open issues related to GORM Documentation at [grails/gorm-docs](https://github.com/grails/gorm-docs) repository.
