### ISSUE TITLE
Passing empty string to GORM .get() method used to return a null result, now throws an error

### ISSUE THREAD

**Issue by davydotcom** [grails/grails-data-mapping#905]
In previous versions of GORM 5 and below calling an object get method while passing a blank param simply returned null.

```groovy
given:
 def bookId = '' //useful if a blank param is passed as well from say a dropdown
when:
  def result = Network.get(bookId)
then:
  result == null
```

This now throws an Exception in GORM 6.0.9 + and potentially earlier versions of GORM6

This is hibernate 5.1.3.FINAL
`java.lang.IllegalArgumentException: id to load is required for loading`

**Comment by jameskleeh** [comment]
Already fixed https://github.com/grails/grails-data-mapping/blob/6.0.x/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/AbstractHibernateGormStaticApi.groovy#L77

**Comment by davydotcom** [comment]
Is it in any 6.0.x releases?

**Comment by jameskleeh** [comment]
@davydotcom Not yet
