### ISSUE TITLE
Flush mode config not picked up if resolver is PropertySourcesConfig

### ISSUE THREAD

**Issue by dpcasady** [grails/grails-data-mapping#923]
In GORM 6.1.x, setting `hibernate.flush.mode` doesn't work if the `PropertyResolver` is an instance of `NavigableMapConfig`. This is the case when running in a Grails app.

When building `HibernateConnectionSourceSettings` within `AbstractHibernateConnectionSourceFactory`,
 the builder will attempt to set the flush mode on `HibernateConnectionSourceSettings.HibernateSettings.FlushSettings`. The mode is an enum type of `FlushMode`.

As the builder attempts to set the flush mode a `ConversionException` will occur inside the `PropertyResolver` because the configuration value can't be converted to an enum. [ConfigurationBuilder will catch the exception](https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-core/src/main/groovy/org/grails/datastore/mapping/config/ConfigurationBuilder.groovy#L291) and attempt to get the enum value. This works fine with a non-`NavigableMapConfig` resolver.

The problem is that [NavigableMapConfig swallows the exception](https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/org/grails/config/NavigableMapConfig.java#L218) so it never reaches the `ConfigurationBuilder` and thus the flush mode is never set.

The second of these tests (similar to [HibernateConnectionSourceSettingsSpec](https://github.com/grails/grails-data-mapping/blob/4c2484148054fb936a3c7787d30847c37747be19/grails-datastore-gorm-hibernate-core/src/test/groovy/org/grails/orm/hibernate/connections/HibernateConnectionSourceSettingsSpec.groovy)) establish the problem:

```groovy
void "flush mode is picked up from ConfigurableEnvironment property resolver"() {
    when:
    Map config = ['hibernate.flush.mode': 'always']

    PropertyResolver resolver = DatastoreUtils.createPropertyResolver(config)
    HibernateConnectionSourceSettingsBuilder builder = new HibernateConnectionSourceSettingsBuilder(resolver)
    HibernateConnectionSourceSettings settings = builder.build()

    then:"The flush settings are correct"
    settings.hibernate.getFlush().mode == HibernateConnectionSourceSettings.HibernateSettings.FlushSettings.FlushMode.ALWAYS
}

void "flush mode is picked up from PropertySourcesConfig property resolver"() {
    when:
    Map config = ['hibernate.flush.mode': 'always']

    PropertyResolver resolver = new PropertySourcesConfig(config)
    HibernateConnectionSourceSettingsBuilder builder = new HibernateConnectionSourceSettingsBuilder(resolver)
    HibernateConnectionSourceSettings settings = builder.build()

    then:"The flush settings are correct" // fails
    settings.hibernate.getFlush().mode == HibernateConnectionSourceSettings.HibernateSettings.FlushSettings.FlushMode.ALWAYS
}
```

[Example grails 3.2.9/GORM 6.1.2 app](https://github.com/dpcasady/flush-mode) that demonstrates the issue. Run the unit tests and you should see the failure.

**Comment by graemerocher** [comment]
Will require a change on the Grails side to deal with enums in a similar way. Note that the problem can be trivially worked around by simply using a value that matches the enum:

```groovy
 Map config = ['hibernate.flush.mode': 'ALWAYS']
```
