### ISSUE TITLE
executeUpdate should add @CompileDynamic also

### ISSUE THREAD

**Issue by todoubaba** [grails/grails-data-mapping#935]
PR https://github.com/grails/grails-data-mapping/commit/7c8f78018e486b75d2a1ea6c613c65a73d3f57e5 is not complete. Some methods in [HibernateGormStaticApi](https://github.com/grails/gorm-hibernate5/blob/master/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/HibernateGormStaticApi.groovy#L114) should add  `@CompileDynamic` also.

### Environment Information

- **Operating System**: Windows 10
- **GORM Version:** 6.1.3
- **Grails Version (if using Grails):** 3.2.9
- **JDK Version:** 1.8

**Comment by todoubaba** [comment]
I think supporting both hibernate 5.1.x and 5.2.x in the same release complicates the gorm codes and leads to more bugs.

**Comment by graemerocher** [comment]
Tell me about it, that is why the next version of GORM will drop support for all versions below 5.2

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/gorm-hibernate5/commit/1fd5e889a321a4890e35c56e8b72962cd937b500
