### ISSUE TITLE
runCommand detects a dependency cycle for AbstractPersistenceEventListener Bean

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-data-mapping#946]
### Steps to Reproduce

If you create a bean extending `AbstractPersistenceEventListener` such as: 

```
package demo

import org.grails.datastore.mapping.core.Datastore
import org.grails.datastore.mapping.engine.event.AbstractPersistenceEvent
import org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener
import org.springframework.context.ApplicationEvent
import org.grails.datastore.mapping.engine.event.PreInsertEvent
import org.grails.datastore.mapping.engine.event.PreUpdateEvent

class TestPersistenceEventListener extends AbstractPersistenceEventListener {

    protected TestPersistenceEventListener(Datastore datastore) {
        super(datastore)
    }

    @Override
    protected void onPersistenceEvent(AbstractPersistenceEvent event) {}

    @Override
    boolean supportsEventType(Class<? extends ApplicationEvent> eventType) {
        eventType == PreUpdateEvent || eventType == PreInsertEvent
    }
}
```

and define the bean in `grails-app/conf/spring/resources.groovy`

```
import demo.TestPersistenceEventListener
beans = {
    testPersistenceEventListener(TestPersistenceEventListener, ref('hibernateDatastore'))
}
```

If you run any grails command such as: 

`./gradlew myapp:runCommand -Pargs="hello"`

You get the next error: 

```

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌─────┐
|  hibernateDatastore
↑     ↓
|  testPersistenceEventListener
└─────┘


Context failed to load: Error creating bean with name 'hibernateDatastore': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.orm.hibernate.HibernateDatastore]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testPersistenceEventListener': Cannot resolve reference to bean 'hibernateDatastore' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'hibernateDatastore': Requested bean is currently in creation: Is there an unresolvable circular reference?
:myapp:runCommand FAILED
```

**Note: you can run the app with no issue:** 

`./gradlew myapp:bootRun`

No cycle detected there. 

### Environment Information

- **Operating System**: MacOS
- **GORM Version:** 6.0.10.RELEASE
- **Grails Version (if using Grails):** 3.2.9
- **JDK Version:** 1.8.0_121

### Example Application

- [Github repository](https://github.com/grails-core-issues-forks/hibernatedatastore-dependencies-cycle)

**Comment by sdelamo** [comment]
The difference between when executing in `bootStrap`and `runCommand` is in:  https://github.com/spring-projects/spring-framework/blob/master/spring-beans/src/main/java/org/springframework/beans/factory/support/DefaultSingletonBeanRegistry.java#L346

### BootRun

For beanName `hibernateStore`in  bootRun enters once with: 

`singletonsCurrentlyInCreation = ['openSessionInViewInterceptor', 'UrlMappingsHandlerMapping', 'GrailsCacheFilter']
`
### RunCommand

For beanName `hibernateStore`in  bootRun enters twice with: 

one with: 

`singletonsCurrentlyInCreation = ['sessionFactory']
`
second one with: 

`singletonsCurrentlyInCreation = ['testPersistenceEventListener', 'hibernateStore', 'sessionFactory']`

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails/gorm-hibernate5/commit/4ae27d336b73359598f12a15fdb8ffb39186650d
