### ISSUE TITLE
fulltext search via hibernate-search API

### ISSUE THREAD

**Issue by genuinefafa** [grails/grails-data-mapping#953]
I'm looking to use the hibernate-search API from within a GORM 6 app (grails 3.2.9). I know there is an hibernate-search plugin, but is outdated (no grails 3.2.x nor 3.3.x support).

Anyways, it looks like if hibernate is under GORM, one should be able to use hibernate-search "easily", don't we?

**Comment by puneetbehl** [comment]
Yes, as you said there is already a separate hibernate-search plugin for this. And, I think the best option would be to update hibernate-search plugin. So, I would request you to open a ticket to update hibernate-search plugin instead.
