### ISSUE TITLE
Multi-Tenancy - DISCRIMINATOR mode - One-To-Many relationship without belongsTo

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-data-mapping#954]
Two domain classes with a one-to-many relationship between them.Both implement MultiTenant Trait.  Multi-tenancy discriminator mode is used in the app. If the child class does not the define the `belongsTo` property, the discriminator column does not get created and thus queries fail. 

```
import grails.gorm.MultiTenant

class Engine implements MultiTenant<Engine> { 
    Integer cylinders
    String manufacturer 
    static belongsTo = [vehicle: Vehicle] // If you remove this, it fails
    
   static constraints = {
        cylinders nullable: false
    }

    static mapping = {
        tenantId name:'manufacturer'  
    }
}

import grails.gorm.MultiTenant

class Vehicle implements MultiTenant<Vehicle> { 
    String model
    Integer year
    String manufacturer 

    static hasMany = [engines: Engine]
    static constraints = {
        model blank:false
        year min:1980
    }

    static mapping = {
        tenantId name:'manufacturer'  
    }
}

```

### Steps to reproduce.

Clone repository: 

https://github.com/grails-guides/discriminator-per-tenant

Inside that repository, there is a Grails 3 app in the complete folder. 

Edit  `Engine.groovy` and remove the `belongsTo` line.

https://github.com/grails-guides/discriminator-per-tenant/blob/master/complete/grails-app/domain/example/Engine.groovy#L8

Run integration tests:

complete$ ./gradlew iT

It seems the test fails because it does not create the manufacturer column in the `Engine` table.

```
2017-06-07 20:10:23.057 ERROR --- [o-auto-1-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : Column "ENGINES0_.MANUFACTURER" not found; SQL statement:
select engines0_.vehicle_engines_id as vehicle_1_3_0_, engines0_.engine_id as engine_i2_3_0_, engine1_.id as id1_0_1_, engine1_.version as version2_0_1_, engine1_.manufacturer as manufact3_0_1_, engine1_.cylinders as cylinder4_0_1_ from vehicle_engine engines0_ inner join engine engine1_ on engines0_.engine_id=engine1_.id where ? = engines0_.manufacturer and engines0_.vehicle_engines_id=? [42122-194]
```

### Environment Information

- **Operating System**: MacOS
- **GORM Version:** 6.1.4
- **Grails Version (if using Grails):** 6.2.10
- **JDK Version:** 1.8.0_121

### Example Application

https://github.com/grails-guides/discriminator-per-tenant

**Comment by bryan-lifelink** [comment]
@graemerocher 
I see that the test commented out belongsTo, because it doesn't work.  Is there any plan to make belongsTo relationships work for MultiTenant domains?
