### ISSUE TITLE
Validation does not occur against entities in the persistence context

### ISSUE THREAD

**Issue by tlefevre** [grails/grails-data-mapping#958]
### Steps to Reproduce

1. Download the example project and run a check

### Expected Behaviour

I have a simple domain object with a unique constraint. I have a test with two cases where I expect validation to fail in both instances. In both tests, I make an entity with a string and save it. Afterwards I make another identical instance and call validate on it. In the second test, I make sure to flush during save. 

Both tests should succeed. 

### Actual Behaviour

When I use a H2 database, the test passes in both instances.
When I use a Postgres database, the first test fails and the second(with flush) succeeds.

If I re-enable FlushMode.AUTO the test will succeed when running against a Postgres database.

I would expect validation to be run against entities in the persistence context / hibernate session, but it does not seem like it. I have also seen examples where a findOrCreate incorrectly creates a new entity and puts it into the persistence context, only to fail horribly as soon as the session is flushed because the database enforces the unique constraint.

### Environment Information

- **Operating System**: Linux 4.10.0-22-generic #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **GORM Version:** 6.0.10.RELEASE
- **Grails Version (if using Grails):** 3.2.10
- **JDK Version:** 1.8.0_121

### Example Application
Default runs against a Postgres database. Configuration present to switch to a h2 database instead and/or to quickly switch flush mode.
[postgres-demo.tar.gz](https://github.com/grails/grails-data-mapping/files/1074634/postgres-demo.tar.gz)

**Comment by graemerocher** [comment]
Postgres uses sequence identifiers by default so the actual data is not written to the database until `flush()` is called. This means if you may need to use `save(flush:true)` to ensure consistency with your queries. There is nothing we can do in GORM to "fix" this behaviour and queries cannot run against data that hasn't been persisted. That would require re-implementing all Hibernate query data for in-memory data which isn't possible.

**Comment by tlefevre** [comment]
I am not suggesting that queries be run against data that has not been persisted. That is, obviously, a very silly thing to do. 
I would however not think it too much that when an object is validated, that, for example, uniqueness is tested against objects that are present in the hibernate session. Otherwise, as soon as you are dealing with objects that have a uniqueness constraint, you will be forced to flush immediately always. 
That could be how it is supposed to be, but to me it seems rather clumsy that it would require this level of hand holding.

I may not be describing the issue that well, so hopefully you have taken a look at the spec in the attached project? From what you wrote, it does not seem that I did a very good job of conveying what the issue is.

**Comment by graemerocher** [comment]
Clumsy it may be but I see no way to inspect the current session for loaded objects during validation in a performant way

**Comment by tlefevre** [comment]
Alright - then I guess it's either setting the flush mode back to auto or accept that if you want to ride it manual it requires a delicate touch to get the desired results. Thanks.
