### ISSUE TITLE
@Join does not fetch given relation for data service method

### ISSUE THREAD

**Issue by crosburg** [grails/grails-data-mapping#960]
Thanks for reporting an issue for GORM, please review the task list below before submitting the 
issue.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Pull the example app (https://github.com/crosburg/data-service-lazyInitError)
2. run `gradle check` or `grails test-app`

### Expected Behaviour

I expect the @Join('profile') annotated data service method`findById` to return the User object with fetched UserProfile instance.

### Actual Behaviour

The data service method always returns the User object with unfetched UserProfile.

### Environment Information

- **Operating System**: macOS Sierra 10.12.5
- **GORM Version:** 6.1.4
- **Grails Version (if using Grails):** 3.2.9
- **JDK Version:** 1.8.0_102

### Example Application

- https://github.com/crosburg/data-service-lazyInitError

**Comment by graemerocher** [comment]
Seems to only impact the dynamic finder syntax. Changing:

```groovy
    @Join('profile')
    abstract User findById(Serializable id)
```

To 

```groovy
    @Join('profile')
    abstract User findUser(Serializable id)
```

Resolves the issue
