### ISSUE TITLE
GORM 6.1.4: manual flush needed in @Transactional annotated Services for delete() operations

### ISSUE THREAD

**Issue by mhuebner** [grails/grails-data-mapping#964]
### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. checkout example repo @ https://github.com/mhuebner/flushInTransaction
2. `gradlew check`
3. Tests fail

### Expected Behaviour
No need to flush manually when a service method is annotated with @Transactional.
This is not the case for save() operations.
```
package org.test

import grails.transaction.Transactional

class HouseService {

    @Transactional
    void deleteHouse(House house) {
        house.delete()
    }

    @Transactional
    void saveHouse() {
        new House(name: UUID.randomUUID()).save()
    }
}
```
Might only be a problem in test environment. But still this is an issue which prevents from upgrading to the newest GORM version.

### Actual Behaviour

deleteHouse does not delete the house instance until you use `flush: true` in the delete statement.
saveHouse works as expected

### Environment Information

- **Operating System**: WIN10
- **GORM Version:** 6.1.4.RELEASE
- **Grails Version (if using Grails):** 3.2.10
- **JDK Version:** 1.8

### Example Application

https://github.com/mhuebner/flushInTransaction

**Comment by graemerocher** [comment]
This isn't a bug as far as I can see. The `deleteHouse` operation is running within the test `@Rollback` transaction, and since the session is only flushed when the transaction is committed you get the behaviour you see. As for why this isn't an issue for `save()` it is because you are using auto-increment ids which require an `insert` in order to generate the id if you were to use assigned ids you would see the same behaviour.

**Comment by mhuebner** [comment]
Ok, but this behaviour has changed since 6.0.4. 
The tests were running fine (same setup or just Grails 3.2.10 default). We have many  failing tests now in our apps. Any idea on how to develop integration tests with `@Rollback` and '@Transactional' in the future?

**Comment by graemerocher** [comment]
You can use `hibernate.flush.mode` to `AUTO` to restore the previous behaviour, although performance will be worse if you performance many queries after writes. See the upgrade notes at http://gorm.grails.org/latest/hibernate/manual/index.html#upgradeNotes

**Comment by mhuebner** [comment]
Yes, I was aware of this possibility but this would also change the flush behaviour of the whole app. 
I think we have to change to Unit Spec in this case. 

Many thanks anyway!
