### ISSUE TITLE
Suggestion: Detailed changelog for each new releases

### ISSUE THREAD

**Issue by snimavat** [grails/grails-data-mapping#965]
Can we have a detailed changelog /milestone linked for each new release, which shows what all issues/new features went into the release, along with release notes

That will make it easy to identify what bug fixes/ enhancements to expect when upgrading.

Just like how grails core has it here https://github.com/grails/grails-core/releases 

Gorm docs has it, but its not deailed for each minor release - http://gorm.grails.org/latest/hibernate/manual/index.html#releaseHistory

**Comment by graemerocher** [comment]
Those are already found here https://github.com/grails/grails-data-mapping/milestones?state=closed

**Comment by snimavat** [comment]
Cant we link them with release, how we do it for Grails core @graemerocher
