### ISSUE TITLE
GORM is not initialized correctly

### ISSUE THREAD

**Issue by crosburg** [grails/grails-data-mapping#966]
### Steps to Reproduce

1. Pull the example app (https://github.com/crosburg/hibernate-error-example)
2. Run the AuthSpec integration test

### Expected Behaviour

GORM should be initialized correctly. 

### Actual Behaviour

GORM seems not to be initialized correctly. The spring security rest plugin is not able to authenticate users due to this error (and many other parts are affected as well I guess)

### Environment Information

- **Operating System**: macOS Sierra 10.12.5
- **GORM Version:** 6.1.5
- **Grails Version (if using Grails):** 3.3.0.RC1
- **JDK Version:** 1.8.0_102

### Example Application

https://github.com/crosburg/hibernate-error-example

### Logging output
2017-06-27 23:06:33.865 DEBUG --- [o-auto-1-exec-1] g.p.s.rest.RestAuthenticationFilter      : Authentication failed: **No GORM implementation configured for type [class org.grails.orm.hibernate.HibernateDatastore$2]. Ensure GORM has been initialized correctly**

**Comment by dpcasady** [comment]
Same issue in a multi-tenant app when running a functional test after upgrading to 6.1.5. Seems like it's due to the datastore type being `org.grails.orm.hibernate.HibernateDatastore$2` vs `org.grails.orm.hibernate.HibernateDatastore`.

**Comment by graemerocher** [comment]
The above change resolves the issue. The example now fails with a "No Session Found for Thread error" but this is because the default `GormUserDetailsService` provided by Spring Security is multi-tenant. You would need to override the `loadUserByUsername` and apply the appropriate `@CurrentTenant` annotation to it
