### ISSUE TITLE
Class Tenants doesn't reuse sessions

### ISSUE THREAD

**Issue by artemik** [grails/grails-data-mapping#981]
All methods of the class `Tenants` (for example `Tenants.withId(...)`) result in calling `multiTenantCapableDatastore.withNewSession(tenantIdentifier)` which means a new session is always created regardless if there is an existing session bound to the current thread and corresponding to this tenant. It looks unoptimized.

Is it really necessary? Can existing sessions be reused?
### Environment Information

- **GORM Version:** 6.0.12
- **Grails Version (if using Grails):** 3.2.11

**Comment by graemerocher** [comment]
the `isSharedConnection` method will return true for SCHEMA and DISCRIMINATOR modes so in that case a shared session is used https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm/src/main/groovy/grails/gorm/multitenancy/Tenants.groovy#L201

The only time this is a factory is in `DATABASE` per tenant mode and as per https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-core/src/main/groovy/org/grails/datastore/mapping/multitenancy/MultiTenantCapableDatastore.java#L40

A new session is only created if one is not found. The code leads to

https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/AbstractHibernateDatastore.java#L362

Which calls `executeWithExistingOrCreateNewSession` ensuring session reuse. So as far as I can see this is not an actual bug.
