### ISSUE TITLE
DetachedCriteria.count() returns null

### ISSUE THREAD

**Issue by jameskleeh** [grails/grails-data-mapping#992]
Calling count on a detached criteria that has an offset value returns null. Interestingly, count returns the total number of records even if max is set.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

`def dc = Domain.where {}.max(10).offset(0)`

`dc.count()` returns the count not considering the max value. Good for my use case.

`def dc = Domain.where {}.max(10).offset(10)`

`dc.count()` returns null. I would expect it to return the same value as the previous example.

### Workaround

`dc.offset(0).count()`

**Comment by graemerocher** [comment]
Before applying any kind of fix to this we need to discuss whether the current behaviour is actually correct. So what would you expect? count and offset to always be ignored ?
