### ISSUE TITLE
HibernateSpec doesn't correctly load settings from application.groovy

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-data-mapping#993]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Setup a MultiTenant app and a Unit test (See sample app below from grails-guides)
Put MultiTenant settings in application.groovy
Run tests with HibernateSpec

### Expected Behaviour

HibernateSpec's dataSource should be setup correctly as it is when settings are in application.yml

### Actual Behaviour

```
Current datastore [org.grails.orm.hibernate.HibernateDatastore@58ef5e75] is not configured for Multi-Tenancy
org.grails.datastore.mapping.model.DatastoreConfigurationException: Current datastore [org.grails.orm.hibernate.HibernateDatastore@58ef5e75] is not configured for Multi-Tenancy
	at org.grails.datastore.gorm.services.DefaultTenantService.withCurrent(DefaultTenantService.groovy:74)
	at example.VehicleController.index(VehicleController.groovy:20)
	at example.VehicleControllerSpec.Test the index action returns the correct model(VehicleControllerSpec.groovy:40)
```

### Environment Information

- **Operating System**: Mac
- **GORM Version:** 6.1.6.RELEASE
- **Grails Version (if using Grails):** 3.3.0
- **JDK Version:** 8u141

### Example Application

Tests fail when moving the MT settings from yml to groovy file:
https://github.com/erichelgeson/discriminator-per-tenant/commit/694b3488d45f030d33a38b93ce3438e2d740392c

NOTE: The settings in application.groovy work fine when the app is running in dev or prod, just not in a HibernateSpec unit test.

**Comment by graemerocher** [comment]
The two configuration are not equivalent. You have:

```groovy
grails.gorm.multiTenancy = "DISCRIMINATOR"
grails.gorm.tenantResolverClass = "org.grails.datastore.mapping.multitenancy.web.SessionTenantResolver"
```

But the YAML is:

```yaml
grails:
        multiTenancy:
            mode: DISCRIMINATOR
            tenantResolverClass: org.grails.datastore.mapping.multitenancy.web.SessionTenantResolver
```

The correct equivalent  Groovy config is:

```groovy
grails.gorm.multiTenancy.mode = "DISCRIMINATOR"
grails.gorm.multiTenancy.tenantResolverClass = "org.grails.datastore.mapping.multitenancy.web.SessionTenantResolver"
```
