### ISSUE TITLE
Question: ClassPropertyFetcher accessing non static property value

### ISSUE THREAD

**Issue by mamunsardar** [grails/grails-data-mapping#995]
In `grails-datastore-core-6.0.9.RELEASE` (grails 3.2.8) using `org.grails.datastore.mapping.reflect.ClassPropertyFetcher` could extract non static property value. But in `6.1.6.RELEASE` (grails 3.3.0) only static property value can be extracted and non static property value returns null. What changed?

Example code to extract property value: 
```
ClassPropertyFetcher.forClass(Foo).getPropertyValue("name", String.class);
```

**Comment by jameskleeh** [comment]
The method to get property values on instances is: https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-core/src/main/groovy/org/grails/datastore/mapping/reflect/ClassPropertyFetcher.java#L162
